--실전문제②
SELECT M1.INVOICE_NO, M1.OUTBOUND_DATE, M1.OUT_TYPE_DIV, M2.LINE_NO, M2.ITEM_CD, C1.ITEM_NM, M2.ORDER_QTY
     , C2.CODE_NM AS TEMP_NM
     , C3.CODE_NM AS OUT_TYPE_NM
  FROM LO_OUT_M M1
       JOIN LO_OUT_D M2 ON  M2.INVOICE_NO = M1.INVOICE_NO
       JOIN CM_ITEM  C1 ON  C1.ITEM_CD    = M2.ITEM_CD
       JOIN CS_CODE  C2 ON  C2.CODE_GRP   = 'LDIV01'
                        AND C2.CODE_CD    = M1.TEMP_DIV
       JOIN CS_CODE  C3 ON  C3.CODE_GRP   = 'LDIV03'
                        AND C3.CODE_CD    = M1.OUT_TYPE_DIV
 WHERE M1.INVOICE_NO IN ('346724703834', '346724722535', '346724717915')
 ORDER BY M1.INVOICE_NO, M2.LINE_NO
;

--SELECT *
--FROM CS_CODE;

--실전문제①
SELECT M1.INVOICE_NO, M1.OUTBOUND_DATE, M1.OUT_TYPE_DIV, M2.LINE_NO, M2.ITEM_CD, C1.ITEM_NM, M2.ORDER_QTY
  FROM LO_OUT_M M1
       JOIN LO_OUT_D M2 ON  M2.INVOICE_NO = M1.INVOICE_NO
       JOIN CM_ITEM C1  ON  C1.ITEM_CD    = M2.ITEM_CD
 WHERE M1.INVOICE_NO IN ('346724703834', '346724722535', '346724717915')
 ORDER BY M1.INVOICE_NO, M2.LINE_NO
;

--예제
--1) 고정배수 복재
SELECT *
  FROM (
        SELECT 'A' AS ITEM, 1 AS QTY FROM DUAL UNION ALL
        SELECT 'B' AS ITEM, 2 AS QTY FROM DUAL
        ) M1
        JOIN CS_NO C1 ON    C1.NO <= 2
;

--2) 변동배수 복제
SELECT *
  FROM (
        SELECT 'A' AS ITEM, 1 AS QTY FROM DUAL UNION ALL
        SELECT 'B' AS ITEM, 2 AS QTY FROM DUAL
        ) M1
        JOIN CS_NO C1 ON    C1.NO <= M1.QTY
;
----
SELECT .COUNT(1)
  FROM DUAL
 CONNECT BY LEVEL <= TO_DATE('2026-12-31', 'YYYY-MM-DD') - TRUNC(SYSDATE)
;

SELECT TRUNC(SYSDATE) + LEVEL
  FROM DUAL
 CONNECT BY LEVEL <= 10
;

--<2-4>
SELECT *
  FROM (
        SELECT M3.*
              , TRUNC(SUM_QTY / QTY_IN_BOX) AS BOX_CNT
              , MOD(SUM_QTY, QTY_IN_BOX)    AS ITEM_CNT
          FROM (
                SELECT M1.BRAND_CD, M2.ITEM_CD, C1.ITEM_NM, C1.QTY_IN_BOX, SUM(M2.ORDER_QTY) AS SUM_QTY
                  FROM A_OUT_M M1
                       JOIN A_OUT_D M2 ON  M2.BRAND_CD   = M1.BRAND_CD
                                       AND M2.INVOICE_NO = M1.INVOICE_NO
                       JOIN A_ITEM  C1 ON  C1.BRAND_CD   = M2.BRAND_CD
                                       AND C1.ITEM_CD    = M2.ITEM_CD
                 WHERE OUTBOUND_DATE BETWEEN TO_DATE('2023-01-01', 'YYYY-MM-DD')
                                         AND TO_DATE('2023-01-04', 'YYYY-MM-DD')
                 GROUP BY M1.BRAND_CD, M2.ITEM_CD, C1.ITEM_NM, C1.QTY_IN_BOX
                ) M3
          ORDER BY BOX_CNT DESC
        ) 
 WHERE ROWNUM <= 3
;

--<2-3>
SELECT M3.*
      , TRUNC(SUM_QTY / QTY_IN_BOX) AS BOX_CNT
      , MOD(SUM_QTY, QTY_IN_BOX)    AS ITEM_CNT
  FROM (
        SELECT M1.BRAND_CD, M2.ITEM_CD, C1.ITEM_NM, C1.QTY_IN_BOX, SUM(M2.ORDER_QTY) AS SUM_QTY
          FROM A_OUT_M M1
               JOIN A_OUT_D M2 ON  M2.BRAND_CD   = M1.BRAND_CD
                               AND M2.INVOICE_NO = M1.INVOICE_NO
               JOIN A_ITEM  C1 ON  C1.BRAND_CD   = M2.BRAND_CD
                               AND C1.ITEM_CD    = M2.ITEM_CD
         WHERE OUTBOUND_DATE BETWEEN TO_DATE('2023-01-01', 'YYYY-MM-DD')
                                 AND TO_DATE('2023-01-04', 'YYYY-MM-DD')
         GROUP BY M1.BRAND_CD, M2.ITEM_CD, C1.ITEM_NM, C1.QTY_IN_BOX
        ) M3
;

--<2-2>
SELECT M1.BRAND_CD, M2.ITEM_CD, C1.ITEM_NM, C1.QTY_IN_BOX, SUM(M2.ORDER_QTY) AS SUM_QTY
  FROM A_OUT_M M1
       JOIN A_OUT_D M2 ON  M2.BRAND_CD   = M1.BRAND_CD
                       AND M2.INVOICE_NO = M1.INVOICE_NO
       JOIN A_ITEM  C1 ON  C1.BRAND_CD   = M2.BRAND_CD
                       AND C1.ITEM_CD    = M2.ITEM_CD
 WHERE OUTBOUND_DATE BETWEEN TO_DATE('2023-01-01', 'YYYY-MM-DD')
                         AND TO_DATE('2023-01-04', 'YYYY-MM-DD')
 GROUP BY M1.BRAND_CD, M2.ITEM_CD, C1.ITEM_NM, C1.QTY_IN_BOX
;

--<2-1>
SELECT M1.BRAND_CD, M1.OUTBOUND_DATE, M1.INVOICE_NO, M2.ITEM_CD
     , M3.ITEM_CD, M2.ORDER_QTY
  FROM A_OUT_M M1
       JOIN A_OUT_D M2 ON  M2.BRAND_CD   = M1.BRAND_CD
                       AND M2.INVOICE_NO = M1.INVOICE_NO
                       AND M2.ORDER_QTY >= 3
       JOIN A_ITEM  M3 ON  M3.BRAND_CD   = M1.BRAND_CD
                       AND M3.ITEM_CD    = M2.ITEM_CD
 WHERE OUTBOUND_DATE BETWEEN TO_DATE('2023-01-01', 'YYYY-MM-DD')
                         AND TO_DATE('2023-01-04', 'YYYY-MM-DD')
;

--<1-3>
SELECT INVOICE_NO, ORDER_NM
  FROM (
        SELECT M1.INVOICE_NO, M1.ORDER_NM, SUM(M2.ORDER_QTY) AS SUM_QTY
          FROM A_OUT_M M1
               JOIN A_OUT_D M2 ON  M2.BRAND_CD   = M1.BRAND_CD
                               AND M2.INVOICE_NO = M1.INVOICE_NO
         WHERE M1.BRAND_CD = '1001'
           AND M1.OUTBOUND_DATE BETWEEN TO_DATE('2023-01-04', 'YYYY-MM-DD')
                                    AND TO_DATE('2023-01-05', 'YYYY-MM-DD')
         GROUP BY M1.INVOICE_NO, M1.ORDER_NM
         ORDER BY SUM_QTY DESC
        )
 WHERE ROWNUM = 1
;

--<1-2>
SELECT M1.BRAND_CD, M1.OUTBOUND_DATE, M2.ITEM_CD, SUM(M2.ORDER_QTY) AS 주문수량합계
  FROM A_OUT_M M1 
        JOIN A_OUT_D M2 ON  M2.BRAND_CD   = M1.BRAND_CD
                        AND M2.INVOICE_NO = M1.INVOICE_NO
                        AND M2.ITEM_CD IN ('B', 'D')
 WHERE M1.OUTBOUND_DATE BETWEEN TO_DATE('2023-01-03', 'YYYY-MM-DD')
                            AND TO_DATE('2023-01-04', 'YYYY-MM-DD')
 GROUP BY M1.BRAND_CD, M1.OUTBOUND_DATE, M2.ITEM_CD
 ORDER BY M1.BRAND_CD, M1.OUTBOUND_DATE, M2.ITEM_CD
;

--<1-1>
SELECT M1.BRAND_CD, M1.OUTBOUND_DATE, M1.INVOICE_NO, M2.LINE_NO, M2.ORDER_QTY
  FROM A_OUT_M M1 
       JOIN A_OUT_D M2 ON  M2.BRAND_CD   = M1.BRAND_CD
                       AND M2.INVOICE_NO = M1.INVOICE_NO
                       AND M2.ITEM_CD IN ('B', 'D')
 WHERE M1.OUTBOUND_DATE = TO_DATE('2023-01-04', 'YYYY-MM-DD')
   
;

--예제
SELECT M1.ITEM, M1.QTY, M2.ITEM, M2.QTY
  FROM (
        SELECT 'A' ITEM, 1 AS QTY FROM DUAL UNION ALL
        SELECT 'B' ITEM, 2 AS QTY FROM DUAL UNION ALL
        SELECT 'C' ITEM, 3 AS QTY FROM DUAL
      ) M1
--      JOIN (
--           SELECT 'A' ITEM, 2 AS QTY FROM DUAL UNION ALL
--            SELECT 'D' ITEM, 1 AS QTY FROM DUAL
--            ) M2 ON 1 = 1
      CROSS JOIN (
            SELECT 'A' ITEM, 2 AS QTY FROM DUAL UNION ALL
            SELECT 'D' ITEM, 1 AS QTY FROM DUAL
            ) M2
;

