--문제①
WITH BASE_01 AS(
SELECT TO_CHAR(M1.OUTBOUND_DATE, 'DY') AS DY
     , SUM(ORDER_QTY) AS ORDER_QTY
  FROM LO_OUT_M M1
       JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
 WHERE OUTBOUND_DATE BETWEEN ADD_MONTHS(TO_DATE(:OUTBOUND_DATE, 'YYYY-MM-DD'), -1)
                         AND TO_DATE(:OUTBOUND_DATE, 'YYYY-MM-DD') 
 GROUP BY TO_CHAR(M1.OUTBOUND_DATE, 'DY')
 ORDER BY ORDER_QTY DESC
),
BASE_02 AS(
SELECT BASE_01.*
      , ROW_NUMBER() OVER(ORDER BY ORDER_QTY DESC) AS RNK
  FROM BASE_01
)

SELECT DY, ORDER_QTY
  FROM BASE_02
 WHERE RNK <= 3

UNION ALL

SELECT 'etc' AS DY
     , SUM(ORDER_QTY) AS ORDER_QTY
  FROM BASE_02
 WHERE RNK > 3
;

--문제②
SELECT SUM(CASE WHEN TO_CHAR(M1.OUTBOUND_DATE, 'D') BETWEEN '2' AND '6' THEN
                  M2.ORDER_QTY END) AS WEEKDAY_OUTPUT
     , SUM(CASE WHEN TO_CHAR(M1.OUTBOUND_DATE, 'D') IN ('1', '7') THEN
                  M2.ORDER_QTY END) AS WEEKEND_OUTPUT
  FROM LO_OUT_M M1
       JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
 WHERE M1.OUTBOUND_DATE BETWEEN ADD_MONTHS(TO_DATE(:OUTBOUND_DATE, 'YYYY-MM-DD'), -1)
                            AND TO_DATE(:OUTBOUND_DATE, 'YYYY-MM-DD') 
;

--문제③
SELECT CASE WHEN TO_CHAR(M1.OUTBOUND_DATE, 'D') BETWEEN '2' AND '6' THEN 'WEEKDAY'
            WHEN TO_CHAR(M1.OUTBOUND_DATE, 'D') IN ('1', '7')       THEN 'WEEKEND'
       END AS WEEK
    ,  SUM(M2.ORDER_QTY) AS SUM_QTY
  FROM LO_OUT_M M1
       JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
 WHERE M1.OUTBOUND_DATE BETWEEN ADD_MONTHS(TO_DATE(:OUTBOUND_DATE, 'YYYY-MM-DD'), -1)
                            AND TO_DATE(:OUTBOUND_DATE, 'YYYY-MM-DD') 
 GROUP BY CASE WHEN TO_CHAR(M1.OUTBOUND_DATE, 'D') BETWEEN '2' AND '6' THEN 'WEEKDAY'
               WHEN TO_CHAR(M1.OUTBOUND_DATE, 'D') IN ('1', '7')       THEN 'WEEKEND'
          END
;

--문제④
SELECT TO_CHAR(OUT_DATE, 'YYYY/MM/DD') AS OUT_DATE
      , TO_CHAR(OUT_DATE, 'DY') AS DY
FROM (SELECT (TO_DATE(:OUTBOUND_DATE, 'YYYY-MM-DD') - 31) + LEVEL AS OUT_DATE--ADD_MONTHS(TO_DATE(:OUTBOUND_DATE, 'YYYY-MM-DD') + LEVEL + 1
        FROM DUAL
        CONNECT BY LEVEL < 31--TO_DATE(:OUTBOUND_DATE, 'YYYY-MM-DD') - ADD_MONTHS(TO_DATE(:OUTBOUND_DATE, 'YYYY-MM-DD'), -1) + 1
      ) M3 LEFT JOIN (
           SELECT OUTBOUND_DATE, ORDER_QTY
            FROM LO_OUT_M M1 JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO) M4 ON M3.OUT_DATE = M4.OUTBOUND_DATE
 WHERE M3.OUT_DATE BETWEEN ADD_MONTHS(TO_DATE(:OUTBOUND_DATE, 'YYYY-MM-DD'), -1) --WHERE NOT EXISTS (..... = OUT_DATE)
                       AND TO_DATE(:OUTBOUND_DATE, 'YYYY-MM-DD') 
  AND OUTBOUND_DATE IS NULL
;

--문제⑤
WITH BASE_01 AS (
SELECT M1.OUTBOUND_DATE
     , TO_CHAR(M1.OUTBOUND_DATE, 'DY') AS DY
     , SUM(M2.ORDER_QTY) AS SUM_QTY
  FROM LO_OUT_M M1
       JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
 WHERE M1.OUTBOUND_DATE BETWEEN ADD_MONTHS(TO_DATE(:OUTBOUND_DATE, 'YYYY-MM-DD'), -1)
                            AND TO_DATE(:OUTBOUND_DATE, 'YYYY-MM-DD') 
 GROUP BY M1.OUTBOUND_DATE
),
BASE_02 AS (
SELECT *
  FROM BASE_01
 WHERE SUM_QTY >= 170000
),
BASE_03 AS (
SELECT TO_CHAR(OUTBOUND_DATE, 'DY') AS DY
     , ROUND(AVG(SUM_QTY)) AS AVG_QTY
  FROM BASE_01
 GROUP BY TO_CHAR(OUTBOUND_DATE, 'DY')
)
SELECT R1.OUTBOUND_DATE, R1.DY, R1.SUM_QTY
    , CASE WHEN R1.SUM_QTY > R2.AVG_QTY THEN 'High' ELSE 'Low' END AS GRADE
    , R2.AVG_QTY
 FROM BASE_02 R1
     JOIN BASE_03 R2 ON R1.DY = R2.DY
 ORDER BY R1.OUTBOUND_DATE
;

--보너스 문제
--교수님 답안
SELECT CASE :SCHOOL WHEN '1' THEN '초등학교 ' WHEN '2' THEN '중학교 ' WHEN '3' THEN '고등학교 ' END || TO_CHAR(NO) || '학년' AS SCHOOL 
     , TO_NUMBER(SUBSTR(:BIRTHDAY, 1, 4)) + CASE :SCHOOL WHEN '1' THEN  6 + NO WHEN '2' THEN  6 + 6 + NO WHEN '3' THEN  6 + 6 + 3 + NO END AS YEAR
  FROM CS_NO
 WHERE NO <= CASE :SCHOOL WHEN '1' THEN 6 WHEN '2' THEN 3 WHEN '3' THEN 3 END
;

--오답
WITH ELEMENT_SCHOOL AS (
SELECT '초등학교 ' || LEVEL || '학년' AS SCHOOL
     , TO_NUMBER(TO_CHAR(TO_DATE(:BIRTHDAY, 'YYYY-MM-DD'), 'YYYY')) + LEVEL + 6 AS YEAR
  FROM DUAL
CONNECT BY LEVEL <= 6
),
MIDDLE_SCHOOL AS (
SELECT '중학교 ' || LEVEL || '학년' AS SCHOOL
     , TO_NUMBER(TO_CHAR(TO_DATE(:BIRTHDAY, 'YYYY-MM-DD'), 'YYYY')) + LEVEL + 12 AS YEAR
  FROM DUAL
CONNECT BY LEVEL <= 3
),
HIGH_SCHOOL AS (
SELECT '고등학교 ' || LEVEL || '학년' AS SCHOOL
     , TO_NUMBER(TO_CHAR(TO_DATE(:BIRTHDAY, 'YYYY-MM-DD'), 'YYYY')) + LEVEL + 15 AS YEAR
  FROM DUAL
CONNECT BY LEVEL <= 3
),
SCHOOL_TAB AS (
SELECT *
  FROM ELEMENT_SCHOOL
UNION ALL
SELECT *
  FROM MIDDLE_SCHOOL
UNION ALL
SELECT *
  FROM HIGH_SCHOOL
)

SELECT *
  FROM SCHOOL_TAB
 WHERE CASE WHEN :SCHOOL = '3' THEN ROWNUM < 13
            WHEN :SCHOOL = '2' THEN ROWNUM < 10
            WHEN :SCHOOL = '1' THEN ROWNUM < 7  
 END
;