--실전문제④
SELECT TO_CHAR(M3.OUT_DATE, 'YYYY/MM/DD') AS OUT_DATE
     , NVL(M4.QTY, 0) AS QTY
FROM (
       SELECT TRUNC(TO_DATE(:OUTBOUND_DATE, 'YYYY-MM-DD'), 'MM') + LEVEL - 1 AS OUT_DATE
         FROM DUAL
      CONNECT BY LEVEL <= TO_DATE(:OUTBOUND_DATE, 'YYYY-MM-DD') - TRUNC(TO_DATE(:OUTBOUND_DATE, 'YYYY-MM-DD'), 'MM') + 1
      ) M3 LEFT JOIN (
                      SELECT M1.OUTBOUND_DATE AS OUT_DATE, SUM(M2.ORDER_QTY) AS QTY
                        FROM LO_OUT_M M1
                             JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
                       WHERE M1.OUTBOUND_DATE BETWEEN TRUNC(TO_DATE(:OUTBOUND_DATE, 'YYYY-MM-DD'), 'MM') AND TO_DATE(:OUTBOUND_DATE, 'YYYY-MM-DD')
                       GROUP BY M1.OUTBOUND_DATE
                      ) M4
            ON M4.OUT_DATE = M3.OUT_DATE
 ORDER BY OUT_DATE
;

--LO_OUT_M: INVOICE_NO, OUTBOUND_DATE, OUTBOUND_NO, ORDER_PLACE, OUTBOUND_BATCH, TEMP_DIV, OUT_TYPE_DIV, OUT_BOX_DIV, OUT_BOX_NM, SET_TYPE_CD, SET_TYPE_NM, SET_QTY, SET_STATE, WORK_SEQ, REG_USER_ID, REG_DATETIME
--LO_OUT_D: INVOICE_NO, LINE_NO, ITEM_CD, ITEM_NM, ITEM_BAR_CD, BOX_BAR_CD, ITEM_WEIGHT, QTY_IN_BOX, BOX_WEIGHT, ITEM_WIDTH, ITEM_LENGTH, ITEM_HEIGHT, ITEM_CBM, SALE_PLACE, ORDER_QTY, REG_USER_ID, REG_DATETIME, OUT_TYPE_DIV_D
--CM_ITEM: ITEM_CD, ITEM_NM, QTY_IN_BOX, REG_USER_ID, REG_DATETIME

--실전문제③
SELECT M1.INVOICE_NO, M1.OUTBOUND_DATE, M1.OUT_TYPE_DIV, M2.LINE_NO, M2.ITEM_CD, C1.ITEM_NM, M2.ORDER_QTY
     , NVL(C2.CODE_NM, 'Failed...') AS TEMP_NM
     , NVL(C3.CODE_NM, 'Failed...') AS OUT_TYPE_NM
  FROM LO_OUT_M M1
            JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
            JOIN CM_ITEM  C1 ON C1.ITEM_CD    = M2.ITEM_CD
       LEFT JOIN CS_CODE  C2 ON C2.CODE_GRP   = 'LDIV011' 
                            AND C2.CODE_CD = M1.TEMP_DIV
       LEFT JOIN CS_CODE  C3 ON C3.CODE_GRP   = 'LDIV03'  
                            AND C3.CODE_CD = M1.OUT_TYPE_DIV
 WHERE M1.INVOICE_NO         IN ('346724703834', '346724722535', '346724717915')
 ORDER BY M1.INVOICE_NO, M2.LINE_NO
;

--실전문제②
SELECT M2.ITEM_CD, C1.ITEM_NM, SUM(M2.ORDER_QTY) AS ORDER_QTY
  FROM LO_OUT_M M1
       JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
       JOIN CM_ITEM  C1 ON C1.ITEM_CD    = M2.ITEM_CD
 WHERE OUTBOUND_DATE BETWEEN '2019-09-03' AND '2019-09-10'
   AND OUT_BOX_DIV = 'D5'
 GROUP BY M2.ITEM_CD, C1.ITEM_NM
 ORDER BY SUM(M2.ORDER_QTY) DESC
;

--실전문제①
SELECT *
  FROM (
        SELECT M1.INVOICE_NO, M1.OUTBOUND_NO, M1.OUTBOUND_BATCH, M2.ITEM_CD, M2.ITEM_NM, SUM(M2.ORDER_QTY) AS ORDER_QTY
          FROM LO_OUT_M M1  
               JOIN LO_OUT_D M2  ON M2.INVOICE_NO = M1.INVOICE_NO
                                AND M2.ITEM_NM LIKE    '%골뱅이%'
         WHERE M1.OUTBOUND_DATE BETWEEN '2019-09-03' AND '2019-09-10'
         GROUP BY M1.INVOICE_NO, M1.OUTBOUND_NO, M1.OUTBOUND_BATCH, M2.ITEM_CD, M2.ITEM_NM
         ORDER BY ORDER_QTY DESC, M1.INVOICE_NO
        )
 WHERE ROWNUM <= 5
;