SELECT ROWNUM AS RNUM
      ,OUTBOUND_DATE
      ,INV_CNT
  FROM (
        SELECT OUTBOUND_DATE, COUNT(*) AS INV_CNT
          FROM LO_OUT_M
         WHERE OUTBOUND_DATE BETWEEN :OUTBOUND_DATE1 AND :OUTBOUND_DATE2
           --AND ROWNUM <= 3
         GROUP BY OUTBOUND_DATE
         ORDER BY INV_CNT DESC
        )
WHERE ROWNUM <= 3
;

--<13>
SELECT ROWNUM AS RNK
  ,OUTBOUND_DATE
  ,INVOICE_CNT
FROM (
  SELECT OUTBOUND_DATE
          ,COUNT(1) AS INVOICE_CNT
    FROM LO_OUT_M
   WHERE OUTBOUND_DATE BETWEEN :OUTBOUND_DATE1 AND :OUTBOUND_DATE2
   GROUP BY OUTBOUND_DATE
   ORDER BY INVOICE_CNT DESC
   )
WHERE ROWNUM <= 5
;

--<11>
SELECT 1 AS NO
  FROM DUAL
UNION
SELECT 4 AS NO
  FROM DUAL
UNION
SELECT 3 AS NO
  FROM DUAL
UNION
SELECT 1 AS NO
  FROM DUAL
;

--<10>
SELECT ITEM_CD, SUM(ORDER_QTY) AS SUM_ORDER_QTY
  FROM A_OUT_D
WHERE BRAND_CD IN ('1001', '2001')
  AND ORDER_QTY BETWEEN 1 AND 2
 GROUP BY ITEM_CD
HAVING SUM(ORDER_QTY) BETWEEN 2 AND 4
 ORDER BY ITEM_CD DESC
;

--<9>
SELECT ITEM_CD, SUM(ORDER_QTY) AS SUM_ORDER_QTY
  FROM A_OUT_D
WHERE BRAND_CD IN ('1001', '2001')
  AND ORDER_QTY BETWEEN 1 AND 2
GROUP BY ITEM_CD
ORDER BY SUM_ORDER_QTY DESC
;

--<8> ≒ DISTINCT
SELECT ITEM_CD
  FROM A_OUT_D
WHERE BRAND_CD  IN ('1001', '1002')
  AND ORDER_QTY BETWEEN 1 AND 2
GROUP BY ITEM_CD
ORDER BY ITEM_CD
;

--<7>
SELECT DISTINCT BRAND_CD, ITEM_CD, ORDER_QTY
  FROM A_OUT_D
WHERE BRAND_CD  IN ('1001', '2001')
  AND ORDER_QTY BETWEEN 1 AND 2
ORDER BY BRAND_CD, ITEM_CD
;

--<6>
SELECT BRAND_CD, INVOICE_NO, OUTBOUND_DATE, OUT_TYPE_DIV, ORDER_NM
  FROM A_OUT_M
WHERE BRAND_CD          = '1001'
  AND OUT_TYPE_DIV    IN ('M11', 'M12')
  AND OUTBOUND_DATE   BETWEEN TO_DATE('20230104', 'YYYYMMDD') AND
                              TO_DATE('20230105', 'YYYYMMDD')
  AND INVOICE_NO      LIKE '#0%'
ORDER BY OUT_TYPE_DIV ASC, OUTBOUND_DATE DESC
;

--<5>
SELECT BRAND_CD, INVOICE_NO, OUTBOUND_DATE, OUT_TYPE_DIV, ORDER_NM
    FROM A_OUT_M
WHERE BRAND_CD          = '1001'
    AND OUT_TYPE_DIV    IN ('M11', 'M12')
    AND OUTBOUND_DATE   BETWEEN TO_DATE('20230104', 'YYYYMMDD') AND
                                TO_DATE('20230105', 'YYYYMMDD')
    AND INVOICE_NO      LIKE '#0%'
;


--<4>
SELECT *
    FROM A_OUT_M
WHERE BRAND_CD = '1001'
    OR OUTBOUND_DATE = TO_DATE('20230103', 'YYYY-MM-DD')
;


--<3>
SELECT *
    FROM A_OUT_M
WHERE BRAND_CD = '1001'
    AND OUTBOUND_DATE = TO_DATE('20230103', 'YYYY-MM-DD')
;


--<2>
SELECT DISTINCT OUTBOUND_DATE, OUT_TYPE_DIV
    FROM A_OUT_M
;

--<1>
    SELECT *
    FROM A_ITEM
;