--<3-5>
SELECT BRAND_CD AS 브랜드, MAX(ORDER_QTY) AS 최대, MIN(ORDER_QTY) AS 최소
 FROM A_OUT_D
 GROUP BY BRAND_CD
;

--<3-4>
SELECT BRAND_CD AS 브랜드, ITEM_CD AS 상품, SUM(ORDER_QTY) AS N
 FROM A_OUT_D
 GROUP BY BRAND_CD, ITEM_CD
;

--<3-3>
SELECT BRAND_CD AS 브랜드, SUM(ORDER_QTY) AS N
 FROM A_OUT_D
 GROUP BY BRAND_CD
;

--<3-2>
SELECT BRAND_CD AS 브랜드, OUTBOUND_DATE AS 출고일자, COUNT(1) AS N
 FROM A_OUT_M
 GROUP BY BRAND_CD, OUTBOUND_DATE
;

--<3-1>
SELECT BRAND_CD AS 브랜드, COUNT(1) AS N
 FROM A_OUT_M
 GROUP BY BRAND_CD
;

--<2-2>
SELECT SUM(ORDER_QTY) AS N
  FROM A_OUT_D
 WHERE BRAND_CD = '1001'
;

--<2-1>
SELECT COUNT(1) AS N
  FROM A_OUT_M
 WHERE OUTBOUND_DATE BETWEEN TO_DATE('2023-01-03', 'YYYY-MM-DD')
                         AND TO_DATE('2023-01-04', 'YYYY-MM-DD')
;

--<1-3>
SELECT *
  FROM (
        SELECT BRAND_CD AS 브랜드, INVOICE_NO AS 인보이스, ITEM_CD AS 상품코드, ORDER_QTY AS 주문수량
          FROM A_OUT_D
         WHERE INVOICE_NO LIKE '#0%'
           AND ORDER_QTY  >= 3
         ORDER BY ORDER_QTY DESC, ITEM_CD DESC
        )
 WHERE ROWNUM <= 2
;

--<1-2>
SELECT BRAND_CD AS 브랜드, INVOICE_NO AS 인보이스, ITEM_CD AS 상품코드, ORDER_QTY AS 주문수량
  FROM A_OUT_D
 WHERE INVOICE_NO LIKE '#0%'
   AND ORDER_QTY  >= 3
 ORDER BY ORDER_QTY DESC, ITEM_CD ASC
;

--<1-1>
SELECT BRAND_CD AS 브랜드, INVOICE_NO AS 인보이스, ITEM_CD AS 상품코드, ORDER_QTY AS 주문수량
  FROM A_OUT_D
 WHERE INVOICE_NO LIKE '#0%'
   AND ORDER_QTY  >= 3
 ORDER BY ORDER_QTY DESC
;