--<2-3>
SELECT CASE WHEN ROWNUM <= 2 THEN ITEM_CD ELSE 'etc' END ITEM
      , SUM(SUM_QTY) AS SUM_QTY
  FROM (
        SELECT ITEM_CD, SUM(ORDER_QTY) AS SUM_QTY
          FROM A_OUT_D
         GROUP BY ITEM_CD
         ORDER BY SUM_QTY DESC
        )
 GROUP BY CASE WHEN ROWNUM <= 2 THEN ROWNUM ELSE 999 END
        , CASE WHEN ROWNUM <= 2 THEN ITEM_CD ELSE 'etc' END 
 ORDER BY CASE WHEN ROWNUM <= 2 THEN ROWNUM ELSE 999 END
;

--<2-2>
SELECT BRAND_CD AS 브랜드
      , CASE 
          WHEN SUM_QTY > 4 THEN '상'
          WHEN SUM_QTY > 2 THEN '중'
          WHEN SUM_QTY > 0 THEN '하'
          END AS GRADE_DIV
       , SUM(SUM_QTY) AS INV_SUM
 FROM (
      SELECT BRAND_CD, INVOICE_NO, SUM(ORDER_QTY) AS SUM_QTY
        FROM A_OUT_D
       GROUP BY BRAND_CD, INVOICE_NO
       )
 GROUP BY BRAND_CD 
        , CASE 
            WHEN SUM_QTY > 4 THEN '상'
            WHEN SUM_QTY > 2 THEN '중'
            WHEN SUM_QTY > 0 THEN '하'
          END
;

--<2-1>
SELECT BRAND_CD AS 브랜드 
      ,CASE SUBSTR(OUT_TYPE_DIV, 1, 2) 
            WHEN 'M1' THEN '상온'
            WHEN 'M2' THEN '저온'
            END AS TEMP_DIV
      ,COUNT(1) AS INV_CNT
  FROM A_OUT_M
 GROUP BY BRAND_CD 
        , CASE SUBSTR(OUT_TYPE_DIV, 1, 2) 
            WHEN 'M1' THEN '상온'
            WHEN 'M2' THEN '저온'
            END
;

--<1-2>
SELECT BRAND_CD, INVOICE_NO, LINE_NO, ITEM_CD, ORDER_QTY
      , CASE 
          WHEN ORDER_QTY > 4 THEN '상'
          WHEN ORDER_QTY > 2 THEN '중'
          WHEN ORDER_QTY > 0 THEN '하'
          END AS GRADE
 FROM A_OUT_D
;

--<1-1>
SELECT OUTBOUND_DATE, TO_CHAR(OUTBOUND_DATE, 'DY') AS DY, INVOICE_NO
      ,CASE MOD(TO_NUMBER(SUBSTR(INVOICE_NO, 2)), 2) WHEN 0 THEN '짝수' ELSE '홀수' END AS EVENODD
      ,ORDER_NM
      ,CASE SUBSTR(OUT_TYPE_DIV, 1, 2) 
            WHEN 'M1' THEN '상온'
            WHEN 'M2' THEN '저온'
            END AS TEMP_DIV
  FROM A_OUT_M
;

--<5>
SELECT CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '01' THEN SET_QTY END AS M01
      ,CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '02' THEN SET_QTY END AS M02
      ,CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '03' THEN SET_QTY END AS M03
      ,CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '04' THEN SET_QTY END AS M04
      ,CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '05' THEN SET_QTY END AS M05
      ,CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '06' THEN SET_QTY END AS M06
      ,CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '07' THEN SET_QTY END AS M07
      ,CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '08' THEN SET_QTY END AS M08
      ,CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '09' THEN SET_QTY END AS M09
      ,CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '10' THEN SET_QTY END AS M10
      ,CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '11' THEN SET_QTY END AS M11
      ,CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '12' THEN SET_QTY END AS M12
  FROM LO_OUT_M
 WHERE OUTBOUND_DATE BETWEEN TO_DATE('20190101', 'YYYY-MM-DD')
                         AND TO_DATE('20191231', 'YYYY-MM-DD')
;
      