--실전문제④
SELECT CASE WHEN RNK <= 5 THEN TO_CHAR(OUTBOUND_DATE, 'YYYY-MM-DD') ELSE '기타' END AS OUTBOUND_DATE
     , SUM(ORDER_QTY) AS ORDER_QTY
     , MIN(RNK)       AS RNK
     , SUM(RATE)      AS RATE
  FROM (
        SELECT M1.OUTBOUND_DATE, SUM(M2.ORDER_QTY) AS ORDER_QTY
             , ROW_NUMBER() OVER(ORDER BY SUM(M2.ORDER_QTY) DESC) AS RNK
             , ROUND(RATIO_TO_REPORT(SUM(M2.ORDER_QTY)) OVER() * 100, 3) AS RATE
          FROM LO_OUT_M M1
               JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
         WHERE OUTBOUND_DATE BETWEEN '2019-09-01' AND '2019-09-15'
         GROUP BY M1.OUTBOUND_DATE
        )
 GROUP BY CASE WHEN RNK <= 5 THEN TO_CHAR(OUTBOUND_DATE, 'YYYY-MM-DD') ELSE '기타' END
 ORDER BY RNK
;

--실전문제③
SELECT CASE WHEN LAG(OUT_DATE) OVER(PARTITION BY OUT_DATE ORDER BY OUT_DATE) IS NULL THEN TO_CHAR(OUT_DATE, 'YY/MM/DD') END AS OUT_DATE
      , OUTBOUND_BATCH, ORDER_QTY, SUM_PER_DAY
      , DENSE_RANK()         OVER(ORDER BY SUM_PER_DAY DESC)           AS RANK_SUM_PER_DAY
      , RANK()               OVER(ORDER BY ORDER_QTY DESC)             AS RANK_TOT
  FROM (
        SELECT M1.OUTBOUND_DATE AS OUT_DATE, M1.OUTBOUND_BATCH, SUM(M2.ORDER_QTY)   AS ORDER_QTY
             , SUM(SUM(M2.ORDER_QTY)) OVER(PARTITION BY OUTBOUND_DATE)              AS SUM_PER_DAY
          FROM LO_OUT_M M1
               JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
         WHERE M1.OUTBOUND_DATE    BETWEEN '2019-09-03' AND '2019-09-10'
           AND M1.OUT_TYPE_DIV     = 'M11'
         GROUP BY M1.OUTBOUND_DATE, M1.OUTBOUND_BATCH
          ORDER BY SUM_PER_DAY DESC
        )
  ORDER BY SUM_PER_DAY DESC, OUTBOUND_BATCH
;

--실전문제②
SELECT OUTBOUND_DATE
     , RANK()         OVER(PARTITION BY OUTBOUND_DATE ORDER BY ORDER_QTY DESC) AS "일자단위 수량 랭킹"
     , OUTBOUND_BATCH, ORDER_QTY
  FROM (
        SELECT M1.OUTBOUND_DATE, M1.OUTBOUND_BATCH, SUM(M2.ORDER_QTY) AS ORDER_QTY
          FROM LO_OUT_M M1
               JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
         WHERE M1.OUTBOUND_DATE BETWEEN '2019-09-03' AND '2019-09-10'
           AND M1.OUT_TYPE_DIV = 'M11'
         GROUP BY M1.OUTBOUND_DATE, M1.OUTBOUND_BATCH
        )
 ORDER BY OUTBOUND_DATE, OUTBOUND_BATCH
;

--실전문제①
SELECT OUTBOUND_DATE, OUTBOUND_BATCH, ORDER_QTY
     , ROW_NUMBER()   OVER(PARTITION BY OUTBOUND_DATE ORDER BY OUTBOUND_BATCH) AS "일자단위 차수 순서"
     , SUM(ORDER_QTY) OVER(PARTITION BY OUTBOUND_DATE ORDER BY OUTBOUND_BATCH) AS "일자단위 차수순 누계"
     , SUM(ORDER_QTY) OVER(PARTITION BY OUTBOUND_DATE)                         AS "일자별 합계"
     , SUM(ORDER_QTY) OVER(ORDER BY OUTBOUND_DATE)                             AS "일자순 누계"
     , SUM(ORDER_QTY) OVER()                                                   AS "전체 합계"
     , COUNT(1)       OVER(PARTITION BY OUTBOUND_DATE)                         AS "일자단위 레코드수"
     , COUNT(1)       OVER()                                                   AS "전체 레코드수"
  FROM (
        SELECT M1.OUTBOUND_DATE, M1.OUTBOUND_BATCH, SUM(M2.ORDER_QTY) AS ORDER_QTY
          FROM LO_OUT_M M1
               JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
         WHERE M1.OUTBOUND_DATE BETWEEN '2019-09-03' AND '2019-09-10'
           AND M1.OUT_TYPE_DIV = 'M11'
         GROUP BY M1.OUTBOUND_DATE, M1.OUTBOUND_BATCH
        )
 ORDER BY OUTBOUND_DATE, OUTBOUND_BATCH
;
