--실전문제②
SELECT INVOICE_NO, LINE_NO, ITEM_NM
  FROM LO_OUT_D
 WHERE INVOICE_NO = '346724704405'
 ORDER BY CASE WHEN :SORT_TYPE = 1 THEN ITEM_NM END
        , CASE WHEN :SORT_TYPE = 2 THEN ITEM_NM END DESC
;

--실전문제①
SELECT OUTBOUND_DATE, INVOICE_NO, WORK_SEQ
  FROM LO_OUT_M
 WHERE OUTBOUND_DATE BETWEEN TO_DATE('2019-06-03', 'YYYY-MM-DD') 
                         AND TO_DATE('2019-06-04', 'YYYY-MM-DD')
   AND SET_TYPE_CD   = '000581225'
   AND SET_QTY       = 3
 ORDER BY WORK_SEQ * CASE :SET_TYPE WHEN '1' THEN 1 ELSE -1 END
        , INVOICE_NO
;
