--실전문제④
WITH BASE AS (
SELECT M2.ITEM_CD, M2.ITEM_NM
     , SUM(M2.ORDER_QTY) AS ORDER_QTY
  FROM LO_OUT_M M1
       JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
 WHERE M1.OUTBOUND_DATE BETWEEN TO_DATE('2019-06-01', 'YYYY-MM-DD')
                            AND TO_DATE('2019-06-30', 'YYYY-MM-DD')
   AND M2.ITEM_NM LIKE '%참치%'
 GROUP BY M2.ITEM_CD, M2.ITEM_NM
 ),
BASE_01 AS (
SELECT ITEM_CD, ITEM_NM, ORDER_QTY
     , ROW_NUMBER() OVER(ORDER BY ORDER_QTY DESC) AS RNUM
  FROM BASE
 ORDER BY ORDER_QTY DESC
 )

SELECT RNUM, ITEM_CD, ITEM_NM, ORDER_QTY
  FROM BASE_01
 WHERE RNUM <= 5

UNION ALL

SELECT 0              AS RNUM
     , '99999'        AS ITEM_CD
     , 'TOP5제외 합계' AS ITEM_NM
     , SUM(ORDER_QTY) AS ORDER_QTY
  FROM BASE_01
 WHERE RNUM > 5
;

--실전문제③
SELECT SUM(CASE WHEN TO_CHAR(TO_DATE(M1.OUTBOUND_DATE, 'YYYY-MM-DD'), 'MM') = '01' THEN M2.ORDER_QTY END) AS M01
     , SUM(CASE WHEN TO_CHAR(TO_DATE(M1.OUTBOUND_DATE, 'YYYY-MM-DD'), 'MM') = '02' THEN M2.ORDER_QTY END) AS M02
     , SUM(CASE WHEN TO_CHAR(TO_DATE(M1.OUTBOUND_DATE, 'YYYY-MM-DD'), 'MM') = '03' THEN M2.ORDER_QTY END) AS M03
     , SUM(CASE WHEN TO_CHAR(TO_DATE(M1.OUTBOUND_DATE, 'YYYY-MM-DD'), 'Q')  = '1'  THEN M2.ORDER_QTY END) AS Q1
     , SUM(CASE WHEN TO_CHAR(TO_DATE(M1.OUTBOUND_DATE, 'YYYY-MM-DD'), 'MM') = '04' THEN M2.ORDER_QTY END) AS M04
     , SUM(CASE WHEN TO_CHAR(TO_DATE(M1.OUTBOUND_DATE, 'YYYY-MM-DD'), 'MM') = '05' THEN M2.ORDER_QTY END) AS M05
     , SUM(CASE WHEN TO_CHAR(TO_DATE(M1.OUTBOUND_DATE, 'YYYY-MM-DD'), 'MM') = '06' THEN M2.ORDER_QTY END) AS M06
     , SUM(CASE WHEN TO_CHAR(TO_DATE(M1.OUTBOUND_DATE, 'YYYY-MM-DD'), 'Q')  = '2'  THEN M2.ORDER_QTY END) AS Q2
     , SUM(CASE WHEN TO_CHAR(TO_DATE(M1.OUTBOUND_DATE, 'YYYY-MM-DD'), 'MM') = '07' THEN M2.ORDER_QTY END) AS M07
     , SUM(CASE WHEN TO_CHAR(TO_DATE(M1.OUTBOUND_DATE, 'YYYY-MM-DD'), 'MM') = '08' THEN M2.ORDER_QTY END) AS M08
     , SUM(CASE WHEN TO_CHAR(TO_DATE(M1.OUTBOUND_DATE, 'YYYY-MM-DD'), 'MM') = '09' THEN M2.ORDER_QTY END) AS M09
     , SUM(CASE WHEN TO_CHAR(TO_DATE(M1.OUTBOUND_DATE, 'YYYY-MM-DD'), 'Q')  = '3'  THEN M2.ORDER_QTY END) AS Q3
     , SUM(CASE WHEN TO_CHAR(TO_DATE(M1.OUTBOUND_DATE, 'YYYY-MM-DD'), 'MM') = '10' THEN M2.ORDER_QTY END) AS M10
     , SUM(CASE WHEN TO_CHAR(TO_DATE(M1.OUTBOUND_DATE, 'YYYY-MM-DD'), 'MM') = '11' THEN M2.ORDER_QTY END) AS M11
     , SUM(CASE WHEN TO_CHAR(TO_DATE(M1.OUTBOUND_DATE, 'YYYY-MM-DD'), 'MM') = '12' THEN M2.ORDER_QTY END) AS M12
     , SUM(CASE WHEN TO_CHAR(TO_DATE(M1.OUTBOUND_DATE, 'YYYY-MM-DD'), 'Q')  = '4'  THEN M2.ORDER_QTY END) AS Q4
  FROM LO_OUT_M M1
       JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
 WHERE OUTBOUND_DATE BETWEEN TO_DATE('2019'||'0101', 'YYYY-MM-DD')
                         AND TO_DATE('2019'||'1231', 'YYYY-MM-DD')
;

--실전문제②
SELECT SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'D') = '1' THEN ORDER_QTY END) AS SUN
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'D') = '2' THEN ORDER_QTY END) AS MON
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'D') = '3' THEN ORDER_QTY END) AS TUE
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'D') = '4' THEN ORDER_QTY END) AS WED
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'D') = '5' THEN ORDER_QTY END) AS THU
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'D') = '6' THEN ORDER_QTY END) AS FRI
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'D') = '7' THEN ORDER_QTY END) AS SAT
  FROM LO_OUT_M M1
       JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
 WHERE OUTBOUND_DATE BETWEEN TO_DATE('201901', 'YYYY-MM')
                         AND LAST_DAY(TO_DATE('201912', 'YYYY-MM'))
;

SELECT TO_CHAR(OUTBOUND_DATE, 'DAY') AS DAY
     , SUM(ORDER_QTY) AS ORDER_QTY
  FROM LO_OUT_M M1
       JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
 WHERE OUTBOUND_DATE BETWEEN TO_DATE('201909', 'YYYY-MM')
                         AND LAST_DAY(TO_DATE('201909', 'YYYY-MM'))
 GROUP BY TO_CHAR(OUTBOUND_DATE, 'DAY')
        , TO_CHAR(OUTBOUND_DATE, 'D')
 ORDER BY TO_CHAR(OUTBOUND_DATE, 'D')
;

--실전문제①
SELECT TO_CHAR(OUTBOUND_DATE, 'YYYY/MM/DD') AS OUTBOUND_DATE
     , SUM(ORDER_QTY) AS SUM_QTY
  FROM LO_OUT_M M1
       JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
 WHERE OUTBOUND_DATE BETWEEN TO_DATE('201909', 'YYYY-MM')
                         AND LAST_DAY(TO_DATE('201909', 'YYYY-MM'))
 GROUP BY OUTBOUND_DATE
 ORDER BY SUM_QTY DESC
;
