--실전문제⑥
SELECT INVOICE_NO, LINE_NO, ITEM_CD, ITEM_NM, ORDER_QTY
  FROM LO_OUT_D
 WHERE INVOICE_NO = '346724706214'
 ORDER BY CASE :SORT_TYPE WHEN '1' THEN LINE_NO
                          WHEN '2' THEN ORDER_QTY
          END, LINE_NO
;

--실전문제⑤
SELECT TO_CHAR(OUTBOUND_DATE, 'YYYY-MM') AS YYYY
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '01' THEN SET_QTY END) AS M01
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '02' THEN SET_QTY END) AS M02
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '03' THEN SET_QTY END) AS M03
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '04' THEN SET_QTY END) AS M04
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '05' THEN SET_QTY END) AS M05
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '06' THEN SET_QTY END) AS M06
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '07' THEN SET_QTY END) AS M07
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '08' THEN SET_QTY END) AS M08
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '09' THEN SET_QTY END) AS M09
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '10' THEN SET_QTY END) AS M10
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '11' THEN SET_QTY END) AS M11
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '12' THEN SET_QTY END) AS M12
 FROM LO_OUT_M
 WHERE TO_CHAR(OUTBOUND_DATE, 'YYYY') <> '2023'
 GROUP BY TO_CHAR(OUTBOUND_DATE, 'YYYY-MM')
 ORDER BY TO_CHAR(OUTBOUND_DATE, 'YYYY-MM')
;
----
SELECT TO_CHAR(OUTBOUND_DATE, 'YYYY') AS YYYY
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '01' THEN SET_QTY END) AS M01
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '02' THEN SET_QTY END) AS M02
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '03' THEN SET_QTY END) AS M03
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '04' THEN SET_QTY END) AS M04
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '05' THEN SET_QTY END) AS M05
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '06' THEN SET_QTY END) AS M06
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '07' THEN SET_QTY END) AS M07
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '08' THEN SET_QTY END) AS M08
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '09' THEN SET_QTY END) AS M09
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '10' THEN SET_QTY END) AS M10
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '11' THEN SET_QTY END) AS M11
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '12' THEN SET_QTY END) AS M12
 FROM LO_OUT_M
 WHERE TO_CHAR(OUTBOUND_DATE, 'YYYY') <> '2023'
 GROUP BY TO_CHAR(OUTBOUND_DATE, 'YYYY')
 ORDER BY TO_CHAR(OUTBOUND_DATE, 'YYYY')
;

--실전문제④
SELECT TO_CHAR(OUTBOUND_DATE, 'MM') AS MM
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '01' THEN SET_QTY END) AS M01
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '02' THEN SET_QTY END) AS M02
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '03' THEN SET_QTY END) AS M03
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '04' THEN SET_QTY END) AS M04
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '05' THEN SET_QTY END) AS M05
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '06' THEN SET_QTY END) AS M06
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '07' THEN SET_QTY END) AS M07
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '08' THEN SET_QTY END) AS M08
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '09' THEN SET_QTY END) AS M09
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '10' THEN SET_QTY END) AS M10
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '11' THEN SET_QTY END) AS M11
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '12' THEN SET_QTY END) AS M12
 FROM LO_OUT_M
 WHERE OUTBOUND_DATE BETWEEN :YEAR || '0101' AND :YEAR || '1231'
 GROUP BY TO_CHAR(OUTBOUND_DATE, 'MM')
 ORDER BY TO_CHAR(OUTBOUND_DATE, 'MM')
;
--
SELECT OUTBOUND_DATE
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '01' THEN SET_QTY END) AS M01
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '02' THEN SET_QTY END) AS M02
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '03' THEN SET_QTY END) AS M03
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '04' THEN SET_QTY END) AS M04
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '05' THEN SET_QTY END) AS M05
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '06' THEN SET_QTY END) AS M06
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '07' THEN SET_QTY END) AS M07
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '08' THEN SET_QTY END) AS M08
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '09' THEN SET_QTY END) AS M09
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '10' THEN SET_QTY END) AS M10
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '11' THEN SET_QTY END) AS M11
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '12' THEN SET_QTY END) AS M12
 FROM LO_OUT_M
 WHERE OUTBOUND_DATE BETWEEN :YEAR || '0101' AND :YEAR || '1231'
 GROUP BY OUTBOUND_DATE
 ORDER BY OUTBOUND_DATE
;

--실전문제③
SELECT SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '01' THEN SET_QTY END) AS M01
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '02' THEN SET_QTY END) AS M02
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '03' THEN SET_QTY END) AS M03
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '04' THEN SET_QTY END) AS M04
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '05' THEN SET_QTY END) AS M05
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '06' THEN SET_QTY END) AS M06
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '07' THEN SET_QTY END) AS M07
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '08' THEN SET_QTY END) AS M08
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '09' THEN SET_QTY END) AS M09
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '10' THEN SET_QTY END) AS M10
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '11' THEN SET_QTY END) AS M11
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '12' THEN SET_QTY END) AS M12
 FROM LO_OUT_M
 WHERE OUTBOUND_DATE BETWEEN :YEAR || '0101' AND :YEAR || '1231'
;

--실전문제②
SELECT ITEM_BAR_CD, COUNT(DISTINCT ITEM_CD) AS ITEM_CNT
  FROM LO_OUT_D
 GROUP BY ITEM_BAR_CD
HAVING COUNT(DISTINCT ITEM_CD) >= 2
 ORDER BY CASE WHEN ITEM_BAR_CD IS NULL THEN 2 ELSE 1 END
        , ITEM_CNT DESC
;

--실전문제①
SELECT OUTBOUND_DATE
      , COUNT(*) AS INV_CNT
      , COUNT(CASE WHEN OUT_TYPE_DIV LIKE 'M1%' THEN 1 END) M1_CNT
      , COUNT(CASE WHEN OUT_TYPE_DIV LIKE 'M2%' THEN 1 END) M2_CNT
  FROM LO_OUT_M
 WHERE OUTBOUND_DATE BETWEEN TO_DATE(SUBSTR(:OUTBOUND_DATE, 1, 7) || '01', 'YYYY-MM-DD')
                         AND TO_DATE(:OUTBOUND_DATE, 'YYYY-MM-DD')
   AND OUT_BOX_DIV LIKE 
    CASE :COND
      WHEN '1' THEN 'D'
      WHEN '2' THEN 'F'
      WHEN '0' THEN NULL
      ELSE 'zzz' END || '%'
 GROUP BY OUTBOUND_DATE
;

--초일 날짜 지정
--SELECT TRUNC(TO_DATE(:OUTBOUND_DATE, 'YYYY-MM-DD'), 'MM')
--     , LAST_DAY(ADD_MONTHS(TO_DATE(:OUTBOUND_DATE, 'YYYY-MM-DD'), -1)) + 1--말일 + 1
--  FROM DUAL;

--<3-1>
SELECT BRAND_CD, INVOICE_NO, LINE_NO, ITEM_CD, ORDER_QTY
     , CASE  
         WHEN ORDER_QTY >= 5 THEN '상'
         WHEN ORDER_QTY >= 3 THEN '중'
         WHEN ORDER_QTY >= 1 THEN '하'
        END AS GRADE
      --, CASE WHEN ITEM_CD = 'C' THEN 1 ELSE 2 END AS RNK
  FROM A_OUT_D
 WHERE BRAND_CD = '1001'
 ORDER BY CASE WHEN ITEM_CD = 'C' THEN 1 ELSE 2 END --RNK 
        , ITEM_CD
        , ORDER_QTY DESC
;
