--<5-2>
SELECT BRAND_CD AS 브랜드, INVOICE_NO AS 인보이스, ITEM_CD AS 상품코드, ORDER_QTY AS 주문수량
  FROM A_OUT_D
 WHERE INVOICE_NO LIKE '#0%' 
   AND ORDER_QTY >= 3
;

--<5-1>
SELECT BRAND_CD AS 브랜드, INVOICE_NO AS 인보이스, OUTBOUND_DATE AS 출고일자, ORDER_NM AS 주문자
  FROM A_OUT_M
 WHERE INVOICE_NO BETWEEN '#01' AND '#05'
   AND (ORDER_NM LIKE '전%' OR ORDER_NM LIKE '권%')
--   AND SUBSTR(ORDER_NM ,1 ,1) IN ('전', '권') --  좌항 함수 아용 지양
;

--<4-2>
SELECT BRAND_CD AS 브랜드, INVOICE_NO AS 인보이스, ITEM_CD AS 상품코드, ORDER_QTY AS 주문수량
  FROM A_OUT_D
 WHERE INVOICE_NO BETWEEN '#01' AND '#05'
   AND (
       ITEM_CD IN ('A', 'B') 
       OR (ITEM_CD = 'C' AND ORDER_QTY >= 3)
       )
;

--<4-1>
SELECT BRAND_CD AS 브랜드, INVOICE_NO AS 인보이스, OUTBOUND_DATE AS 출고일자, ORDER_NM AS 주문자
  FROM A_OUT_M
 WHERE OUTBOUND_DATE BETWEEN TO_DATE('2023-01-01', 'YYYY-MM-DD')
                         AND TO_DATE('2023-01-04', 'YYYY-MM-DD')
   AND ORDER_NM IN ('윤현수', '김민기')
;

--<3-2>
SELECT BRAND_CD AS 브랜드, INVOICE_NO AS 인보이스, ITEM_CD AS 상품코드, ORDER_QTY AS 주문수량
  FROM A_OUT_D
 WHERE BRAND_CD = '1001'
   AND (
       ITEM_CD IN ('A', 'B') 
       OR (ITEM_CD = 'C' AND ORDER_QTY >= 3)
       )
;

--<3-1>
SELECT BRAND_CD AS 브랜드,  INVOICE_NO AS 인보이스, ORDER_NM AS 주문자명
  FROM A_OUT_M
 WHERE OUTBOUND_DATE BETWEEN TO_DATE('2023-01-03', 'YYYY-MM-DD') AND
                             TO_DATE('2023-01-04', 'YYYY-MM-DD')
;

--<2-5>
SELECT *
  FROM A_ITEM
 WHERE BRAND_CD = '1001'
;

--<2-4>
SELECT *
  FROM A_OUT_D
 WHERE ITEM_CD = 'C'
   AND ORDER_QTY >= 3
;

--<2-3>
SELECT *
  FROM A_OUT_D
 WHERE ITEM_CD = 'A'
;

--<2-2>
SELECT *
  FROM A_OUT_M
 WHERE OUTBOUND_DATE = TO_DATE('2023-01-04', 'YYYY-MM-DD')
   AND ORDER_NM = '김민기'
;

--<2-1>
SELECT *
  FROM A_OUT_M
 WHERE OUTBOUND_DATE = TO_DATE('2023-01-03', 'YYYY-MM-DD')
;

--<1-3>
SELECT M1.BRAND_CD, M3.ITEM_NM, SUM(M1.ORDER_QTY) AS 총주문수량
  FROM A_OUT_D M1 JOIN A_OUT_M M2  ON M1.BRAND_CD = M2.BRAND_CD
                                   AND M1.INVOICE_NO = M2.INVOICE_NO
                  JOIN A_ITEM M3  ON M1.BRAND_CD = M3.BRAND_CD
                                  AND M1.ITEM_CD = M3.ITEM_CD
 WHERE M2.OUTBOUND_DATE = TO_DATE('2023-01-03', 'YYYY-MM-DD') 
 GROUP BY M1.BRAND_CD, M3.ITEM_NM
 ORDER BY M1.BRAND_CD, M3.ITEM_NM
;

--<1-2>
SELECT SUM(ORDER_QTY) AS 총주문수량
  FROM A_OUT_D
 WHERE BRAND_CD = 1001
   AND ITEM_CD = 'A'
 GROUP BY BRAND_CD
;

--<1-1>
SELECT BRAND_CD, COUNT(INVOICE_NO) AS 인보이스수
  FROM A_OUT_M
 GROUP BY BRAND_CD
;
