--실전문제 ②
SELECT NVL(TO_CHAR(SUM(ORDER_QTY)), 'Empty..') AS ORDER_QTY
  FROM LO_OUT_D
 WHERE INVOICE_NO = :INVOICE_NO--'346724706215'
;

--<2-3>
SELECT BRAND_CD AS 브랜드
        , CASE MOD(TO_NUMBER(SUBSTR(INVOICE_NO, 2)), 2) WHEN 0 THEN '짝수' ELSE '홀수' END AS 홀짝여부
        , SUM(ORDER_QTY) AS INV_SUM
  FROM A_OUT_D
 GROUP BY BRAND_CD
        , CASE MOD(TO_NUMBER(SUBSTR(INVOICE_NO, 2)), 2) WHEN 0 THEN '짝수' ELSE '홀수' END
;

--<2-2>
SELECT BRAND_CD AS 브랜드, TO_CHAR(OUTBOUND_DATE, 'DY') AS 요일, COUNT(1) AS INV_CNT
  FROM A_OUT_M
 GROUP BY BRAND_CD, TO_CHAR(OUTBOUND_DATE, 'DY') 
 ORDER BY BRAND_CD
;

--<2-1>
SELECT BRAND_CD AS 브랜드, COUNT(1) AS INV_CNT
  FROM A_OUT_M
 GROUP BY BRAND_CD
;

--<1-2>
SELECT OUTBOUND_DATE, TO_CHAR(OUTBOUND_DATE, 'DAY') AS DY, INVOICE_NO
      ,CASE MOD(TO_NUMBER(SUBSTR(INVOICE_NO, 2)), 2) WHEN 0 THEN '짝수' ELSE '홀수' END AS EVENODD
      ,ORDER_NM
  FROM A_OUT_M
 WHERE BRAND_CD = '1001'
;

--<1-1>
SELECT OUTBOUND_DATE, TO_CHAR(OUTBOUND_DATE, 'DAY') AS DY, INVOICE_NO, ORDER_NM
  FROM A_OUT_M
 WHERE BRAND_CD = '1001'
;

--NULL과 공집합
--NULL: 집합 자체는 존재하나 어떤 컬럼 값이 NULL
SELECT NULL AS FROM DUAL WHERE 1 = 1;
--공집합: 집합 자체가 존재하지 않음
SELECT NVL(NULL, 1) AS FROM DUAL WHERE 1 = 2;--공집합인데 NULL처리 해봤자 값 출력X
--GROUP BY 없이 집계함수만 사용→값(NULL) 하나 무조건 출력
SELECT NVL(MAX(NULL), 'HELLO') AS VAL
  FROM DUAL
 WHERE 1 = 2;

--NULL 관련 함수 예제
--SALARY 연산X
SELECT PAY, BONUS, (PAY * 12 + BONUS) AS SALARY
  FROM (
        SELECT 1000 AS PAY, 100   AS BONUS  FROM DUAL
        UNION ALL
        SELECT 1000 AS PAY, 0     AS BONUS  FROM DUAL
        UNION ALL
        SELECT 1000 AS PAY, NULL  AS BONUS  FROM DUAL
        )
;

--SALARY 연산可
SELECT PAY, BONUS, (PAY * 12 + NVL(BONUS, 0)) AS SALARY
  FROM (
        SELECT 1000 AS PAY, 100   AS BONUS  FROM DUAL
        UNION ALL
        SELECT 1000 AS PAY, 0     AS BONUS  FROM DUAL
        UNION ALL
        SELECT 1000 AS PAY, NULL  AS BONUS  FROM DUAL
        )
;
