--실전문제①
SELECT INVOICE_NO, LINE_NO, ITEM_NM, ORDER_QTY
     , MIN(ORDER_QTY) OVER(PARTITION BY INVOICE_NO) AS MIN_1
     , MIN(ORDER_QTY) OVER()                        AS MIN_2
     , MAX(ORDER_QTY) OVER(PARTITION BY INVOICE_NO) AS MAX_1
     , MAX(ORDER_QTY) OVER()                        AS MAX_2
  FROM LO_OUT_D
 WHERE INVOICE_NO IN ('346724703845', '346724706214', '346724706225')
;

--<2-1>
SELECT INVOICE_NO, LINE_NO, ITEM_NM, ORDER_QTY
     , SUM(ORDER_QTY) OVER() AS TOT_SUM
     , SUM(ORDER_QTY) OVER(PARTITION BY INVOICE_NO) AS PART_SUM
     , SUM(ORDER_QTY) OVER(PARTITION BY INVOICE_NO ORDER BY LINE_NO) AS ACC_PART_SUM
     , SUM(ORDER_QTY) OVER(ORDER BY INVOICE_NO, LINE_NO) AS ACC_SUM
     , COUNT(*)       OVER() AS TOT_CNT
     , COUNT(*)       OVER(PARTITION BY INVOICE_NO) AS PART_CNT
     , COUNT(DISTINCT INVOICE_NO) OVER() AS UNQ_CNT
     , LAG(ITEM_NM)   OVER(ORDER BY INVOICE_NO, LINE_NO) AS TOT_LAG
     , LEAD(ITEM_NM)  OVER(ORDER BY INVOICE_NO, LINE_NO) AS TOT_LAG
  FROM LO_OUT_D
 WHERE INVOICE_NO IN ('346724705050', '346724705061')
;

--<1-1>
SELECT INVOICE_NO, LINE_NO, ITEM_NM, ORDER_QTY
     , ROW_NUMBER() OVER(PARTITION BY INVOICE_NO ORDER BY ORDER_QTY DESC) AS RANK
  FROM LO_OUT_D
 WHERE INVOICE_NO IN ('346724705050', '346724705061')
;
