--실전문제③
SELECT LAG(NULL, 1, OUTBOUND_DATE) OVER(PARTITION BY OUTBOUND_DATE ORDER BY RNK) AS OUT_DATE
     , RNK, ITEM_NM, ORDER_QTY
     , RATE
     , SUM(RATE) OVER(PARTITION BY OUTBOUND_DATE ORDER BY RNK) AS ACC_RATE
  FROM (
        SELECT M1.OUTBOUND_DATE
             , ROW_NUMBER() OVER(PARTITION BY OUTBOUND_DATE ORDER BY SUM(ORDER_QTY) DESC) AS RNK
             , M2.ITEM_NM
             , SUM(M2.ORDER_QTY) AS ORDER_QTY
             , ROUND(RATIO_TO_REPORT(SUM(ORDER_QTY)) OVER(PARTITION BY M1.OUTBOUND_DATE) * 100, 2) AS RATE
          FROM LO_OUT_M M1
               JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
         WHERE M1.OUTBOUND_DATE BETWEEN '2019-09-03' AND '2019-09-05'
         GROUP BY M1.OUTBOUND_DATE, M2.ITEM_NM
        )
 WHERE RNK <= 3
;

--실전문제①
SELECT LAG(NULL, 1, OUTBOUND_DATE) OVER(PARTITION BY OUTBOUND_DATE ORDER BY RNK) AS OUT_DATE
     , RNK, ITEM_NM, ORDER_QTY
  FROM (
        SELECT M1.OUTBOUND_DATE
             , ROW_NUMBER() OVER(PARTITION BY OUTBOUND_DATE ORDER BY SUM(ORDER_QTY) DESC) AS RNK
             , M2.ITEM_NM
             , SUM(M2.ORDER_QTY) AS ORDER_QTY
          FROM LO_OUT_M M1
               JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
         WHERE M1.OUTBOUND_DATE BETWEEN '2019-09-03' AND '2019-09-05'
         GROUP BY M1.OUTBOUND_DATE, M2.ITEM_NM
        )
 WHERE RNK <= 3
;
