--조인활용2
--실전문제①
SELECT M1.INVOICE_NO, M1.LINE_NO, M1.ITEM_CD, M1.ITEM_NM, M1.ORDER_QTY
     , SUM(M2.ORDER_QTY) AS ACC_ORDER_QTY
  FROM LO_OUT_D M1 JOIN LO_OUT_D M2 ON  M2.INVOICE_NO =  M1.INVOICE_NO
                                    AND M2.LINE_NO    <= M1.LINE_NO
 WHERE M1.INVOICE_NO IN ('346724703845', '346724706214')
 GROUP BY M1.INVOICE_NO, M1.LINE_NO, M1.ITEM_CD, M1.ITEM_NM, M1.ORDER_QTY
 ORDER BY INVOICE_NO, LINE_NO
;

--실전문제②
SELECT M1.INVOICE_NO, M1.LINE_NO, M1.ITEM_CD, M1.ITEM_NM, M1.ORDER_QTY
     , SUM(M2.ORDER_QTY) AS ACC_ORDER_QTY
  FROM LO_OUT_D M1 JOIN LO_OUT_D M2 ON  M2.INVOICE_NO IN ('346724703845', '346724706214')
                                    AND M2.INVOICE_NO || LPAD(M2.LINE_NO, 3, '0') <= M1.INVOICE_NO || LPAD(M1.LINE_NO, 3, '0')
 WHERE M1.INVOICE_NO IN ('346724703845', '346724706214')
 GROUP BY M1.INVOICE_NO, M1.LINE_NO, M1.ITEM_CD, M1.ITEM_NM, M1.ORDER_QTY
 ORDER BY INVOICE_NO, LINE_NO
;

--분석함수1
--실전문제①
SELECT INVOICE_NO, LINE_NO, ITEM_NM, ORDER_QTY
     , MIN(ORDER_QTY) OVER(PARTITION BY INVOICE_NO) AS MIN_1
     , MIN(ORDER_QTY) OVER()                        AS MIN_2
     , MAX(ORDER_QTY) OVER(PARTITION BY INVOICE_NO) AS MAX_1
     , MAX(ORDER_QTY) OVER()                        AS MAX_2
  FROM LO_OUT_D
 WHERE INVOICE_NO IN ('346724703845','346724706214','346724706225')
;

--분석함수2
--실전문제①
SELECT OUTBOUND_DATE, OUTBOUND_BATCH, ORDER_QTY
     , RANK() OVER(PARTITION BY OUTBOUND_DATE ORDER BY ORDER_QTY DESC)         AS RNK_PER_DAY
     , SUM(ORDER_QTY) OVER(PARTITION BY OUTBOUND_DATE ORDER BY ORDER_QTY DESC) AS ACC_SUM_PER_DAY
     , SUM(ORDER_QTY) OVER(PARTITION BY OUTBOUND_DATE)                         AS SUM_PER_DAY
     , SUM(ORDER_QTY) OVER(ORDER BY OUTBOUND_DATE)                             AS ACC_SUM_PER_DAY
     , SUM(ORDER_QTY) OVER()                                                   AS TOT_SUM
     , COUNT(1)       OVER(PARTITION BY OUTBOUND_DATE)                         AS CNT_PER_DAY
     , COUNT(1)       OVER()                                                   AS TOT_CNT
  FROM (SELECT M1.OUTBOUND_DATE, M1.OUTBOUND_BATCH, SUM(M2.ORDER_QTY) AS ORDER_QTY
          FROM LO_OUT_M M1 JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
         WHERE M1.OUTBOUND_DATE BETWEEN '2019-09-03' AND '2019-09-10'
           AND M1.OUT_TYPE_DIV  = 'M11'
         GROUP BY M1.OUTBOUND_DATE, M1.OUTBOUND_BATCH
        )
 ORDER BY OUTBOUND_DATE, OUTBOUND_BATCH
;

--실전문제②
SELECT OUTBOUND_DATE
     , RANK() OVER(PARTITION BY OUTBOUND_DATE ORDER BY ORDER_QTY DESC) AS RNK_PER_DAY
     , OUTBOUND_BATCH, ORDER_QTY
  FROM (SELECT M1.OUTBOUND_DATE, M1.OUTBOUND_BATCH, SUM(M2.ORDER_QTY) AS ORDER_QTY
          FROM LO_OUT_M M1 JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
         WHERE M1.OUTBOUND_DATE BETWEEN '2019-09-03' AND '2019-09-10'
           AND M1.OUT_TYPE_DIV  = 'M11'
         GROUP BY M1.OUTBOUND_DATE, M1.OUTBOUND_BATCH
         ORDER BY OUTBOUND_DATE
        )
;

--실전문제③
SELECT CASE WHEN LAG(OUTBOUND_DATE) OVER(PARTITION BY OUTBOUND_DATE ORDER BY OUTBOUND_DATE) IS NULL THEN TO_CHAR(OUTBOUND_DATE, 'YY/MM/DD') END AS OUT_DATE
     , OUTBOUND_BATCH
     , ORDER_QTY
     , SUM(ORDER_QTY) OVER(PARTITION BY OUTBOUND_DATE)                                                                                          AS SUM_PER_DAY
     , RANK() OVER(PARTITION BY OUTBOUND_DATE ORDER BY ORDER_QTY DESC)                                                                          AS RNK_PER_DAY
     , RANK() OVER(ORDER BY ORDER_QTY DESC)                                                                                                     AS RNK_TOT
  FROM (SELECT M1.OUTBOUND_DATE, M1.OUTBOUND_BATCH, SUM(M2.ORDER_QTY) AS ORDER_QTY
          FROM LO_OUT_M M1 JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
         WHERE M1.OUTBOUND_DATE BETWEEN '2019-09-03' AND '2019-09-10'
           AND OUT_TYPE_DIV = 'M11'
         GROUP BY M1.OUTBOUND_DATE, M1.OUTBOUND_BATCH
        )
  ORDER BY SUM_PER_DAY DESC, OUTBOUND_BATCH
;

--실전문제④
SELECT CASE WHEN ROWNUM <= 5 THEN TO_CHAR(OUTBOUND_DATE) ELSE '기타' END AS OUTBOUND_DATE
     , SUM(ORDER_QTY) AS ORDER_QTY
     , SUM(RATE)      AS RATE
     , MIN(RNK)       AS RNK
  FROM (SELECT M1.OUTBOUND_DATE, SUM(M2.ORDER_QTY) AS ORDER_QTY
             , ROUND(RATIO_TO_REPORT(SUM(M2.ORDER_QTY)) OVER() * 100, 3) AS RATE
             , ROW_NUMBER() OVER(ORDER BY SUM(M2.ORDER_QTY) DESC) AS RNK
          FROM LO_OUT_M M1 JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
         WHERE M1.OUTBOUND_DATE BETWEEN '2019-09-01' AND '2019-09-15'
         GROUP BY M1.OUTBOUND_DATE
         ORDER BY ORDER_QTY DESC)
 GROUP BY CASE WHEN ROWNUM <= 5 THEN TO_CHAR(OUTBOUND_DATE) ELSE '기타' END
;

     
--분석함수3
--실전문제①
SELECT LAG(NULL, 1, OUTBOUND_DATE) OVER(PARTITION BY OUTBOUND_DATE ORDER BY RNK) AS OUTBOUND_DATE
     , RNK, ITEM_NM, ORDER_QTY
  FROM (SELECT M1.OUTBOUND_DATE, M2.ITEM_NM, SUM(M2.ORDER_QTY) AS ORDER_QTY
             , ROW_NUMBER() OVER(PARTITION BY M1.OUTBOUND_DATE ORDER BY SUM(ORDER_QTY) DESC) AS RNK
          FROM LO_OUT_M M1 JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
         WHERE M1.OUTBOUND_DATE BETWEEN '2019-09-03' AND '2019-09-05'
         GROUP BY M1.OUTBOUND_DATE, M2.ITEM_NM)
 WHERE RNK <= 3
;

--실전문제②
SELECT OUTBOUND_DATE, RNK, ITEM_NM, ORDER_QTY, RATE
     , SUM(RATE) OVER(PARTITION BY OUTBOUND_DATE ORDER BY ORDER_QTY) AS ACC_RATE
  FROM (SELECT M1.OUTBOUND_DATE, M2.ITEM_NM, SUM(M2.ORDER_QTY) AS ORDER_QTY
             , ROUND(RATIO_TO_REPORT(SUM(M2.ORDER_QTY)) OVER(PARTITION BY M1.OUTBOUND_DATE) * 100, 2)  AS RATE
             , ROW_NUMBER() OVER(PARTITION BY M1.OUTBOUND_DATE ORDER BY SUM(M2.ORDER_QTY) DESC) AS RNK
          FROM LO_OUT_M M1 JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
         WHERE M1.OUTBOUND_DATE BETWEEN '2019-09-03' AND '2019-09-05'
         GROUP BY M1.OUTBOUND_DATE, M2.ITEM_NM
        )
 WHERE RNK <= 3
;