--서브쿼리, 스칼라쿼리
--1 - (1)
SELECT M2.*
  FROM A_OUT_M M1
       JOIN A_OUT_D M2 ON   M2.BRAND_CD   = M1.BRAND_CD
                       AND  M2.INVOICE_NO = M1.INVOICE_NO
 WHERE M1.OUTBOUND_DATE = TO_DATE('2023-01-03', 'YYYY-MM-DD')
;

--1 - (2)
SELECT M2.*
  FROM A_OUT_M M1
       JOIN A_OUT_D M2 ON  M2.BRAND_CD   = M1.BRAND_CD
                       AND M2.INVOICE_NO = M1.INVOICE_NO
 WHERE M1.BRAND_CD     =    '1001'
   AND M1.OUT_TYPE_DIV LIKE 'M1%'
;

--1 - (3)
SELECT *
  FROM (
        SELECT M1.BRAND_CD, M1.INVOICE_NO
             , SUM(ORDER_QTY) AS SUM_QTY
          FROM A_OUT_D M1
         GROUP BY M1.BRAND_CD, M1.INVOICE_NO
        )
 WHERE SUM_QTY >= 3
;

--2 - (1)
SELECT M3.*
      , (SELECT M2.ITEM_NM
          FROM A_ITEM M2
         WHERE M2.BRAND_CD = M3.BRAND_CD
           AND M2.ITEM_CD  = M3.ITEM_CD) AS ITEM_NM
  FROM (SELECT M1.BRAND_CD
             , M1.ITEM_CD
             , SUM(ORDER_QTY) AS SUM_QTY
          FROM A_OUT_D M1
         GROUP BY M1.BRAND_CD, M1.ITEM_CD
        ) M3
;

--실전문제①
SELECT DISTINCT M2.OUTBOUND_DATE
  FROM (SELECT TO_DATE(:OUTBOUND_DATE, 'YYYY-MM-DD') + LEVEL AS OUTBOUND_DATE
          FROM DUAL
         CONNECT BY LEVEL <= 10
        ) M1 JOIN LO_OUT_M M2 ON M2.OUTBOUND_DATE = M1.OUTBOUND_DATE
 ORDER BY M2.OUTBOUND_DATE
;

--실전문제②
SELECT INVOICE_NO, OUT_TYPE_DIV, OUT_BOX_DIV
     , TO_NUMBER(SUBSTR(MAX_VAL, 1, 4)) AS MAX_ORDER_QTY
     , TO_NUMBER(SUBSTR(MAX_VAL, 6, 3)) AS MAX_LINE_NO
  FROM (SELECT M1.INVOICE_NO
             , M1.OUT_TYPE_DIV
             , M1.OUT_BOX_DIV
             , (SELECT MAX(LPAD(M2.ORDER_QTY, 4, '0') || '-' || LPAD(M2.LINE_NO, 3, '0'))
                  FROM LO_OUT_D M2
                 WHERE M2.INVOICE_NO = M1.INVOICE_NO) AS MAX_VAL
         FROM LO_OUT_M M1
        WHERE M1.OUTBOUND_DATE =       TO_DATE('2019-06-03', 'YYYY-MM-DD')
          AND M1.OUTBOUND_NO   BETWEEN 'D190603-897353'
                               AND     'D190603-897360'
        )
;

--뷰, 인라인뷰
--1 - (1)
SELECT M1.BRAND_CD, M1.ITEM_CD, M1.SUM_QTY
     , (SELECT M2.ITEM_NM
          FROM A_ITEM M2
         WHERE M2.BRAND_CD = M1.BRAND_CD
           AND M2.ITEM_CD  = M1.ITEM_CD
        ) AS ITEM_NM
     , (SELECT M2.QTY_IN_BOX
          FROM A_ITEM M2
         WHERE M2.BRAND_CD = M1.BRAND_CD
           AND M2.ITEM_CD  = M1.ITEM_CD
        ) AS QTY_IN_BOX
  FROM (SELECT BRAND_CD, ITEM_CD
             , SUM(ORDER_QTY) AS SUM_QTY
          FROM A_OUT_D
         GROUP BY BRAND_CD, ITEM_CD
        ) M1
;

--1 - (2)
SELECT BRAND_CD, ITEM_CD, SUM_QTY, ITEM_NM
     , TRUNC(SUM_QTY/QTY_IN_BOX) AS VAL_BOX
     , MOD(SUM_QTY, QTY_IN_BOX)  AS PEACES
  FROM (SELECT M1.BRAND_CD, M1.ITEM_CD, M1.SUM_QTY
             , (SELECT M2.ITEM_NM
                  FROM A_ITEM M2
                 WHERE M2.BRAND_CD = M1.BRAND_CD
                   AND M2.ITEM_CD  = M1.ITEM_CD
                ) AS ITEM_NM
             , (SELECT M2.QTY_IN_BOX
                  FROM A_ITEM M2
                 WHERE M2.BRAND_CD = M1.BRAND_CD
                   AND M2.ITEM_CD  = M1.ITEM_CD
                ) AS QTY_IN_BOX
          FROM (SELECT BRAND_CD, ITEM_CD
                     , SUM(ORDER_QTY) AS SUM_QTY
                  FROM A_OUT_D
                 GROUP BY BRAND_CD, ITEM_CD
                ) M1
        )
;
--1 - (3)
SELECT *
  FROM (SELECT BRAND_CD, ITEM_CD, SUM_QTY, ITEM_NM
             , TRUNC(SUM_QTY/QTY_IN_BOX) AS VAL_BOX
             , MOD(SUM_QTY, QTY_IN_BOX)  AS PEACES
          FROM (SELECT M1.BRAND_CD, M1.ITEM_CD, M1.SUM_QTY
                     , (SELECT M2.ITEM_NM
                          FROM A_ITEM M2
                         WHERE M2.BRAND_CD = M1.BRAND_CD
                           AND M2.ITEM_CD  = M1.ITEM_CD
                        ) AS ITEM_NM
                     , (SELECT M2.QTY_IN_BOX
                          FROM A_ITEM M2
                         WHERE M2.BRAND_CD = M1.BRAND_CD
                           AND M2.ITEM_CD  = M1.ITEM_CD
                        ) AS QTY_IN_BOX
                  FROM (SELECT BRAND_CD, ITEM_CD
                             , SUM(ORDER_QTY) AS SUM_QTY
                          FROM A_OUT_D
                         GROUP BY BRAND_CD, ITEM_CD
                        ) M1
                )
        )
 WHERE ROWNUM < 4
;

--실전문제①
SELECT ITEM_CD
      , (SELECT M2.ITEM_NM
          FROM CM_ITEM M2
         WHERE M2.ITEM_CD = M1.ITEM_CD)
      , ORDER_QTY
  FROM (SELECT ITEM_CD, SUM(ORDER_QTY) AS ORDER_QTY
          FROM LO_OUT_D
         WHERE INVOICE_NO BETWEEN '346724706262'
                              AND '346724706762'
         GROUP BY ITEM_CD
        ) M1
;

--실전문제②
SELECT ROWNUM AS RNK, ITEM_CD, QTY_IN_BOX, ORDER_QTY
     , TRUNC(ORDER_QTY/QTY_IN_BOX) AS BOX_CNT
     , MOD(ORDER_QTY, QTY_IN_BOX)  AS PCS_CNT
     , CEIL(ORDER_QTY/QTY_IN_BOX)  AS BOX_CNT_TOT
  FROM (SELECT ITEM_CD, QTY_IN_BOX, SUM(ORDER_QTY) AS ORDER_QTY
          FROM LO_OUT_D
         WHERE INVOICE_NO BETWEEN '346724706262'
                              AND '346724706762'
          GROUP BY ITEM_CD, QTY_IN_BOX
          ORDER BY ORDER_QTY DESC
        )
 WHERE ROWNUM < 6
;

--내장함수일반
--1 - (1)
SELECT OUTBOUND_DATE
     , TO_CHAR(OUTBOUND_DATE, 'DAY') AS DY
     , INVOICE_NO, ORDER_NM
  FROM A_OUT_M
 WHERE BRAND_CD = 1001
;
    
--1 - (2)
SELECT OUTBOUND_DATE
     , TO_CHAR(OUTBOUND_DATE, 'DAY') AS DY
     , INVOICE_NO
     , CASE MOD(TO_NUMBER(SUBSTR(INVOICE_NO, 2)), 2) WHEN 0 THEN '짝수' ELSE '홀수' END AS EVENODD
     , ORDER_NM
  FROM A_OUT_M
 WHERE BRAND_CD = 1001
;

--2 - (1)
SELECT BRAND_CD, COUNT(1) AS CNT
  FROM A_OUT_M
 GROUP BY BRAND_CD
;

--2 - (2)
SELECT BRAND_CD
     , TO_CHAR(OUTBOUND_DATE, 'DAY') AS DY
     , COUNT(1) AS CNT
  FROM A_OUT_M
  GROUP BY BRAND_CD, TO_CHAR(OUTBOUND_DATE, 'DAY'), TO_CHAR(OUTBOUND_DATE, 'D')
  ORDER BY BRAND_CD, TO_CHAR(OUTBOUND_DATE, 'D')
;

--2 - (3)
SELECT BRAND_CD
     , CASE MOD(TO_NUMBER(SUBSTR(INVOICE_NO, 2)), 2) WHEN 0 THEN '짝수' ELSE '홀수' END AS EVENODD
     , COUNT(1) AS CNT
  FROM A_OUT_M
  GROUP BY BRAND_CD
         , CASE MOD(TO_NUMBER(SUBSTR(INVOICE_NO, 2)), 2) WHEN 0 THEN '짝수' ELSE '홀수' END
;

--실전문제①
SELECT INVOICE_NO, OUTBOUND_DATE
     , TO_CHAR(OUTBOUND_DATE, 'DAY') AS DAYY
     , OUTBOUND_NO
  FROM LO_OUT_M
 WHERE INVOICE_NO IN ('346724706214', '346724793596', '346724869970')
;

--실전문제②
SELECT NVL(TO_CHAR(SUM(ORDER_QTY)), 'EMPTY..') AS ORDER_QTY
  FROM LO_OUT_D
 WHERE INVOICE_NO = '346724706215'
;

--내장함수CASE
--1 - (1) 
SELECT OUTBOUND_DATE
     , TO_CHAR(OUTBOUND_DATE, 'DAY') AS DY
     , INVOICE_NO
     , CASE MOD(TO_NUMBER(SUBSTR(INVOICE_NO, 2)), 2) WHEN 0 THEN '짝수' ELSE '홀수' END AS EVENODD
     , ORDER_NM
     , CASE WHEN OUT_TYPE_DIV LIKE 'M1%' THEN '상온' ELSE '저온' END AS TEMP
  FROM A_OUT_M
;
--1 - (2)
SELECT BRAND_CD, INVOICE_NO, LINE_NO, ITEM_CD, ORDER_QTY
     , CASE WHEN ORDER_QTY < 3 THEN '하'
            WHEN ORDER_QTY < 5 THEN '중'
            ELSE                    '상' END AS GRADE
  FROM A_OUT_D
;
--2 - (1)
SELECT BRAND_CD
     , CASE SUBSTR(OUT_TYPE_DIV, 1, 2) WHEN 'M1' THEN '상온'
                                       ELSE           '저온' END AS TEMP
     , COUNT(1) AS CNT
  FROM A_OUT_M
 GROUP BY BRAND_CD
     , CASE SUBSTR(OUT_TYPE_DIV, 1, 2) WHEN 'M1' THEN '상온'
                                       ELSE           '저온' END
;
--2 - (2)
SELECT BRAND_CD
     , CASE WHEN ORDER_QTY < 3 THEN '하'
            WHEN ORDER_QTY < 5 THEN '중'
            ELSE                    '상' END AS GRADE
     , COUNT(1) AS CNT
  FROM A_OUT_D
  GROUP BY  BRAND_CD
     , CASE WHEN ORDER_QTY < 3 THEN '하'
            WHEN ORDER_QTY < 5 THEN '중'
            ELSE                    '상' END
  ORDER BY BRAND_CD
;

--2 - (3)
SELECT CASE WHEN ROWNUM < 3 THEN ITEM_CD
       ELSE                 'etc'  END AS ITEM_CD
     , SUM(ORDER_QTY) AS ORDER_QTY
  FROM (SELECT ITEM_CD
              , SUM(ORDER_QTY) AS ORDER_QTY
          FROM A_OUT_D
          GROUP BY ITEM_CD
          ORDER BY ORDER_QTY DESC
        )
  GROUP BY CASE WHEN ROWNUM < 3 THEN ROWNUM ELSE 999 END
         , CASE WHEN ROWNUM < 3 THEN ITEM_CD
                ELSE                 'etc'  END
  ORDER BY CASE WHEN ROWNUM < 3 THEN ROWNUM ELSE 999 END
;

--3 - (1)
SELECT BRAND_CD, INVOICE_NO, LINE_NO, ITEM_CD, ORDER_QTY
     , CASE WHEN ORDER_QTY < 3 THEN '하'
            WHEN ORDER_QTY < 5 THEN '중'
            ELSE                    '상' END AS GRADE
  FROM A_OUT_D
 WHERE BRAND_CD = '1001'
 ORDER BY CASE WHEN ITEM_CD = 'C' THEN 0 ELSE ROWNUM END
        , ITEM_CD, ORDER_QTY DESC
;

--실전문제①
SELECT OUTBOUND_DATE
     , COUNT(1) AS INVOICE_CNT
     , COUNT(CASE WHEN OUT_TYPE_DIV LIKE 'M1%' THEN 1 END) AS M1_CNT
     , COUNT(CASE WHEN OUT_TYPE_DIV LIKE 'M2%' THEN 1 END) AS M2_CNT
  FROM LO_OUT_M
 WHERE OUTBOUND_DATE BETWEEN TO_DATE(SUBSTR(:OUTBOUND_DATE, 1, 7)|| '01', 'YYYY-MM-DD')
                         AND TO_DATE(:OUTBOUND_DATE, 'YYYY-MM-DD')
   AND OUT_BOX_DIV LIKE CASE :COND WHEN '1' THEN 'D%'
                                   WHEN '2' THEN 'F%'
                                   WHEN '0' THEN NULL
                                   ELSE          'ASDB' END                     
  GROUP BY OUTBOUND_DATE
;

--실전문제②
SELECT ITEM_BAR_CD
     , COUNT(DISTINCT ITEM_CD) AS ITEM_CNT
  FROM LO_OUT_D
  GROUP BY ITEM_BAR_CD
  HAVING COUNT(DISTINCT ITEM_CD) >= 2
  ORDER BY CASE WHEN ITEM_BAR_CD IS NULL THEN 2 ELSE 1 END
         , ITEM_CNT DESC
;

--실전문제③
SELECT SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '01' THEN SET_QTY END) AS M01
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '02' THEN SET_QTY END) AS M02
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '03' THEN SET_QTY END) AS M03
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '04' THEN SET_QTY END) AS M04
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '05' THEN SET_QTY END) AS M05
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '06' THEN SET_QTY END) AS M06
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '07' THEN SET_QTY END) AS M07
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '08' THEN SET_QTY END) AS M08
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '09' THEN SET_QTY END) AS M09
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '10' THEN SET_QTY END) AS M10
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '11' THEN SET_QTY END) AS M11
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '12' THEN SET_QTY END) AS M12
  FROM LO_OUT_M
 WHERE OUTBOUND_DATE BETWEEN :YEAR || '0101' AND :YEAR || '1231'
; 

--실전문제④
SELECT OUTBOUND_DATE
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '01' THEN SET_QTY END) AS M01
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '02' THEN SET_QTY END) AS M02
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '03' THEN SET_QTY END) AS M03
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '04' THEN SET_QTY END) AS M04
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '05' THEN SET_QTY END) AS M05
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '06' THEN SET_QTY END) AS M06
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '07' THEN SET_QTY END) AS M07
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '08' THEN SET_QTY END) AS M08
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '09' THEN SET_QTY END) AS M09
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '10' THEN SET_QTY END) AS M10
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '11' THEN SET_QTY END) AS M11
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '12' THEN SET_QTY END) AS M12
  FROM LO_OUT_M
 WHERE OUTBOUND_DATE BETWEEN :YEAR || '0101' AND :YEAR || '1231'
  GROUP BY OUTBOUND_DATE
  ORDER BY OUTBOUND_DATE
; 

--실전문제⑤
SELECT CASE WHEN TO_CHAR(OUTBOUND_DATE, 'YYYY') = '2018' THEN '2018'
            WHEN TO_CHAR(OUTBOUND_DATE, 'YYYY') = '2019' THEN '2019' END AS YYYY
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '01' THEN SET_QTY END) AS M01
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '02' THEN SET_QTY END) AS M02
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '03' THEN SET_QTY END) AS M03
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '04' THEN SET_QTY END) AS M04
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '05' THEN SET_QTY END) AS M05
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '06' THEN SET_QTY END) AS M06
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '07' THEN SET_QTY END) AS M07
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '08' THEN SET_QTY END) AS M08
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '09' THEN SET_QTY END) AS M09
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '10' THEN SET_QTY END) AS M10
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '11' THEN SET_QTY END) AS M11
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '12' THEN SET_QTY END) AS M12
  FROM LO_OUT_M
 WHERE TO_CHAR(OUTBOUND_DATE, 'YYYY') <> '2023'
  GROUP BY CASE WHEN TO_CHAR(OUTBOUND_DATE, 'YYYY') = '2018' THEN '2018'
                WHEN TO_CHAR(OUTBOUND_DATE, 'YYYY') = '2019' THEN '2019' END
; 

--실전문제⑥
SELECT INVOICE_NO, LINE_NO, ITEM_CD, ITEM_NM
     , SUM(ORDER_QTY) AS ORDER_QTY
  FROM LO_OUT_D
 WHERE INVOICE_NO = '346724706214'
 GROUP BY INVOICE_NO, LINE_NO, ITEM_CD, ITEM_NM
 ORDER BY CASE :SORT_TYPE WHEN '1' THEN LINE_NO
                          WHEN '2' THEN ORDER_QTY END DESC, LINE_NO
;
