--실전문제①
SELECT OUTBOUND_DATE
  FROM (
        SELECT TO_DATE(:OUTBOUND_DATE, 'YYYY-MM-DD') + LEVEL AS OUTBOUND_DATE
          FROM DUAL
         CONNECT BY LEVEL <= 10
        ) M1
 WHERE EXISTS (SELECT 1
                 FROM LO_OUT_M M2
                WHERE M2.OUTBOUND_DATE = M1.OUTBOUND_DATE
              )
;

--실전문제②
SELECT INVOICE_NO, OUT_TYPE_DIV, OUT_BOX_DIV
     , TO_NUMBER(SUBSTR(MAX_VAL, 1, 5)) AS MAX_ORDER_QTY
     , TO_NUMBER(SUBSTR(MAX_VAL, 7, 3)) AS MAX_LINE
  FROM (SELECT INVOICE_NO, OUT_TYPE_DIV, OUT_BOX_DIV
             , (SELECT MAX(LPAD(ORDER_QTY, 5, '0') || '-' || LPAD(LINE_NO, 3, '0'))
                  FROM LO_OUT_D M2
                 WHERE M2.INVOICE_NO = M1.INVOICE_NO) AS MAX_VAL
          FROM LO_OUT_M M1
         WHERE OUTBOUND_DATE = TO_DATE('2019-06-03', 'YYYY-MM-DD')
           AND OUTBOUND_NO   BETWEEN 'D190603-897353'
                                 AND 'D190603-897360'
        )
;
