--뷰, 인라인뷰
--1 - (1)
SELECT M1.BRAND_CD, M1.ITEM_CD, M1.SUM_QTY
     , (SELECT ITEM_NM
          FROM A_ITEM M2
         WHERE M2.BRAND_CD = M1.BRAND_CD
           AND M2.ITEM_CD  = M1.ITEM_CD
        ) AS ITEM_NM
     , (SELECT QTY_IN_BOX
          FROM A_ITEM M3
         WHERE M3.BRAND_CD = M1.BRAND_CD
           AND M3.ITEM_CD  = M1.ITEM_CD
        ) AS QTY_IN_BOX
  FROM (SELECT BRAND_CD, ITEM_CD
             , SUM(ORDER_QTY) AS SUM_QTY
          FROM A_OUT_D
         GROUP BY BRAND_CD, ITEM_CD
        ) M1
;

--1 - (2)
SELECT BRAND_CD, ITEM_CD, SUM_QTY, ITEM_NM, QTY_IN_BOX
     , TRUNC(SUM_QTY / QTY_IN_BOX) AS BOX_CNT
     , MOD(SUM_QTY, QTY_IN_BOX)    AS PCS_CNT
  FROM (SELECT M1.BRAND_CD, M1.ITEM_CD, M1.SUM_QTY
             , (SELECT ITEM_NM
                  FROM A_ITEM M2
                 WHERE M2.BRAND_CD = M1.BRAND_CD
                   AND M2.ITEM_CD  = M1.ITEM_CD
                ) AS ITEM_NM
             , (SELECT QTY_IN_BOX
                  FROM A_ITEM M3
                 WHERE M3.BRAND_CD = M1.BRAND_CD
                   AND M3.ITEM_CD  = M1.ITEM_CD
                ) AS QTY_IN_BOX
          FROM (SELECT BRAND_CD, ITEM_CD
                     , SUM(ORDER_QTY) AS SUM_QTY
                  FROM A_OUT_D
                 GROUP BY BRAND_CD, ITEM_CD
                ) M1
        )
;

--1 - (3)
SELECT BRAND_CD, ITEM_CD, SUM_QTY, ITEM_NM, QTY_IN_BOX, BOX_CNT, PCS_CNT
  FROM (SELECT BRAND_CD, ITEM_CD, SUM_QTY, ITEM_NM, QTY_IN_BOX
             , TRUNC(SUM_QTY / QTY_IN_BOX) AS BOX_CNT
             , MOD(SUM_QTY, QTY_IN_BOX)    AS PCS_CNT
             , ROWNUM                      AS RNK
          FROM (SELECT M1.BRAND_CD, M1.ITEM_CD, M1.SUM_QTY
                     , (SELECT ITEM_NM
                          FROM A_ITEM M2
                         WHERE M2.BRAND_CD = M1.BRAND_CD
                           AND M2.ITEM_CD  = M1.ITEM_CD
                        ) AS ITEM_NM
                     , (SELECT QTY_IN_BOX
                          FROM A_ITEM M3
                         WHERE M3.BRAND_CD = M1.BRAND_CD
                           AND M3.ITEM_CD  = M1.ITEM_CD
                        ) AS QTY_IN_BOX
                  FROM (SELECT BRAND_CD, ITEM_CD
                             , SUM(ORDER_QTY) AS SUM_QTY
                          FROM A_OUT_D
                         GROUP BY BRAND_CD, ITEM_CD
                        ) M1
                )
        )
 WHERE RNK < 4
;

--실전문제①
SELECT ITEM_CD
     , (SELECT M2.ITEM_NM      
          FROM CM_ITEM M2
         WHERE M2.ITEM_CD = M1.ITEM_CD
        )  
    , ORDER_QTY
  FROM (SELECT ITEM_CD, SUM(ORDER_QTY) AS ORDER_QTY
          FROM LO_OUT_D
         WHERE INVOICE_NO BETWEEN '346724706262'
                                 AND '346724706762'
         GROUP BY ITEM_CD
        ) M1
;

--실전문제②
SELECT ROWNUM       AS RNK
     , ITEM_CD, QTY_IN_BOX, ORDER_QTY
     , TRUNC(ORDER_QTY/QTY_IN_BOX) AS BOX_CNT
     , MOD(ORDER_QTY, QTY_IN_BOX)  AS PCS_CNT
     , CEIL(ORDER_QTY/QTY_IN_BOX) AS BOX_CNT_TOT
  FROM (SELECT ITEM_CD, QTY_IN_BOX
             , SUM(ORDER_QTY) AS ORDER_QTY
          FROM LO_OUT_D
         WHERE INVOICE_NO BETWEEN '346724706262'
                              AND '346724706762'
         GROUP BY ITEM_CD, QTY_IN_BOX
         ORDER BY ORDER_QTY DESC
        )
 WHERE ROWNUM < 6
;

--내장함수일반
--1 - (1)
SELECT OUTBOUND_DATE
     , TO_CHAR(OUTBOUND_DATE, 'DY') AS DY
     , INVOICE_NO
     , ORDER_NM
  FROM A_OUT_M
 WHERE BRAND_CD = '1001'
;

--1 - (2)
SELECT OUTBOUND_DATE
     , TO_CHAR(OUTBOUND_DATE, 'DY') AS DY
     , INVOICE_NO
     , ORDER_NM
     , CASE MOD(TO_NUMBER(SUBSTR(INVOICE_NO, 2)), 2) WHEN 0 THEN '짝수' ELSE '홀수' END AS EVENODD
  FROM A_OUT_M
 WHERE BRAND_CD = '1001'
;

--2 - (1)
SELECT BRAND_CD
     , COUNT(INVOICE_NO) AS CNT
  FROM A_OUT_M
 GROUP BY BRAND_CD
;

--2 - (2)
SELECT BRAND_CD
     , TO_CHAR(OUTBOUND_DATE, 'DAY') AS DYY
     , COUNT(INVOICE_NO) AS CNT
  FROM A_OUT_M
 GROUP BY BRAND_CD, TO_CHAR(OUTBOUND_DATE, 'DAY')
;

--2 - (3)
SELECT BRAND_CD
        , CASE MOD(TO_NUMBER(SUBSTR(INVOICE_NO, 2)), 2) WHEN 0 THEN '짝수' ELSE '홀수' END AS EVENODD
     , COUNT(INVOICE_NO) AS CNT
  FROM A_OUT_M
 GROUP BY BRAND_CD
        , CASE MOD(TO_NUMBER(SUBSTR(INVOICE_NO, 2)), 2) WHEN 0 THEN '짝수' ELSE '홀수' END
;

--실전문제①
SELECT INVOICE_NO, OUTBOUND_DATE
     , TO_CHAR(OUTBOUND_DATE, 'DAY') AS DAYY
     , OUTBOUND_NO
  FROM LO_OUT_M
 WHERE INVOICE_NO IN ('346724706214', '346724793596', '346724869970')
;

--실전문제②
SELECT NVL(TO_CHAR(SUM(ORDER_QTY)), 'Empty..') AS ORDER_QTY
  FROM LO_OUT_D
 WHERE INVOICE_NO = '346724706215'
;

--내장함수CASE
--1 - (1)
SELECT OUTBOUND_DATE
     , TO_CHAR(OUTBOUND_DATE, 'DAY') AS DAY
     , INVOICE_NO
     , CASE MOD(TO_NUMBER(SUBSTR(INVOICE_NO, 2)), 2) WHEN 0 THEN '짝수' ELSE '홀수' END AS EVENODD
     , ORDER_NM
     , CASE WHEN OUT_TYPE_DIV LIKE 'M1%' THEN '상온' ELSE '저온' END AS TEMP
  FROM A_OUT_M
;

--1 - (2)
SELECT BRAND_CD, INVOICE_NO, LINE_NO, ITEM_CD, ORDER_QTY
     , CASE WHEN ORDER_QTY < 3 THEN '하'
            WHEN ORDER_QTY < 5 THEN '중'
            ELSE                    '상' END AS GRADE
  FROM A_OUT_D
;

--2 - (1)
SELECT BRAND_CD
     , CASE WHEN ORDER_QTY BETWEEN 1 AND 2 THEN '하'
            WHEN ORDER_QTY BETWEEN 3 AND 4 THEN '중'
            ELSE                         '상' END AS GRADE
     , COUNT(INVOICE_NO) AS CNT
  FROM A_OUT_D
 GROUP BY BRAND_CD
         , CASE WHEN ORDER_QTY BETWEEN 1 AND 2 THEN '하'
                WHEN ORDER_QTY BETWEEN 3 AND 4 THEN '중'
                ELSE                         '상'    END
;

--2 - (2)
SELECT BRAND_CD
     , CASE WHEN SUM_QTY BETWEEN 1 AND 2 THEN '하'
            WHEN SUM_QTY BETWEEN 3 AND 4 THEN '중'
            ELSE                              '상' END AS GRADE
     , SUM(SUM_QTY) AS SUM_QTY
  FROM (SELECT BRAND_CD, INVOICE_NO
             , SUM(ORDER_QTY) AS SUM_QTY
          FROM A_OUT_D
         GROUP BY BRAND_CD, INVOICE_NO
        )
 GROUP BY BRAND_CD
       , CASE WHEN SUM_QTY BETWEEN 1 AND 2 THEN '하'
              WHEN SUM_QTY BETWEEN 3 AND 4 THEN '중'
              ELSE                              '상' END
;
    
--2 - (3)
SELECT CASE WHEN ROWNUM < 3 THEN ITEM_CD ELSE 'etc' END AS ITEM_CD
     , SUM(SUM_QTY) AS SUM_QTY
  FROM (SELECT ITEM_CD
             , SUM(ORDER_QTY) AS SUM_QTY
          FROM A_OUT_D
         GROUP BY ITEM_CD
         ORDER BY SUM_QTY DESC
        )
 GROUP BY CASE WHEN ROWNUM < 3 THEN ROWNUM ELSE 999 END
        , CASE WHEN ROWNUM < 3 THEN ITEM_CD ELSE 'etc' END
 ORDER BY CASE WHEN ROWNUM < 3 THEN ROWNUM ELSE 999 END
;

--3 - (1)
SELECT BRAND_CD, INVOICE_NO, LINE_NO, ITEM_CD, ORDER_QTY
     , CASE WHEN ORDER_QTY BETWEEN 1 AND 2 THEN '하'
            WHEN ORDER_QTY BETWEEN 3 AND 4 THEN '중'
            ELSE                                '상' END AS GRADE
  FROM A_OUT_D
 WHERE BRAND_CD = '1001'
 ORDER BY CASE WHEN ITEM_CD = 'C' THEN 0 ELSE 1 END
      , ITEM_CD, ORDER_QTY DESC
;

--실전문제①
SELECT OUTBOUND_DATE
     , COUNT(1) AS INVOICE_CNT
     , COUNT(CASE WHEN OUT_TYPE_DIV LIKE 'M1%' THEN 1 END) AS M1_CNT
     , COUNT(CASE WHEN OUT_TYPE_DIV LIKE 'M2%' THEN 2 END) AS M2_CNT
  FROM LO_OUT_M
 WHERE OUTBOUND_DATE BETWEEN TO_DATE(SUBSTR(:OUTBOUND_DATE, 1, 8) || 01, 'YYYY-MM-DD')
                         AND TO_DATE(:OUTBOUND_DATE, 'YYYY-MM-DD')
   AND OUT_BOX_DIV LIKE CASE :COND WHEN '1' THEN 'D'
                                   WHEN '2' THEN 'F'
                                   WHEN '0' THEN NULL
                                   ELSE          'QWEDAS' END || '%'
 GROUP BY OUTBOUND_DATE
;

--실전문제②
SELECT ITEM_BAR_CD
     , COUNT(ITEM_CD) AS ITEM_CNT
  FROM LO_OUT_D
 GROUP BY ITEM_BAR_CD
 HAVING COUNT(DISTINCT ITEM_CD) > 2
 ORDER BY CASE WHEN ITEM_BAR_CD IS NULL THEN 2 ELSE 1 END
        , ITEM_CNT DESC
;

--실전문제③
SELECT SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '01' THEN SET_QTY END) AS M01
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '02' THEN SET_QTY END) AS M02
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '03' THEN SET_QTY END) AS M03
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '04' THEN SET_QTY END) AS M04
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '05' THEN SET_QTY END) AS M05
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '06' THEN SET_QTY END) AS M06
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '07' THEN SET_QTY END) AS M07
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '08' THEN SET_QTY END) AS M08
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '09' THEN SET_QTY END) AS M09
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '10' THEN SET_QTY END) AS M10
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '11' THEN SET_QTY END) AS M11
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '12' THEN SET_QTY END) AS M12
  FROM LO_OUT_M
 WHERE TO_CHAR(OUTBOUND_DATE, 'YYYY') = '2019'
;

--실전문제④
SELECT OUTBOUND_DATE
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '01' THEN SET_QTY END) AS M01
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '02' THEN SET_QTY END) AS M02
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '03' THEN SET_QTY END) AS M03
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '04' THEN SET_QTY END) AS M04
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '05' THEN SET_QTY END) AS M05
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '06' THEN SET_QTY END) AS M06
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '07' THEN SET_QTY END) AS M07
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '08' THEN SET_QTY END) AS M08
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '09' THEN SET_QTY END) AS M09
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '10' THEN SET_QTY END) AS M10
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '11' THEN SET_QTY END) AS M11
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '12' THEN SET_QTY END) AS M12
  FROM LO_OUT_M
 WHERE TO_CHAR(OUTBOUND_DATE, 'YYYY') = '2019'
 GROUP BY OUTBOUND_DATE
 ORDER BY OUTBOUND_DATE
;

--실전문제⑤
SELECT TO_CHAR(OUTBOUND_DATE, 'YYYY') AS YYYY
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '01' THEN SET_QTY END) AS M01
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '02' THEN SET_QTY END) AS M02
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '03' THEN SET_QTY END) AS M03
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '04' THEN SET_QTY END) AS M04
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '05' THEN SET_QTY END) AS M05
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '06' THEN SET_QTY END) AS M06
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '07' THEN SET_QTY END) AS M07
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '08' THEN SET_QTY END) AS M08
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '09' THEN SET_QTY END) AS M09
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '10' THEN SET_QTY END) AS M10
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '11' THEN SET_QTY END) AS M11
     , SUM(CASE WHEN TO_CHAR(OUTBOUND_DATE, 'MM') = '12' THEN SET_QTY END) AS M12
  FROM LO_OUT_M
 WHERE TO_CHAR(OUTBOUND_DATE, 'YYYY') <> '2023'
 GROUP BY TO_CHAR(OUTBOUND_DATE, 'YYYY')
 ORDER BY TO_CHAR(OUTBOUND_DATE, 'YYYY')
;

--실전문제⑥
SELECT INVOICE_NO, LINE_NO, ITEM_CD, ITEM_NM, ORDER_QTY
  FROM LO_OUT_D
 WHERE INVOICE_NO = '346724706214'
 ORDER BY CASE :SORT_TYPE WHEN '1' THEN LINE_NO
                          WHEN '2' THEN ORDER_QTY END
       , LINE_NO
;

--조인기본
--1 - (1)
SELECT M2.BRAND_CD, M1.OUTBOUND_DATE, M2.INVOICE_NO, M2.LINE_NO, M2.ORDER_QTY
 FROM A_OUT_M M1 
      JOIN A_OUT_D M2 ON  M2.BRAND_CD   = M1.BRAND_CD
                      AND M2.INVOICE_NO = M1.INVOICE_NO
                      AND M2.ITEM_CD IN ('B', 'D')
 WHERE M1.OUTBOUND_DATE = TO_DATE('2023-01-04', 'YYYY-MM-DD')
;

--1 - (2)
SELECT M2.BRAND_CD, M1.OUTBOUND_DATE, M2.ITEM_CD
     , SUM(ORDER_QTY) AS SUM_QTY
  FROM A_OUT_M M1
       JOIN A_OUT_D M2 ON  M2.BRAND_CD   = M1.BRAND_CD
                       AND M2.INVOICE_NO = M1.INVOICE_NO
                       AND M2.ITEM_CD IN ('B', 'D')
 WHERE M1.OUTBOUND_DATE BETWEEN '2023-01-03' AND '2023-01-04'
 GROUP BY M2.BRAND_CD, M1.OUTBOUND_DATE, M2.ITEM_CD
 ORDER BY BRAND_CD, OUTBOUND_DATE
;

--1 - (3)
SELECT M2.INVOICE_NO, M2.ORDER_NM
  FROM (SELECT INVOICE_NO
             , SUM(ORDER_QTY) AS SUM_QTY
          FROM A_OUT_D
         WHERE BRAND_CD = '1001'
         GROUP BY INVOICE_NO
         ORDER BY SUM_QTY DESC
        ) M1 JOIN A_OUT_M M2 ON  M2.INVOICE_NO = M1.INVOICE_NO
                             AND M2.OUTBOUND_DATE BETWEEN '2023-01-04' AND '2023-01-05'
 WHERE ROWNUM = 1
;

--2 - (1)
SELECT M1.BRAND_CD, M1.OUTBOUND_DATE, M1.INVOICE_NO, M2.ITEM_CD, M3.ITEM_NM, M2.ORDER_QTY
  FROM (SELECT BRAND_CD, OUTBOUND_DATE, INVOICE_NO
          FROM A_OUT_M
         WHERE OUTBOUND_DATE BETWEEN '2023-01-01' AND '2023-01-04'
        ) M1 JOIN A_OUT_D M2 ON  M2.BRAND_CD   = M1.BRAND_CD
                             AND M2.INVOICE_NO = M1.INVOICE_NO
                             AND M2.ORDER_QTY >= 3
             JOIN A_ITEM  M3 ON  M3.BRAND_CD   = M1.BRAND_CD
                             AND M3.ITEM_CD    = M2.ITEM_CD
;

--2 - (2)
SELECT M1.BRAND_CD, M2.ITEM_CD, C1.ITEM_NM, C1.QTY_IN_BOX, SUM(M2.ORDER_QTY) AS SUM_QTY
  FROM A_OUT_M M1
       JOIN A_OUT_D M2 ON  M2.BRAND_CD   = M1.BRAND_CD
                       AND M2.INVOICE_NO = M1.INVOICE_NO
       JOIN A_ITEM  C1 ON  C1.BRAND_CD   = M2.BRAND_CD
                       AND C1.ITEM_CD    = M2.ITEM_CD
 WHERE OUTBOUND_DATE BETWEEN TO_DATE('2023-01-01', 'YYYY-MM-DD')
                         AND TO_DATE('2023-01-04', 'YYYY-MM-DD')
 GROUP BY M1.BRAND_CD, M2.ITEM_CD, C1.ITEM_NM, C1.QTY_IN_BOX
;

--2 - (3)
SELECT TRUNC(SUM_QTY / QTY_IN_BOX) AS CNT_BOX
     , MOD(SUM_QTY, QTY_IN_BOX)    AS CNT_PCS
  FROM (SELECT M1.BRAND_CD, M2.ITEM_CD, M3.ITEM_NM, M3.QTY_IN_BOX, SUM(M2.ORDER_QTY) AS SUM_QTY
          FROM A_OUT_M M1 JOIN A_OUT_D M2 ON  M2.BRAND_CD   = M1.BRAND_CD
                                          AND M2.INVOICE_NO = M1.INVOICE_NO
                                          AND M2.ORDER_QTY >= 3
                          JOIN A_ITEM  M3 ON  M3.BRAND_CD   = M1.BRAND_CD
                                          AND M3.ITEM_CD    = M2.ITEM_CD
         GROUP BY M1.BRAND_CD, M2.ITEM_CD, M3.ITEM_NM, M3.QTY_IN_BOX
        )
;

--2 - (4)
SELECT *
  FROM (SELECT M3.*
              , TRUNC(SUM_QTY / QTY_IN_BOX) AS BOX_CNT
              , MOD(SUM_QTY, QTY_IN_BOX)    AS ITEM_CNT
          FROM (SELECT M1.BRAND_CD, M2.ITEM_CD, C1.ITEM_NM, C1.QTY_IN_BOX, SUM(M2.ORDER_QTY) AS SUM_QTY
                  FROM A_OUT_M M1
                       JOIN A_OUT_D M2 ON  M2.BRAND_CD   = M1.BRAND_CD
                                       AND M2.INVOICE_NO = M1.INVOICE_NO
                       JOIN A_ITEM  C1 ON  C1.BRAND_CD   = M2.BRAND_CD
                                       AND C1.ITEM_CD    = M2.ITEM_CD
                 WHERE OUTBOUND_DATE BETWEEN TO_DATE('2023-01-01', 'YYYY-MM-DD')
                                         AND TO_DATE('2023-01-04', 'YYYY-MM-DD')
                 GROUP BY M1.BRAND_CD, M2.ITEM_CD, C1.ITEM_NM, C1.QTY_IN_BOX
                ) M3
          ORDER BY BOX_CNT DESC
        ) 
 WHERE ROWNUM <= 3
;

--실전문제①
SELECT M1.INVOICE_NO, M1.OUTBOUND_DATE, M1.OUT_TYPE_DIV, M2.LINE_NO, M2.ITEM_CD, M3.ITEM_NM, M2.ORDER_QTY
  FROM LO_OUT_M M1
       JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
       JOIN CM_ITEM  M3 ON M3.ITEM_CD    = M2.ITEM_CD
 WHERE M1.INVOICE_NO IN ('346724703834', '34674722535', '346724717915')
;

--실전문제②
SELECT M1.INVOICE_NO, M1.OUTBOUND_DATE, M1.OUT_TYPE_DIV, M2.LINE_NO, M2.ITEM_NM, M2.ORDER_QTY
     , C1.CODE_NM AS TEMP_NM
     , C2.CODE_NM AS OUT_TYPE_NM
  FROM LO_OUT_M M1
       JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
       JOIN CS_CODE  C1 ON  C1.CODE_GRP  = 'LDIV01'
                        AND C1.CODE_CD   = M1.TEMP_DIV
       JOIN CS_CODE  C2 ON  C2.CODE_GRP  = 'LDIV03'
                        AND C2.CODE_CD   = M1.OUT_TYPE_DIV
 WHERE M1.INVOICE_NO IN ('346724703834', '346724722535', '346724717915')
;

SELECT *
FROM CS_CODE;

--LO_OUT_M: INVOICE_NO, OUTBOUND_DATE, OUTBOUND_NO, ORDER_PLACE, OUTBOUND_BATCH, TEMP_DIV, OUT_TYPE_DIV, OUT_BOX_DIV, OUT_BOX_NM, SET_TYPE_CD, SET_TYPE_NM, SET_QTY, SET_STATE, WORK_SEQ, REG_USER_ID, REG_DATETIME
--LO_OUT_D: INVOICE_NO, LINE_NO, ITEM_CD, ITEM_NM, ITEM_BAR_CD, BOX_BAR_CD, ITEM_WEIGHT, QTY_IN_BOX, BOX_WEIGHT, ITEM_WIDTH, ITEM_LENGTH, ITEM_HEIGHT, ITEM_CBM, SALE_PLACE, ORDER_QTY, REG_USER_ID, REG_DATETIME, OUT_TYPE_DIV_D
--CM_ITEM: ITEM_CD, ITEM_NM, QTY_IN_BOX, REG_USER_ID, REG_DATETIME