--분석함수2
--실전문제①
SELECT OUTBOUND_DATE, OUTBOUND_BATCH, ORDER_QTY
     , RANK()         OVER(PARTITION BY OUTBOUND_DATE ORDER BY ORDER_QTY DESC) AS RANK_PER_DAY
     , SUM(ORDER_QTY) OVER(PARTITION BY OUTBOUND_DATE ORDER BY ORDER_QTY DESC) AS ACC_SUM_PER_DAY
     , SUM(ORDER_QTY) OVER(PARTITION BY OUTBOUND_DATE)                         AS SUM_PER_DAY
     , SUM(ORDER_QTY) OVER(ORDER BY OUTBOUND_DATE)                             AS ACC_SUM_DAY
     , COUNT(1)       OVER(PARTITION BY OUTBOUND_DATE)                         AS CNT_PER_DAY
     , COUNT(1)       OVER()                                                   AS CNT_TOT
  FROM (SELECT M1.OUTBOUND_DATE, M1.OUTBOUND_BATCH, SUM(M2.ORDER_QTY) AS ORDER_QTY
          FROM LO_OUT_M M1 JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
         WHERE M1.OUTBOUND_DATE BETWEEN '2019-09-03' AND '2019-09-10'
           AND M1.OUT_TYPE_DIV  = 'M11'
         GROUP BY M1.OUTBOUND_DATE, M1.OUTBOUND_BATCH
         ORDER BY OUTBOUND_DATE
        )
;

--실전문제②
SELECT OUTBOUND_DATE
     , RANK() OVER(PARTITION BY OUTBOUND_DATE ORDER BY ORDER_QTY DESC) AS RNK_PER_DAY 
     , OUTBOUND_BATCH, ORDER_QTY
  FROM (SELECT M1.OUTBOUND_DATE, M1.OUTBOUND_BATCH, SUM(M2.ORDER_QTY) AS ORDER_QTY
          FROM LO_OUT_M M1 JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
         WHERE M1.OUTBOUND_DATE BETWEEN '2019-09-03' AND '2019-09-10'
           AND M1.OUT_TYPE_DIV  =       'M11'
         GROUP BY M1.OUTBOUND_DATE, M1.OUTBOUND_BATCH
         ORDER BY OUTBOUND_DATE
        )
;

--실전문제③
SELECT CASE WHEN LAG(OUTBOUND_DATE) OVER(PARTITION BY OUTBOUND_DATE ORDER BY OUTBOUND_DATE) IS NULL THEN TO_CHAR(OUTBOUND_DATE, 'YY/MM/DD') END AS OUT_DATE
     , OUTBOUND_BATCH, ORDER_QTY, SUM_PER_DAY
     , DENSE_RANK() OVER(ORDER BY SUM_PER_DAY DESC) AS ACC_RNK_SUM_PER_DAY
     , RANK() OVER(ORDER BY ORDER_QTY DESC)         AS RNK_PER_DAY
  FROM (SELECT M1.OUTBOUND_DATE, M1.OUTBOUND_BATCH, SUM(M2.ORDER_QTY)  AS ORDER_QTY
             , SUM(SUM(M2.ORDER_QTY)) OVER(PARTITION BY OUTBOUND_DATE) AS SUM_PER_DAY
          FROM LO_OUT_M M1 JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
         WHERE M1.OUTBOUND_DATE BETWEEN '2019-09-03' AND '2019-09-10'
           AND M1.OUT_TYPE_DIV  =       'M11'
         GROUP BY M1.OUTBOUND_DATE, M1.OUTBOUND_BATCH
         ORDER BY SUM_PER_DAY DESC
        )
 ORDER BY SUM_PER_DAY DESC, OUTBOUND_BATCH
;

--실전문제④
SELECT CASE WHEN RNK <= 5 THEN TO_CHAR(OUTBOUND_DATE, 'YYYY-MM-DD')
            ELSE '기타'    END AS OUTBOUND_DATE
     , SUM(ORDER_QTY)         AS ORDER_QTY
     , SUM(RATE)              AS RATE 
     , MIN(RNK)               AS RNK
  FROM (SELECT M1.OUTBOUND_DATE, SUM(M2.ORDER_QTY) AS ORDER_QTY
             , RANK() OVER(ORDER BY SUM(M2.ORDER_QTY) DESC) AS RNK
             , ROUND(RATIO_TO_REPORT(SUM(M2.ORDER_QTY)) OVER() * 100, 3) AS RATE
          FROM LO_OUT_M M1 JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
         WHERE M1.OUTBOUND_DATE BETWEEN '2019-09-01' AND '2019-09-15'
         GROUP BY M1.OUTBOUND_DATE
         ORDER BY ORDER_QTY DESC
        )
 GROUP BY CASE WHEN RNK <= 5 THEN TO_CHAR(OUTBOUND_DATE, 'YYYY-MM-DD')
            ELSE '기타'    END
 ORDER BY RNK
;

--분석함수3
--실전문제①
SELECT LAG(NULL, 1, OUTBOUND_DATE) OVER(PARTITION BY TO_CHAR(OUTBOUND_DATE, 'YYYY-MM-DD') ORDER BY RNK) AS OUTBOUND_DATE
     , RNK, ITEM_NM, ORDER_QTY
  FROM (SELECT M1.OUTBOUND_DATE, M2.ITEM_NM
             , SUM(M2.ORDER_QTY) AS ORDER_QTY
             , ROW_NUMBER() OVER(PARTITION BY M1.OUTBOUND_DATE ORDER BY SUM(M2.ORDER_QTY) DESC) AS RNK
          FROM LO_OUT_M M1 JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
         WHERE M1.OUTBOUND_DATE BETWEEN '2019-09-03' AND '2019-09-05'
         GROUP BY M1.OUTBOUND_DATE, M2.ITEM_NM
        )
 WHERE RNK <= 3
;

--실전문제②
SELECT LAG(NULL, 1, OUTBOUND_DATE) OVER(PARTITION BY TO_CHAR(OUTBOUND_DATE, 'YYYY-MM-DD') ORDER BY RNK) AS OUTBOUND_DATE
     , RNK, ORDER_QTY, RATE
  FROM (SELECT M1.OUTBOUND_DATE, M2.ITEM_NM
             , SUM(M2.ORDER_QTY) AS ORDER_QTY
             , ROW_NUMBER() OVER(PARTITION BY M1.OUTBOUND_DATE ORDER BY SUM(M2.ORDER_QTY) DESC) AS RNK
             , ROUND(RATIO_TO_REPORT(SUM(M2.ORDER_QTY)) OVER(PARTITION BY M1.OUTBOUND_DATE) * 100, 2) AS RATE
          FROM LO_OUT_M M1 JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
         WHERE M1.OUTBOUND_DATE BETWEEN '2019-09-03' AND '2019-09-05'
         GROUP BY M1.OUTBOUND_DATE, M2.ITEM_NM
         ORDER BY ORDER_QTY DESC
        )
 WHERE RNK <= 3
;

--데이터압축하기1
--실전문제①
SELECT M1.OUTBOUND_DATE, SUM(M2.ORDER_QTY) AS ORDER_QTY
  FROM LO_OUT_M M1 JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
 WHERE M1.OUTBOUND_DATE BETWEEN TO_DATE(:OUTBOUND_DATE, 'YYYY-MM')
                            AND LAST_DAY(TO_DATE(:OUTBOUND_DATE, 'YYYY-MM'))
 GROUP BY M1.OUTBOUND_DATE
 ORDER BY ORDER_QTY DESC
;

--실전문제②
SELECT SUM(CASE TO_CHAR(M1.OUTBOUND_DATE, 'D') WHEN '1' THEN M2.ORDER_QTY END) AS SUN
     , SUM(CASE TO_CHAR(M1.OUTBOUND_DATE, 'D') WHEN '2' THEN M2.ORDER_QTY END) AS MON
     , SUM(CASE TO_CHAR(M1.OUTBOUND_DATE, 'D') WHEN '3' THEN M2.ORDER_QTY END) AS TUE
     , SUM(CASE TO_CHAR(M1.OUTBOUND_DATE, 'D') WHEN '4' THEN M2.ORDER_QTY END) AS WED
     , SUM(CASE TO_CHAR(M1.OUTBOUND_DATE, 'D') WHEN '5' THEN M2.ORDER_QTY END) AS THU
     , SUM(CASE TO_CHAR(M1.OUTBOUND_DATE, 'D') WHEN '6' THEN M2.ORDER_QTY END) AS FRI
     , SUM(CASE TO_CHAR(M1.OUTBOUND_DATE, 'D') WHEN '7' THEN M2.ORDER_QTY END) AS SAT
  FROM LO_OUT_M M1 JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
 WHERE M1.OUTBOUND_DATE BETWEEN TO_DATE(:OUTBOUND_DATE, 'YYYY-MM')
                            AND LAST_DAY(TO_DATE(:OUTBOUND_DATE, 'YYYY-MM'))
;

SELECT TO_CHAR(M1.OUTBOUND_DATE, 'DAY') AS DAY
     , SUM(M2.ORDER_QTY)                AS ORDER_QTY
  FROM LO_OUT_M M1 JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
 WHERE M1.OUTBOUND_DATE BETWEEN TO_DATE(:OUTBOUND_DATE, 'YYYY-MM')
                            AND LAST_DAY(TO_DATE(:OUTBOUND_DATE, 'YYYY-MM'))
 GROUP BY TO_CHAR(M1.OUTBOUND_DATE, 'D')
        , TO_CHAR(M1.OUTBOUND_DATE, 'DAY')
 ORDER BY TO_CHAR(M1.OUTBOUND_DATE, 'D')
;

--실전문제①
SELECT SUM(CASE TO_CHAR(M1.OUTBOUND_DATE, 'MM') WHEN '01' THEN M2.ORDER_QTY END) AS M01
     , SUM(CASE TO_CHAR(M1.OUTBOUND_DATE, 'MM') WHEN '02' THEN M2.ORDER_QTY END) AS M02
     , SUM(CASE TO_CHAR(M1.OUTBOUND_DATE, 'MM') WHEN '03' THEN M2.ORDER_QTY END) AS M03
     , SUM(CASE TO_CHAR(M1.OUTBOUND_DATE, 'Q')  WHEN '1'  THEN M2.ORDER_QTY END) AS Q1
     , SUM(CASE TO_CHAR(M1.OUTBOUND_DATE, 'MM') WHEN '04' THEN M2.ORDER_QTY END) AS M04
     , SUM(CASE TO_CHAR(M1.OUTBOUND_DATE, 'MM') WHEN '05' THEN M2.ORDER_QTY END) AS M05
     , SUM(CASE TO_CHAR(M1.OUTBOUND_DATE, 'MM') WHEN '06' THEN M2.ORDER_QTY END) AS M06
     , SUM(CASE TO_CHAR(M1.OUTBOUND_DATE, 'Q')  WHEN '2'  THEN M2.ORDER_QTY END) AS Q2
     , SUM(CASE TO_CHAR(M1.OUTBOUND_DATE, 'MM') WHEN '07' THEN M2.ORDER_QTY END) AS M07
     , SUM(CASE TO_CHAR(M1.OUTBOUND_DATE, 'MM') WHEN '08' THEN M2.ORDER_QTY END) AS M08
     , SUM(CASE TO_CHAR(M1.OUTBOUND_DATE, 'MM') WHEN '09' THEN M2.ORDER_QTY END) AS M09
     , SUM(CASE TO_CHAR(M1.OUTBOUND_DATE, 'Q')  WHEN '3'  THEN M2.ORDER_QTY END) AS Q3
     , SUM(CASE TO_CHAR(M1.OUTBOUND_DATE, 'MM') WHEN '10' THEN M2.ORDER_QTY END) AS M10
     , SUM(CASE TO_CHAR(M1.OUTBOUND_DATE, 'MM') WHEN '11' THEN M2.ORDER_QTY END) AS M11
     , SUM(CASE TO_CHAR(M1.OUTBOUND_DATE, 'MM') WHEN '12' THEN M2.ORDER_QTY END) AS M12
     , SUM(CASE TO_CHAR(M1.OUTBOUND_DATE, 'Q')  WHEN '4'  THEN M2.ORDER_QTY END) AS Q4
  FROM LO_OUT_M M1 JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
 WHERE M1.OUTBOUND_DATE BETWEEN :OUTBOUND_DATE || '0101'
                            AND :OUTBOUND_DATE || '1231'
;

--실전문제①
SELECT RNUM, ITEM_CD, ITEM_NM
     , SUM(ORDER_QTY)
  FROM (SELECT CASE WHEN RNUM <= 5 THEN RNUM      ELSE 0              END AS RNUM
             , CASE WHEN RNUM <= 5 THEN ITEM_CD   ELSE '99999'        END AS ITEM_CD
             , CASE WHEN RNUM <= 5 THEN ITEM_NM   ELSE 'TOP5제외 합계' END AS ITEM_NM
             , CASE WHEN RNUM <= 5 THEN ORDER_QTY ELSE ORDER_QTY      END AS ORDER_QTY
          FROM (SELECT M2.ITEM_CD, M2.ITEM_NM, SUM(M2.ORDER_QTY) AS ORDER_QTY
                     , ROW_NUMBER() OVER(ORDER BY SUM(M2.ORDER_QTY) DESC) AS RNUM
                  FROM LO_OUT_M M1 JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
                 WHERE M1.OUTBOUND_DATE BETWEEN '2019-06-01' AND '2019-06-30'
                   AND M2.ITEM_NM LIKE '%참치%'
                 GROUP BY M2.ITEM_CD, M2.ITEM_NM
                 ORDER BY ORDER_QTY DESC
                )
        )
 GROUP BY RNUM, ITEM_CD, ITEM_NM
 ORDER BY CASE WHEN RNUM = 0 THEN 99999 ELSE RNUM END
;

WITH BASE_01 AS(
SELECT M2.ITEM_CD, M2.ITEM_NM, SUM(M2.ORDER_QTY) AS ORDER_QTY
     , ROW_NUMBER() OVER(ORDER BY SUM(M2.ORDER_QTY) DESC) AS RNUM
  FROM LO_OUT_M M1 JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
 WHERE M1.OUTBOUND_DATE BETWEEN '2019-06-01' AND '2019-06-30'
   AND M2.ITEM_NM LIKE '%참치%'
 GROUP BY M2.ITEM_CD, M2.ITEM_NM
 ORDER BY ORDER_QTY DESC
), BASE_02 AS(
SELECT RNUM, ITEM_CD, ITEM_NM, ORDER_QTY
  FROM BASE_01
)

SELECT RNUM, ITEM_CD, ITEM_NM, ORDER_QTY
  FROM BASE_02
 WHERE RNUM <= 5

UNION ALL

SELECT 0              AS RNUM
     , '99999'        AS ITEM_CD
     , 'TOP5제외 합계' AS ITEM_NM
     , SUM(ORDER_QTY) AS ORDER_QTY
  FROM BASE_02
 WHERE RNUM > 5
;

--상반기평가
--문제①
SELECT DY, ORDER_QTY
  FROM (SELECT CASE WHEN ROWNUM <= 3 THEN DY ELSE 'etc' END AS DY
             , SUM(ORDER_QTY) AS ORDER_QTY
          FROM (SELECT TO_CHAR(M1.OUTBOUND_DATE, 'DY') AS DY
                     , SUM(M2.ORDER_QTY) AS ORDER_QTY
                  FROM LO_OUT_M M1 JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
                 WHERE M1.OUTBOUND_DATE BETWEEN ADD_MONTHS(TO_DATE(:OUTBOUND_DATE, 'YYYY-MM-DD'), -1)
                                            AND TO_DATE(:OUTBOUND_DATE, 'YYYY-MM-DD')
                 GROUP BY TO_CHAR(M1.OUTBOUND_DATE, 'DY')
                 ORDER BY ORDER_QTY DESC
                )
         GROUP BY CASE WHEN ROWNUM <= 3 THEN DY ELSE 'etc' END
        )
 ORDER BY CASE WHEN DY = 'etc' THEN 999 ELSE ROWNUM END
;

--문제②
SELECT SUM(CASE WHEN TO_CHAR(M1.OUTBOUND_DATE, 'D') BETWEEN '2' AND '6' THEN M2.ORDER_QTY END) AS WEEKDAYS
     , SUM(CASE WHEN TO_CHAR(M1.OUTBOUND_DATE, 'D') IN ('1', '7')       THEN M2.ORDER_QTY END) AS WEEKENDS
  FROM LO_OUT_M M1 JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
 WHERE M1.OUTBOUND_DATE BETWEEN ADD_MONTHS(TO_DATE(:OUTBOUND_DATE, 'YYYY-MM-DD'), -1)
                            AND TO_DATE(:OUTBOUND_DATE, 'YYYY-MM-DD')
;

--문제③
SELECT CASE WHEN TO_CHAR(M1.OUTBOUND_DATE, 'D') IN      ('1', '7')  THEN 'WEEKDAYS' 
            WHEN TO_CHAR(M1.OUTBOUND_DATE, 'D') BETWEEN '2' AND '6' THEN 'WEEKENDS' END AS WEEK
     , SUM(M2.ORDER_QTY) AS SUM_QTY
  FROM LO_OUT_M M1 JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
 WHERE M1.OUTBOUND_DATE BETWEEN ADD_MONTHS(TO_DATE(:OUTBOUND_DATE, 'YYYY-MM-DD'), -1)
                            AND TO_DATE(:OUTBOUND_DATE, 'YYYY-MM-DD')
 GROUP BY CASE WHEN TO_CHAR(M1.OUTBOUND_DATE, 'D') IN      ('1', '7')  THEN 'WEEKDAYS' 
               WHEN TO_CHAR(M1.OUTBOUND_DATE, 'D') BETWEEN '2' AND '6' THEN 'WEEKENDS' END
;

--문제④
SELECT OUT_DATE, DY
  FROM (SELECT ADD_MONTHS(TO_DATE(:OUTBOUND_DATE, 'YYYY-MM-DD'), -1) + LEVEL AS OUT_DATE
             , TO_CHAR(ADD_MONTHS(TO_DATE(:OUTBOUND_DATE, 'YYYY-MM-DD'), -1) + LEVEL, 'DY') AS DY
          FROM DUAL
         CONNECT BY LEVEL <= TO_DATE(:OUTBOUND_DATE, 'YYYY-MM-DD') - ADD_MONTHS(TO_DATE(:OUTBOUND_DATE, 'YYYY-MM-DD'), -1)
        ) D1 LEFT JOIN (SELECT M1.OUTBOUND_DATE, SUM(M2.ORDER_QTY) AS SUM_QTY
                        FROM LO_OUT_M M1 JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
                       WHERE M1.OUTBOUND_DATE BETWEEN ADD_MONTHS(TO_DATE(:OUTBOUND_DATE, 'YYYY-MM-DD'), -1)
                                                  AND TO_DATE(:OUTBOUND_DATE, 'YYYY-MM-DD')
                       GROUP BY M1.OUTBOUND_DATE
                      ) D2 ON D2.OUTBOUND_DATE = D1.OUT_DATE
 WHERE SUM_QTY IS NULL
 ORDER BY OUT_DATE
;

--문제⑤
SELECT OUTBOUND_DATE, DY, SUM_QTY
     , CASE WHEN SUM_QTY >= AVG(SUM_QTY) OVER(PARTITION BY DY) THEN 'High' ELSE 'Low' END AS GRADE
     , ROUND(AVG(SUM_QTY) OVER(PARTITION BY DY))                                          AS AVG_QTY
  FROM (SELECT M1.OUTBOUND_DATE
             , TO_CHAR(M1.OUTBOUND_DATE, 'DY')                                           AS DY
             , SUM(M2.ORDER_QTY)                                                         AS SUM_QTY             
          FROM LO_OUT_M M1 JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
         WHERE M1.OUTBOUND_DATE BETWEEN ADD_MONTHS(TO_DATE(:OUTBOUND_DATE, 'YYYY-MM-DD'), -1)
                                    AND TO_DATE(:OUTBOUND_DATE, 'YYYY-MM-DD')
         GROUP BY M1.OUTBOUND_DATE
        )
 WHERE SUM_QTY >= 170000
 ORDER BY OUTBOUND_DATE
;

--보너스 문제
SELECT CASE :SCHOOL 
        WHEN '1' THEN '초등학교 ' 
        WHEN '2' THEN '중학교 ' 
        WHEN '3' THEN '고등학교 ' END || TO_CHAR(NO) || '학년' AS SCHOOL 
     , TO_NUMBER(SUBSTR(:BIRTHDAY, 1, 4)) + CASE :SCHOOL 
        WHEN '1' THEN  6 + NO 
        WHEN '2' THEN  6 + 6 + NO 
        WHEN '3' THEN  6 + 6 + 3 + NO END AS YEAR
  FROM CS_NO
 WHERE NO <= CASE :SCHOOL 
      WHEN '1' THEN 6 
      WHEN '2' THEN 3 
      WHEN '3' THEN 3 END
;
