--조인활용1
--실전문제①
SELECT *
  FROM (SELECT M1.INVOICE_NO, M1.OUTBOUND_NO, M1.OUTBOUND_BATCH, M2.ITEM_CD, M2.ITEM_NM, M2.ORDER_QTY
          FROM LO_OUT_M M1 JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
         WHERE M1.OUTBOUND_DATE BETWEEN '2019-09-03' AND '2019-09-10'
           AND M2.ITEM_NM LIKE '%골뱅이%'
         ORDER BY ORDER_QTY DESC
        )
 WHERE ROWNUM <= 5
;

--실전문제②
SELECT M1.INVOICE_NO, M1.OUTBOUND_DATE, M1.OUT_TYPE_DIV, M2.LINE_NO, M2.ITEM_CD, M3.ITEM_NM, M2.ORDER_QTY
     , NVL(C1.CODE_NM, 'Failed..') AS TEMP_NM
     , NVL(C2.CODE_NM, 'Failed..') AS OUT_TYPE_NM
  FROM LO_OUT_M M1 JOIN LO_OUT_D M2     ON  M2.INVOICE_NO   = M1.INVOICE_NO
                   JOIN CM_ITEM  M3     ON  M3.ITEM_CD      = M2.ITEM_CD
                   LEFT JOIN CS_CODE C1 ON  C1.CODE_GRP = 'LDIV011'
                                        AND C1.CODE_CD  = M1.TEMP_DIV
                   LEFT JOIN CS_CODE C2 ON  C2.CODE_GRP = 'LDIV03'
                                        AND C2.CODE_CD  = M1.OUT_TYPE_DIV
 WHERE M1.INVOICE_NO IN ('346724703834', '346724722535', '346724717915')
;

--실전문제③
SELECT M1.OUT_DATE, SUM(M3.ORDER_QTY) AS QTY
  FROM (SELECT TO_DATE(SUBSTR(:OUTBOUND_DATE, 1, 8) || '01', 'YYYY-MM-DD') + LEVEL - 1 AS OUT_DATE
           FROM DUAL
        CONNECT BY LEVEL <= TO_DATE(:OUTBOUND_DATE, 'YYYY-MM-DD') - TO_DATE(SUBSTR(:OUTBOUND_DATE, 1, 8) || '01', 'YYYY-MM-DD') + 1
        ) M1 LEFT JOIN LO_OUT_M M2 ON M2.OUTBOUND_DATE = M1.OUT_DATE
             LEFT JOIN LO_OUT_D M3 ON M3.INVOICE_NO    = M2.INVOICE_NO
 GROUP BY M1.OUT_DATE
 ORDER BY OUT_DATE
;

--조인활용2
--실전문제①
SELECT M1.INVOICE_NO, M1.LINE_NO, M1.ITEM_CD, M1.ITEM_NM, M1.ORDER_QTY
     , SUM(M2.ORDER_QTY) AS ACC_ORDER_QTY
  FROM LO_OUT_D M1 JOIN LO_OUT_D M2 ON  M2.INVOICE_NO = M1.INVOICE_NO
                                    AND M2.LINE_NO    <= M1.LINE_NO
 WHERE M1.INVOICE_NO IN ('346724703845', '346724706214')
 GROUP BY M1.INVOICE_NO, M1.LINE_NO, M1.ITEM_CD, M1.ITEM_NM, M1.ORDER_QTY
 ORDER BY INVOICE_NO, LINE_NO
;

--실전문제②
SELECT M1.INVOICE_NO, M1.LINE_NO, M1.ITEM_CD, M1.ITEM_NM, M1.ORDER_QTY
     , SUM(M2.ORDER_QTY) AS ACC_ORDER_QTY
  FROM LO_OUT_D M1 JOIN LO_OUT_D M2 ON  M2.INVOICE_NO IN ('346724703845', '346724706214')
                                    AND M2.INVOICE_NO || LPAD(M2.LINE_NO, 3, '0') <= M1.INVOICE_NO || LPAD(M1.LINE_NO, 3, '0')
 WHERE M1.INVOICE_NO IN ('346724703845', '346724706214')
 GROUP BY M1.INVOICE_NO, M1.LINE_NO, M1.ITEM_CD, M1.ITEM_NM, M1.ORDER_QTY
 ORDER BY INVOICE_NO, LINE_NO
;

--분석함수1
--실전문제①
SELECT INVOICE_NO, LINE_NO, ITEM_NM, ORDER_QTY
     , MIN(ORDER_QTY) OVER (PARTITION BY INVOICE_NO) AS MIN_1
     , MIN(ORDER_QTY) OVER () AS MIN_2
     , MAX(ORDER_QTY) OVER (PARTITION BY INVOICE_NO) AS MAX_1
     , MAX(ORDER_QTY) OVER () AS MAX_2
  FROM LO_OUT_D
 WHERE INVOICE_NO IN ('346724703845', '346724706214', '346724706225')
;

--분석함수2
--실전문제①
SELECT OUTBOUND_DATE,OUTBOUND_BATCH, ORDER_QTY
     , ROW_NUMBER()   OVER (PARTITION BY OUTBOUND_DATE ORDER BY OUTBOUND_DATE) AS RNK_PER_DAY
     , SUM(ORDER_QTY) OVER (PARTITION BY OUTBOUND_DATE ORDER BY OUTBOUND_DATE) AS ACC_SUM_PER_DAY_RNK
     , SUM(ORDER_QTY) OVER (PARTITION BY OUTBOUND_DATE)                        AS SUM_TOT_PER_DAY
     , SUM(ORDER_QTY) OVER (ORDER BY OUTBOUND_DATE)                            AS ACC_SUM_PER_DAY
     , SUM(ORDER_QTY) OVER ()                                                  AS SUM_TOT
     , COUNT(1)       OVER (PARTITION BY OUTBOUND_DATE ORDER BY OUTBOUND_DATE) AS CNT_PER_DAY
     , COUNT(1)       OVER ()                                                  AS CNT_TOT
  FROM (SELECT M1.OUTBOUND_DATE, M1.OUTBOUND_BATCH, SUM(M2.ORDER_QTY) AS ORDER_QTY
          FROM LO_OUT_M M1 JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
         WHERE M1.OUTBOUND_DATE BETWEEN '2019-09-03' AND '2019-09-10'
           AND M1.OUT_TYPE_DIV = 'M11'
         GROUP BY M1.OUTBOUND_DATE, M1.OUTBOUND_BATCH
        )
;

--실전문제②
SELECT OUTBOUND_DATE
     , RANK() OVER(PARTITION BY OUTBOUND_DATE ORDER BY ORDER_QTY DESC) AS QTY_RNK_PER_DAY
     , OUTBOUND_BATCH, ORDER_QTY
FROM (SELECT M1.OUTBOUND_DATE, M1.OUTBOUND_BATCH, SUM(M2.ORDER_QTY) AS ORDER_QTY
        FROM LO_OUT_M M1 JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
       WHERE M1.OUTBOUND_DATE BETWEEN '2019-09-03' AND '2019-09-10'
         AND M1.OUT_TYPE_DIV = 'M11'
       GROUP BY M1.OUTBOUND_DATE, M1.OUTBOUND_BATCH
      )
 ORDER BY OUTBOUND_DATE, OUTBOUND_BATCH
;

--실전문제③
SELECT CASE WHEN LAG(OUT_DATE) OVER(PARTITION BY OUT_DATE ORDER BY OUT_DATE) IS NULL THEN TO_CHAR(OUT_DATE, 'YY/MM/DD') END AS OUT_DATE
     , OUTBOUND_BATCH, ORDER_QTY, SUM_PER_DAY
     , DENSE_RANK()            OVER(ORDER BY SUM_PER_DAY)                   AS RNK_SUM_PER_DAY
     , RANK()                  OVER(ORDER BY ORDER_QTY DESC)                AS RNK_TOT
  FROM (SELECT M1.OUTBOUND_DATE AS OUT_DATE, M1.OUTBOUND_BATCH
             , SUM(M2.ORDER_QTY)                                            AS ORDER_QTY
             , SUM(SUM(M2.ORDER_QTY)) OVER (PARTITION BY M1.OUTBOUND_DATE)  AS SUM_PER_DAY
          FROM LO_OUT_M M1 JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
         WHERE M1.OUTBOUND_DATE BETWEEN '2019-09-03' AND '2019-09-10'
           AND OUT_TYPE_DIV = 'M11'
         GROUP BY M1.OUTBOUND_DATE, M1.OUTBOUND_BATCH
        )
 ORDER BY SUM_PER_DAY DESC, OUTBOUND_BATCH
;

--실전문제④
SELECT CASE WHEN RNK <= 5 THEN TO_CHAR(OUTBOUND_DATE, 'YYYY-MM-DD') ELSE '기타' END AS OUTBOUND_DATE
     , SUM(ORDER_QTY) AS ORDER_QTY
     , MIN(RNK)       AS RNK
     , SUM(RATE)      AS RATE
  FROM (SELECT M1.OUTBOUND_DATE, SUM(M2.ORDER_QTY) AS ORDER_QTY
             , RANK() OVER(ORDER BY SUM(M2.ORDER_QTY)) AS RNK
             , ROUND(RATIO_TO_REPORT(SUM(M2.ORDER_QTY)) OVER() * 100, 3) AS RATE
          FROM LO_OUT_M M1 JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
         WHERE M1.OUTBOUND_DATE BETWEEN '2019-09-01' AND '2019-09-15'
         GROUP BY M1.OUTBOUND_DATE
        )
 GROUP BY CASE WHEN RNK <= 5 THEN TO_CHAR(OUTBOUND_DATE, 'YYYY-MM-DD') ELSE '기타' END
 ORDER BY RNK
;

--LO_OUT_M: INVOICE_NO, OUTBOUND_DATE, OUTBOUND_NO, ORDER_PLACE, OUTBOUND_BATCH, TEMP_DIV, OUT_TYPE_DIV, OUT_BOX_DIV, OUT_BOX_NM, SET_TYPE_CD, SET_TYPE_NM, SET_QTY, SET_STATE, WORK_SEQ, REG_USER_ID, REG_DATETIME
--LO_OUT_D: INVOICE_NO, LINE_NO, ITEM_CD, ITEM_NM, ITEM_BAR_CD, BOX_BAR_CD, ITEM_WEIGHT, QTY_IN_BOX, BOX_WEIGHT, ITEM_WIDTH, ITEM_LENGTH, ITEM_HEIGHT, ITEM_CBM, SALE_PLACE, ORDER_QTY, REG_USER_ID, REG_DATETIME, OUT_TYPE_DIV_D
--CM_ITEM: ITEM_CD, ITEM_NM, QTY_IN_BOX, REG_USER_ID, REG_DATETIME
--CS_CODE: CODE_GRP, CODE_CD, CODE_NM, SUB_CD, CODE_EX, SORT_RANK, LOCK_YN, REG_USER_ID, REG_DATETIME, LAST_USER_ID, LAST_DATETIME
--ER_OUT: RECV_DATE, RECV_NO, RECV_SEQ, INVOICE_NO, OUTBOUND_DATE, OUTBOUND_NO, LINE_NO, ORDER_PLACE, OUTBOUND_BATCH, TEMP_DIV, OUT_TYPE_DIV, OUT_BOX_DIV, OUT_BOX_NM, SET_TYPE_CD, SET_TYPE_NM, SET_QTY, ITEM_CD, ITEM_NM, ITEM_BAR_CD, BOX_BAR_CD, ITEM_WEIGHT, QTY_IN_BOX, BOX_WEIGHT, ITEM_WIDTH, ITEM_LENGTH, ITEM_HEIGHT, ITEM_CBM, SALE_PLACE, ORDER_QTY, ORDERER_NM
