--분석함수3
--실전문제①
SELECT LAG(NULL, 1, OUTBOUND_DATE) OVER(PARTITION BY OUTBOUND_DATE ORDER BY RNK) AS OUTBOUND_DATE
     , RNK, ITEM_NM, ORDER_QTY
  FROM (SELECT M1.OUTBOUND_DATE, M2.ITEM_NM, SUM(M2.ORDER_QTY) AS ORDER_QTY
             , ROW_NUMBER() OVER(PARTITION BY M1.OUTBOUND_DATE ORDER BY SUM(M2.ORDER_QTY) DESC) AS RNK
          FROM LO_OUT_M M1 JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
         WHERE M1.OUTBOUND_DATE BETWEEN '2019-09-03' AND '2019-09-05'
         GROUP BY M1.OUTBOUND_DATE, M2.ITEM_NM
        )
 WHERE RNK <= 3
;

--실전문제②
SELECT LAG(NULL, 1, OUTBOUND_DATE) OVER(PARTITION BY OUTBOUND_DATE ORDER BY RNK) AS OUTBOUND_DATE
      , RNK, ITEM_NM, ORDER_QTY, RATE
  FROM (SELECT M1.OUTBOUND_DATE, M2.ITEM_NM, SUM(M2.ORDER_QTY) AS ORDER_QTY
             , RANK() OVER(PARTITION BY M1.OUTBOUND_DATE ORDER BY SUM(M2.ORDER_QTY) DESC)             AS RNK
             , ROUND(RATIO_TO_REPORT(SUM(M2.ORDER_QTY)) OVER(PARTITION BY M1.OUTBOUND_DATE) * 100, 2) AS RATE
          FROM LO_OUT_M M1 JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
         WHERE M1.OUTBOUND_DATE BETWEEN '2019-09-03' AND '2019-09-05'
         GROUP BY M1.OUTBOUND_DATE, M2.ITEM_NM
        )
 WHERE RNK <= 3
;

--실전문제③
SELECT LAG(NULL, 1, OUTBOUND_DATE) OVER(PARTITION BY OUTBOUND_DATE ORDER BY RNK) AS OUTBOUND_DATE
     , RNK, ITEM_NM, ORDER_QTY, RATE
     , SUM(RATE) OVER(PARTITION BY OUTBOUND_DATE ORDER BY RNK) AS ACC_RATE
  FROM (SELECT M1.OUTBOUND_DATE, M2.ITEM_NM, SUM(M2.ORDER_QTY) AS ORDER_QTY
             , RANK() OVER(PARTITION BY M1.OUTBOUND_DATE ORDER BY SUM(M2.ORDER_QTY) DESC)             AS RNK
             , ROUND(RATIO_TO_REPORT(SUM(M2.ORDER_QTY)) OVER(PARTITION BY M1.OUTBOUND_DATE) * 100, 2) AS RATE
          FROM LO_OUT_M M1 JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
         WHERE M1.OUTBOUND_DATE BETWEEN '2019-09-03' AND '2019-09-05'
         GROUP BY M1.OUTBOUND_DATE, M2.ITEM_NM
        )
 WHERE RNK <= 3
;

--데이터압축하기1
--실전문제①
SELECT TO_CHAR(M1.OUTBOUND_DATE, 'YYYY/MM/DD')
     , SUM(M2.ORDER_QTY) AS SUM_QTY
  FROM LO_OUT_M M1 JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
 WHERE M1.OUTBOUND_DATE BETWEEN TO_DATE(:OUTBOUND_DATE || '01', 'YYYY-MM-DD')
                            AND ADD_MONTHS(TO_DATE(:OUTBOUND_DATE, 'YYYY-MM'), 1) - 1
 GROUP BY M1.OUTBOUND_DATE
 ORDER BY SUM_QTY DESC
;

--실전문제②
SELECT SUM(CASE TO_CHAR(OUTBOUND_DATE, 'D') WHEN '1' THEN M2.ORDER_QTY END) AS SUN
     , SUM(CASE TO_CHAR(OUTBOUND_DATE, 'D') WHEN '2' THEN M2.ORDER_QTY END) AS MON
     , SUM(CASE TO_CHAR(OUTBOUND_DATE, 'D') WHEN '3' THEN M2.ORDER_QTY END) AS TUE
     , SUM(CASE TO_CHAR(OUTBOUND_DATE, 'D') WHEN '4' THEN M2.ORDER_QTY END) AS WED
     , SUM(CASE TO_CHAR(OUTBOUND_DATE, 'D') WHEN '5' THEN M2.ORDER_QTY END) AS THU
     , SUM(CASE TO_CHAR(OUTBOUND_DATE, 'D') WHEN '6' THEN M2.ORDER_QTY END) AS FRI
     , SUM(CASE TO_CHAR(OUTBOUND_DATE, 'D') WHEN '7' THEN M2.ORDER_QTY END) AS SAT
  FROM LO_OUT_M M1 JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
 WHERE M1.OUTBOUND_DATE BETWEEN TO_DATE(:OUTBOUND_DATE || '01', 'YYYY-MM-DD')
                            AND ADD_MONTHS(TO_DATE(:OUTBOUND_DATE, 'YYYY-MM'), 1)
;

SELECT TO_CHAR(M1.OUTBOUND_DATE, 'DAY') AS DAY
     , SUM(M2.ORDER_QTY) AS ORDER_QTY
  FROM LO_OUT_M M1 JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
 WHERE M1.OUTBOUND_DATE BETWEEN TO_DATE(:OUTBOUND_DATE || '01', 'YYYY-MM-DD')
                            AND ADD_MONTHS(TO_DATE(:OUTBOUND_DATE, 'YYYY-MM-'), 1)
 GROUP BY TO_CHAR(M1.OUTBOUND_DATE, 'D')
        , TO_CHAR(M1.OUTBOUND_DATE, 'DAY')
 ORDER BY TO_CHAR(M1.OUTBOUND_DATE, 'D')
;

--실전문제③
SELECT SUM(CASE TO_CHAR(M1.OUTBOUND_DATE, 'MM') WHEN '01' THEN M2.ORDER_QTY END) AS M01
     , SUM(CASE TO_CHAR(M1.OUTBOUND_DATE, 'MM') WHEN '02' THEN M2.ORDER_QTY END) AS M02
     , SUM(CASE TO_CHAR(M1.OUTBOUND_DATE, 'MM') WHEN '03' THEN M2.ORDER_QTY END) AS M03
     , SUM(CASE TO_CHAR(M1.OUTBOUND_DATE, 'Q')  WHEN '1' THEN M2.ORDER_QTY END)  AS Q1
     , SUM(CASE TO_CHAR(M1.OUTBOUND_DATE, 'MM') WHEN '04' THEN M2.ORDER_QTY END) AS M04
     , SUM(CASE TO_CHAR(M1.OUTBOUND_DATE, 'MM') WHEN '05' THEN M2.ORDER_QTY END) AS M05
     , SUM(CASE TO_CHAR(M1.OUTBOUND_DATE, 'MM') WHEN '06' THEN M2.ORDER_QTY END) AS M06
     , SUM(CASE TO_CHAR(M1.OUTBOUND_DATE, 'Q')  WHEN '2' THEN M2.ORDER_QTY END)  AS Q2
     , SUM(CASE TO_CHAR(M1.OUTBOUND_DATE, 'MM') WHEN '07' THEN M2.ORDER_QTY END) AS M07
     , SUM(CASE TO_CHAR(M1.OUTBOUND_DATE, 'MM') WHEN '08' THEN M2.ORDER_QTY END) AS M08
     , SUM(CASE TO_CHAR(M1.OUTBOUND_DATE, 'MM') WHEN '09' THEN M2.ORDER_QTY END) AS M09
     , SUM(CASE TO_CHAR(M1.OUTBOUND_DATE, 'Q')  WHEN '3' THEN M2.ORDER_QTY END)  AS Q3
     , SUM(CASE TO_CHAR(M1.OUTBOUND_DATE, 'MM') WHEN '10' THEN M2.ORDER_QTY END) AS M10
     , SUM(CASE TO_CHAR(M1.OUTBOUND_DATE, 'MM') WHEN '11' THEN M2.ORDER_QTY END) AS M11
     , SUM(CASE TO_CHAR(M1.OUTBOUND_DATE, 'MM') WHEN '12' THEN M2.ORDER_QTY END) AS M12
     , SUM(CASE TO_CHAR(M1.OUTBOUND_DATE, 'Q')  WHEN '4' THEN M2.ORDER_QTY END)  AS Q4
  FROM LO_OUT_M M1 JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
 WHERE M1.OUTBOUND_DATE BETWEEN TO_DATE(:OUTBOUND_DATE || '0101', 'YYYY-MM-DD')
                            AND TO_DATE(:OUTBOUND_DATE || '1231', 'YYYY-MM-DD')
;

--실전문제④
SELECT RNUM, ITEM_CD, ITEM_NM, SUM(ORDER_QTY) AS ORDER_QTY
  FROM (SELECT CASE WHEN RNUM <= 5 THEN RNUM      ELSE 0                END AS RNUM
             , CASE WHEN RNUM <= 5 THEN ITEM_CD   ELSE '99999'          END AS ITEM_CD
             , CASE WHEN RNUM <= 5 THEN ITEM_NM   ELSE 'TOP5제외 합계' END AS ITEM_NM
             , ORDER_QTY
          FROM (SELECT ROW_NUMBER() OVER(ORDER BY SUM(ORDER_QTY) DESC) AS RNUM
                     , ITEM_CD, ITEM_NM, SUM(ORDER_QTY) AS ORDER_QTY
                  FROM(SELECT M2.ITEM_CD, M2.ITEM_NM, SUM(M2.ORDER_QTY) AS ORDER_QTY
                        FROM LO_OUT_M M1 JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
                       WHERE M1.OUTBOUND_DATE BETWEEN '2019-06-01' AND '2019-06-30'
                         AND M2.ITEM_NM LIKE '%참치%'
                       GROUP BY M2.ITEM_CD, M2.ITEM_NM
                       ORDER BY ORDER_QTY DESC
                      )
                 GROUP BY ITEM_CD, ITEM_NM 
                )
        )
 GROUP BY RNUM, ITEM_CD, ITEM_NM
;

--상반기평가
--문제①
SELECT CASE WHEN ROWNUM <= 3 THEN DY ELSE 'etc' END AS DY
     , SUM(ORDER_QTY) AS ORDER_QTY
     , ROW_NUMBER() OVER(ORDER BY SUM(ORDER_QTY)) AS RNUM
  FROM (SELECT TO_CHAR(M1.OUTBOUND_DATE, 'DY') AS DY, SUM(M2.ORDER_QTY) AS ORDER_QTY
          FROM LO_OUT_M M1 JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
         WHERE M1.OUTBOUND_DATE BETWEEN ADD_MONTHS(TO_DATE(:OUTBOUND_DATE, 'YYYY-MM-DD'), -1)
                                    AND TO_DATE(:OUTBOUND_DATE, 'YYYY-MM-DD')
         GROUP BY TO_CHAR(M1.OUTBOUND_DATE, 'DY')
         ORDER BY ORDER_QTY DESC
        )
 GROUP BY CASE WHEN ROWNUM <= 3 THEN DY ELSE 'etc' END
;

--문제②
SELECT SUM(CASE WHEN TO_CHAR(M1.OUTBOUND_DATE, 'D') BETWEEN '2' AND '6' THEN M2.ORDER_QTY END) AS WEEKDAYS
     , SUM(CASE WHEN TO_CHAR(M1.OUTBOUND_DATE, 'D') IN ('1', '7')       THEN M2.ORDER_QTY END) AS WEEKEND
  FROM LO_OUT_M M1 JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
 WHERE M1.OUTBOUND_DATE BETWEEN ADD_MONTHS(TO_DATE(:OUTBOUND_DATE, 'YYYY-MM-DD'), -1)
                            AND TO_DATE(:OUTBOUND_DATE, 'YYYY-MM-DD')
;

--문제③
SELECT CASE WHEN TO_CHAR(M1.OUTBOUND_DATE, 'D') IN      ('1', '7')  THEN 'WEEKDAYS'
            WHEN TO_CHAR(M1.OUTBOUND_DATE, 'D') BETWEEN '2' AND '6' THEN 'WEEKENDS' END AS WEEK
     , SUM(M2.ORDER_QTY) AS SUM_QTY
  FROM LO_OUT_M M1 JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
 WHERE M1.OUTBOUND_DATE BETWEEN ADD_MONTHS(TO_DATE(:OUTBOUND_DATE, 'YYYY-MM-DD'), -1)
                            AND TO_DATE(:OUTBOUND_DATE, 'YYYY-MM-DD')
 GROUP BY CASE WHEN TO_CHAR(M1.OUTBOUND_DATE, 'D') IN      ('1', '7')  THEN 'WEEKDAYS'
               WHEN TO_CHAR(M1.OUTBOUND_DATE, 'D') BETWEEN '2' AND '6' THEN 'WEEKENDS' END
;

--문제④
SELECT TO_CHAR(T1.OUT_DATE, 'YYYY/MM/DD') AS OUT_DATE
     , TO_CHAR(T1.OUT_DATE, 'DY') AS DY
  FROM (SELECT ADD_MONTHS(TO_DATE(:OUTBOUND_DATE, 'YYYY-MM-DD'), -1) + LEVEL AS OUT_DATE
          FROM DUAL
          CONNECT BY LEVEL <= TO_DATE(:OUTBOUND_DATE ,'YYYY-MM-DD') - ADD_MONTHS(TO_DATE(:OUTBOUND_DATE ,'YYYY-MM-DD'), -1)
        ) T1 LEFT JOIN (SELECT M1.OUTBOUND_DATE, SUM(M2.ORDER_QTY) AS ORDER_QTY
                       FROM LO_OUT_M M1 JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
                      WHERE M1.OUTBOUND_DATE BETWEEN ADD_MONTHS(TO_DATE(:OUTBOUND_DATE, 'YYYY-MM-DD'), -1)
                                                 AND TO_DATE(:OUTBOUND_DATE, 'YYYY-MM-DD')
                      GROUP BY M1.OUTBOUND_DATE
                      ) T2 ON T2.OUTBOUND_DATE = T1.OUT_DATE
 WHERE T2.ORDER_QTY IS NULL
 ORDER BY OUT_DATE
;

--문제⑤
SELECT TO_CHAR(OUTBOUND_DATE, 'YYYY/MM/DD') AS OUTBOUND_DATE
     , TO_CHAR(OUTBOUND_DATE, 'DY')         AS DY
     , SUM_QTY
     , CASE WHEN SUM_QTY > ROUND(AVG(SUM_QTY) OVER(PARTITION BY TO_CHAR(OUTBOUND_DATE, 'DY'))) THEN 'High'
            ELSE 'Low' END AS GRADE
     , ROUND(AVG(SUM_QTY) OVER(PARTITION BY TO_CHAR(OUTBOUND_DATE, 'DY'))) AS AVG
  FROM (SELECT M1.OUTBOUND_DATE, SUM(M2.ORDER_QTY) AS SUM_QTY
          FROM LO_OUT_M M1 JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
         WHERE M1.OUTBOUND_DATE BETWEEN ADD_MONTHS(TO_DATE(:OUTBOUND_DATE, 'YYYY-MM-DD'), -1)
                                    AND TO_DATE(:OUTBOUND_DATE, 'YYYY-MM-DD')
         GROUP BY M1.OUTBOUND_DATE
        )
 WHERE SUM_QTY >= 170000
 ORDER BY OUTBOUND_DATE
;

--보너스 문제
 SELECT CASE :SCHOOL WHEN '1' THEN '초등학교 '
                     WHEN '2' THEN '중학교 '
                     WHEN '3' THEN '고등학교 ' END || LEVEL || '학년' AS SCHOOL
      , CASE :SCHOOL WHEN '1' THEN SUBSTR(:BIRTHDAY, 1, 4) + 7
                     WHEN '2' THEN SUBSTR(:BIRTHDAY, 1, 4) + 13
                     WHEN '3' THEN SUBSTR(:BIRTHDAY, 1, 4) + 16 END AS YEAR
   FROM DUAL
CONNECT BY LEVEL <= CASE :SCHOOL WHEN '1' THEN 6
                                 WHEN '2' THEN 3
                                 WHEN '3' THEN 3 END
;

--서브쿼리, 스칼라 쿼리
--1 - (1)
SELECT M2.BRAND_CD, M2.INVOICE_NO, M2.LINE_NO, M2.ITEM_CD, M2.ORDER_QTY
  FROM A_OUT_M M1 JOIN A_OUT_D M2 ON  M2.BRAND_CD   = M1.BRAND_CD
                                  AND M2.INVOICE_NO = M1.INVOICE_NO
 WHERE M1.OUTBOUND_DATE = '2023-01-03'
;

--1 - (2)
SELECT M2.BRAND_CD, M2.INVOICE_NO, M2.LINE_NO, M2.ITEM_CD, M2.ORDER_QTY
  FROM A_OUT_M M1 JOIN A_OUT_D M2 ON  M2.BRAND_CD   = M1.BRAND_CD
                                  AND M2.INVOICE_NO = M1.INVOICE_NO
 WHERE M2.BRAND_CD     = '1001' 
   AND M1.OUT_TYPE_DIV LIKE 'M1%'
;

--1 - (3)
SELECT *
  FROM A_OUT_M M2
 WHERE (BRAND_CD, INVOICE_NO) IN (SELECT M1.BRAND_CD, M1.INVOICE_NO
                                  FROM A_OUT_D M1
                                 GROUP BY M1.BRAND_CD, M1.INVOICE_NO
                                 HAVING SUM(M1.ORDER_QTY) >= 3)
;

--2 - (1)
SELECT M1.BRAND_CD, M1.ITEM_CD, SUM(M1.ORDER_QTY) AS SUM_QTY
     , (SELECT M2.ITEM_NM
          FROM A_ITEM M2
         WHERE M2.BRAND_CD = M1.BRAND_CD
           AND M2.ITEM_CD  = M1.ITEM_CD) AS ITEM_NM
  FROM A_OUT_D M1
 GROUP BY M1.BRAND_CD, M1.ITEM_CD
;

--실전문제①
SELECT *
  FROM ( SELECT TO_DATE(:OUTBOUND_DATE, 'YYYY-MM-DD') + LEVEL AS OUTBOUND_DATE
           FROM DUAL
        CONNECT BY LEVEL <= 10) M1
 WHERE EXISTS ( SELECT 1
                  FROM LO_OUT_M M2
                 WHERE M2.OUTBOUND_DATE = M1.OUTBOUND_DATE
                )
;

--실전문제②
SELECT INVOICE_NO, OUT_TYPE_DIV, OUT_BOX_DIV
     , TO_NUMBER(SUBSTR(MAX_VAL, 1, 5)) AS MAX_ORDER_QTY
     , TO_NUMBER(SUBSTR(MAX_VAL, 7, 3)) AS MAX_LINE
  FROM( SELECT INVOICE_NO, OUT_TYPE_DIV, OUT_BOX_DIV
             , (SELECT MAX(LPAD(M2.ORDER_QTY, 5, '0') || '-' || LPAD(M2.LINE_NO, 3, '0'))
                  FROM LO_OUT_D M2
                 WHERE M2.INVOICE_NO = M1.INVOICE_NO
                ) AS MAX_VAL
          FROM LO_OUT_M M1
         WHERE M1.OUTBOUND_DATE = '2019-06-03'
           AND OUTBOUND_NO BETWEEN 'D190603-897353'
                               AND 'D190603-897360'
        )
;