--내장함수일반
--1 - (1)
SELECT OUTBOUND_DATE
     , TO_CHAR(OUTBOUND_DATE, 'DY') AS DY
     , INVOICE_NO, ORDER_NM
  FROM A_OUT_M
 WHERE BRAND_CD = '1001'
;

--1 - (2)
SELECT OUTBOUND_DATE
     , TO_CHAR(OUTBOUND_DATE, 'DY') AS DY
     , INVOICE_NO
     , CASE MOD(TO_NUMBER(SUBSTR(INVOICE_NO, 2)), 2) WHEN 0 THEN '짝수' ELSE '홀수' END AS EVENODD
     , ORDER_NM
  FROM A_OUT_M
 WHERE BRAND_CD = '1001'
;

--2 - (1)
SELECT BRAND_CD, COUNT(1) AS CNT
  FROM A_OUT_M
 GROUP BY BRAND_CD
;

--2 - (2)
SELECT BRAND_CD
     , TO_CHAR(OUTBOUND_DATE, 'DY') AS DY
     , COUNT(1) AS CNT
  FROM A_OUT_M
 GROUP BY BRAND_CD
     , TO_CHAR(OUTBOUND_DATE, 'DY')
     , TO_CHAR(OUTBOUND_DATE, 'D')
 ORDER BY BRAND_CD
     , TO_CHAR(OUTBOUND_DATE, 'D')
;

--2 - (3)
SELECT BRAND_CD
     , CASE MOD(TO_NUMBER(SUBSTR(INVOICE_NO, 2)), 2) WHEN 0 THEN '짝수' ELSE '홀수' END AS EVENODD
     , SUM(ORDER_QTY) AS SUM_QTY
  FROM A_OUT_D
 GROUP BY BRAND_CD
        , CASE MOD(TO_NUMBER(SUBSTR(INVOICE_NO, 2)), 2) WHEN 0 THEN '짝수' ELSE '홀수' END
 ORDER BY BRAND_CD
;

--실전문제①
SELECT INVOICE_NO, OUTBOUND_DATE
     , TO_CHAR(OUTBOUND_DATE, 'DAY') AS DAYY
     , OUTBOUND_NO
  FROM LO_OUT_M
 WHERE INVOICE_NO IN ('346724706214','346724793596','346724869970')
;

--실전문제②
SELECT NVL(TO_CHAR(SUM(ORDER_QTY)), 'Empty..') AS ORDER_QTY
  FROM LO_OUT_D
 WHERE INVOICE_NO = '346724706215'
;

--내장함수CASE
--1 - (1)
SELECT OUTBOUND_DATE
     , TO_CHAR(OUTBOUND_DATE, 'DAY') AS DY
     , INVOICE_NO
     , CASE MOD(TO_NUMBER(SUBSTR(INVOICE_NO, 2)), 2) WHEN 0 THEN '짝수' ELSE '홀수' END AS EVENODD
     , ORDER_NM
     , CASE WHEN OUT_TYPE_DIV LIKE 'M1%' THEN '상온' 
            WHEN OUT_TYPE_DIV LIKE 'M2%' THEN '저온' END AS TEMP
  FROM A_OUT_M
;

--1 - (2)
SELECT BRAND_CD, INVOICE_NO, LINE_NO, ITEM_CD, ORDER_QTY
     , CASE WHEN ORDER_QTY BETWEEN 1 AND 2 THEN '하'
            WHEN ORDER_QTY BETWEEN 3 AND 4 THEN '중'
            WHEN ORDER_QTY >= 5            THEN '상'
            END AS GRADE
  FROM A_OUT_D
;

--2 - (1)
SELECT M1.BRAND_CD
     , CASE WHEN OUT_TYPE_DIV LIKE 'M1%' THEN '상온' 
            WHEN OUT_TYPE_DIV LIKE 'M2%' THEN '저온' END AS TEMP
     , SUM(M1.ORDER_QTY) AS SUM_QTY
  FROM A_OUT_D M1
       JOIN A_OUT_M M2 ON  M2.BRAND_CD   = M1.BRAND_CD
                       AND M2.INVOICE_NO = M1.INVOICE_NO
 GROUP BY M1.BRAND_CD
     , CASE WHEN OUT_TYPE_DIV LIKE 'M1%' THEN '상온' 
            WHEN OUT_TYPE_DIV LIKE 'M2%' THEN '저온' END
;

--2 - (2)
SELECT M1.BRAND_CD
     , CASE WHEN ORDER_QTY BETWEEN 1 AND 2 THEN '하'
            WHEN ORDER_QTY BETWEEN 3 AND 4 THEN '중'
            WHEN ORDER_QTY >= 5            THEN '상'
            END AS GRADE
     , SUM(M1.ORDER_QTY) AS SUM_QTY
  FROM A_OUT_D M1
       JOIN A_OUT_M M2 ON  M2.BRAND_CD   = M1.BRAND_CD
                       AND M2.INVOICE_NO = M1.INVOICE_NO
 GROUP BY M1.BRAND_CD
     , CASE WHEN ORDER_QTY BETWEEN 1 AND 2 THEN '하'
            WHEN ORDER_QTY BETWEEN 3 AND 4 THEN '중'
            WHEN ORDER_QTY >= 5            THEN '상'
            END
 ORDER BY BRAND_CD
        , CASE GRADE WHEN '상' THEN 0
                     WHEN '중' THEN 1
                     ELSE           2 END
;

--2 - (3)
SELECT CASE WHEN ROWNUM > 2 THEN 'etc' 
            ELSE                 ITEM_CD END AS ITEM_CD
     , SUM(SUM_QTY) AS SUM_QTY
  FROM (SELECT ITEM_CD
             , SUM(ORDER_QTY) AS SUM_QTY
          FROM A_OUT_D
         GROUP BY ITEM_CD
         ORDER BY SUM_QTY DESC
        )
 GROUP BY CASE WHEN ROWNUM > 2 THEN 'etc' 
               ELSE                 ITEM_CD END 
 ORDER BY CASE WHEN ITEM_CD = 'etc' THEN 999 ELSE 1 END
        , ITEM_CD
;

--3 - (1)
SELECT BRAND_CD, INVOICE_NO, LINE_NO, ITEM_CD, ORDER_QTY
     , CASE WHEN ORDER_QTY BETWEEN 1 AND 2 THEN '하'
            WHEN ORDER_QTY BETWEEN 3 AND 4 THEN '중'
            WHEN ORDER_QTY >=      5       THEN '상' END AS GRADE
  FROM A_OUT_D
 WHERE BRAND_CD = '1001'
 ORDER BY CASE WHEN ITEM_CD = 'C' THEN 0 ELSE 1 END
        , ITEM_CD, ORDER_QTY DESC
;

--실전문제①
SELECT OUTBOUND_DATE
     , COUNT() AS INVOICE_CNT
     , COUNT() AS M1_CNT
     , COUNT() AS M2_CNT
  FROM LO_OUT_M
 WHERE :OUTBOUND_DATE BETWEEN TO_DATE(SUBSTR(:OUTBOUND_DATE, 1, 8) || '01', 'YYYY-MM-DD')
                          AND TO_DATE(:OUTBOUND_DATE, 'YYYY-MM-DD')
   AND OUT_BOX_DIV LIKE 
      CASE :COND WHEN '1' THEN 'D%'
                 WHEN '2' THEN 'F%'
                 WHEN '0' THEN NULL
                 ELSE          'EQWE' END
;

--실전문제②
SELECT ITEM_BAR_CD, COUNT(DISTINCT ITEM_CD) AS ITEM_CNT
  FROM LO_OUT_D
 GROUP BY ITEM_BAR_CD
 HAVING COUNT(DISTINCT ITEM_CD) >= 2
 ORDER BY CASE WHEN ITEM_BAR_CD IS NULL THEN 999 ELSE 0 END
        , ITEM_CNT DESC
;

--실전문제③
SELECT COUNT(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '01' THEN 1 ELSE NULL END) AS M01
     , COUNT(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '02' THEN 1 ELSE NULL END) AS M02
     , COUNT(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '03' THEN 1 ELSE NULL END) AS M03
     , COUNT(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '04' THEN 1 ELSE NULL END) AS M04
     , COUNT(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '05' THEN 1 ELSE NULL END) AS M05
     , COUNT(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '06' THEN 1 ELSE NULL END) AS M06
     , COUNT(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '07' THEN 1 ELSE NULL END) AS M07
     , COUNT(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '08' THEN 1 ELSE NULL END) AS M08
     , COUNT(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '09' THEN 1 ELSE NULL END) AS M09
     , COUNT(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '10' THEN 1 ELSE NULL END) AS M10
     , COUNT(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '11' THEN 1 ELSE NULL END) AS M11
     , COUNT(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '12' THEN 1 ELSE NULL END) AS M12
  FROM LO_OUT_M
 WHERE OUTBOUND_DATE BETWEEN TO_DATE(:YEAR || '0101', 'YYYY-MM-DD')
                         AND TO_DATE(:YEAR || '1231', 'YYYY-MM-DD')
;

--실전문제④
SELECT OUTBOUND_DATE
     , COUNT(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '01' THEN 1 ELSE NULL END) AS M01
     , COUNT(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '02' THEN 1 ELSE NULL END) AS M02
     , COUNT(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '03' THEN 1 ELSE NULL END) AS M03
     , COUNT(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '04' THEN 1 ELSE NULL END) AS M04
     , COUNT(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '05' THEN 1 ELSE NULL END) AS M05
     , COUNT(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '06' THEN 1 ELSE NULL END) AS M06
     , COUNT(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '07' THEN 1 ELSE NULL END) AS M07
     , COUNT(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '08' THEN 1 ELSE NULL END) AS M08
     , COUNT(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '09' THEN 1 ELSE NULL END) AS M09
     , COUNT(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '10' THEN 1 ELSE NULL END) AS M10
     , COUNT(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '11' THEN 1 ELSE NULL END) AS M11
     , COUNT(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '12' THEN 1 ELSE NULL END) AS M12
  FROM LO_OUT_M
 WHERE OUTBOUND_DATE BETWEEN TO_DATE(:YEAR || '0101', 'YYYY-MM-DD')
                         AND TO_DATE(:YEAR || '1231', 'YYYY-MM-DD')
 GROUP BY OUTBOUND_DATE
;

--실전문제⑤
SELECT TO_CHAR(OUTBOUND_DATE, 'YYYY') AS YYYY
     , COUNT(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '01' THEN 1 ELSE NULL END) AS M01
     , COUNT(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '02' THEN 1 ELSE NULL END) AS M02
     , COUNT(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '03' THEN 1 ELSE NULL END) AS M03
     , COUNT(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '04' THEN 1 ELSE NULL END) AS M04
     , COUNT(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '05' THEN 1 ELSE NULL END) AS M05
     , COUNT(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '06' THEN 1 ELSE NULL END) AS M06
     , COUNT(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '07' THEN 1 ELSE NULL END) AS M07
     , COUNT(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '08' THEN 1 ELSE NULL END) AS M08
     , COUNT(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '09' THEN 1 ELSE NULL END) AS M09
     , COUNT(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '10' THEN 1 ELSE NULL END) AS M10
     , COUNT(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '11' THEN 1 ELSE NULL END) AS M11
     , COUNT(CASE TO_CHAR(OUTBOUND_DATE, 'MM') WHEN '12' THEN 1 ELSE NULL END) AS M12
  FROM LO_OUT_M
 WHERE TO_CHAR(OUTBOUND_DATE, 'YYYY') <> '2023'
 GROUP BY TO_CHAR(OUTBOUND_DATE, 'YYYY')
;

--실전문제⑥
SELECT INVOICE_NO, LINE_NO, ITEM_CD, ITEM_NM, ORDER_QTY
  FROM LO_OUT_D
 WHERE INVOICE_NO = '346724706214'
 ORDER BY CASE :SORT_TYPE WHEN '1' THEN LINE_NO
                          WHEN '2' THEN ORDER_QTY END, LINE_NO
;

--조인기본
--1 - (1)
SELECT M1.BRAND_CD, M1.INVOICE_NO, M1.LINE_NO, M1.ORDER_QTY
  FROM A_OUT_D M1 JOIN A_OUT_M M2 ON  M2.BRAND_CD   = M1.BRAND_CD
                                  AND M2.INVOICE_NO = M1.INVOICE_NO
                                  AND M2.OUTBOUND_DATE = '2023-01-04'
 WHERE M1.ITEM_CD IN ('B', 'D')
;

--1 - (2)
SELECT M1.BRAND_CD, M2.OUTBOUND_DATE, M1.ITEM_CD
     , SUM(M1.ORDER_QTY) AS SUM_QTY
  FROM A_OUT_D M1 JOIN A_OUT_M M2 ON  M2.BRAND_CD   = M1.BRAND_CD
                                  AND M2.INVOICE_NO = M1.INVOICE_NO
                                  AND M2.OUTBOUND_DATE BETWEEN '2023-01-03' AND '2023-01-04'
 WHERE M1.ITEM_CD IN ('B', 'D')
 GROUP BY M1.BRAND_CD, M2.OUTBOUND_DATE, M1.ITEM_CD
 ORDER BY BRAND_CD, OUTBOUND_DATE
;

--1 - (3)
SELECT *
  FROM (SELECT M1.BRAND_CD, M1.ORDER_NM, SUM(M2.ORDER_QTY) AS SUM_QTY
          FROM A_OUT_M M1 JOIN A_OUT_D M2 ON  M2.BRAND_CD   = M1.BRAND_CD
                                          AND M2.INVOICE_NO = M1.INVOICE_NO
         GROUP BY M1.BRAND_CD, M1.ORDER_NM
         ORDER BY SUM_QTY DESC
        )
 WHERE ROWNUM = 1
;

--2 - (1)
SELECT M1.BRAND_CD, M2.OUTBOUND_DATE, M1.INVOICE_NO, M1.ITEM_CD, M3.ITEM_NM, M1.ORDER_QTY
  FROM A_OUT_D M1 JOIN A_OUT_M M2 ON  M2.BRAND_CD   = M1.BRAND_CD
                                  AND M2.INVOICE_NO = M1.INVOICE_NO
                                  AND M2.OUTBOUND_DATE BETWEEN '2023-01-01' AND '2023-01-04'
                  JOIN A_ITEM M3  ON  M3.BRAND_CD   = M1.BRAND_CD
                                  AND M3.ITEM_CD    = M1.ITEM_CD
 WHERE M1.ORDER_QTY >= 3
;

--2 - (2)
SELECT M3.BRAND_CD, M3.ITEM_CD, M3.SUM_QTY, M4.QTY_IN_BOX
  FROM (SELECT M1.BRAND_CD, M1.ITEM_CD
             , SUM(M1.ORDER_QTY) AS SUM_QTY
          FROM A_OUT_D M1 JOIN A_OUT_M M2 ON  M2.BRAND_CD   = M1.BRAND_CD
                                          AND M2.INVOICE_NO = M1.INVOICE_NO
         GROUP BY M1.BRAND_CD, M1.ITEM_CD
        ) M3 JOIN A_ITEM  M4 ON  M4.BRAND_CD = M3.BRAND_CD
                             AND M4.ITEM_CD  = M3.ITEM_CD
;

--2 - (3)
SELECT BRAND_CD, ITEM_CD, SUM_QTY, QTY_IN_BOX
     , TRUNC(SUM_QTY/QTY_IN_BOX) AS CNT_BOX
     , MOD(SUM_QTY, QTY_IN_BOX)  AS CNT_PCS
  FROM (SELECT M3.BRAND_CD, M3.ITEM_CD, M3.SUM_QTY, M4.QTY_IN_BOX
          FROM (SELECT M1.BRAND_CD, M1.ITEM_CD
                     , SUM(M1.ORDER_QTY) AS SUM_QTY
                  FROM A_OUT_D M1 JOIN A_OUT_M M2 ON  M2.BRAND_CD   = M1.BRAND_CD
                                                  AND M2.INVOICE_NO = M1.INVOICE_NO
                 GROUP BY M1.BRAND_CD, M1.ITEM_CD
                ) M3 JOIN A_ITEM  M4 ON  M4.BRAND_CD = M3.BRAND_CD
                                     AND M4.ITEM_CD  = M3.ITEM_CD
        )
;
--2 - (4)
SELECT *
  FROM (SELECT BRAND_CD, ITEM_CD, SUM_QTY, QTY_IN_BOX
             , TRUNC(SUM_QTY/QTY_IN_BOX) AS CNT_BOX
             , MOD(SUM_QTY, QTY_IN_BOX)  AS CNT_PCS
          FROM (SELECT M3.BRAND_CD, M3.ITEM_CD, M3.SUM_QTY, M4.QTY_IN_BOX
                  FROM (SELECT M1.BRAND_CD, M1.ITEM_CD
                             , SUM(M1.ORDER_QTY) AS SUM_QTY
                          FROM A_OUT_D M1 JOIN A_OUT_M M2 ON  M2.BRAND_CD   = M1.BRAND_CD
                                                          AND M2.INVOICE_NO = M1.INVOICE_NO
                         GROUP BY M1.BRAND_CD, M1.ITEM_CD
                        ) M3 JOIN A_ITEM  M4 ON  M4.BRAND_CD = M3.BRAND_CD
                                             AND M4.ITEM_CD  = M3.ITEM_CD
                )
         ORDER BY CNT_BOX DESC
        )
 WHERE ROWNUM < 4
;

--실전문제①
SELECT M1.INVOICE_NO, M1.OUTBOUND_DATE, M1.OUT_TYPE_DIV, M2.LINE_NO, M2.ITEM_CD, M3.ITEM_NM, M2.ORDER_QTY
  FROM LO_OUT_M M1 JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
                   JOIN CM_ITEM  M3 ON M3.ITEM_CD    = M2.ITEM_CD
 WHERE M1.INVOICE_NO IN ('346724703834', '346724722535', '346724717915')
;

--실전문제②
SELECT M1.INVOICE_NO, M1.OUTBOUND_DATE, M1.OUT_TYPE_DIV, M2.LINE_NO, M2.ITEM_CD, M3.ITEM_NM, M2.ORDER_QTY
     , C1.CODE_NM
     , C2.CODE_NM
  FROM LO_OUT_M M1 JOIN LO_OUT_D M2     ON  M2.INVOICE_NO = M1.INVOICE_NO
                   JOIN CM_ITEM  M3     ON  M3.ITEM_CD    = M2.ITEM_CD
                   LEFT JOIN CS_CODE C1 ON  C1.CODE_GRP = 'LDIV01'
                                        AND C1.CODE_CD  = M1.TEMP_DIV
                   LEFT JOIN CS_CODE C2 ON  C2.CODE_GRP = 'LDIV03'
                                        AND C2.CODE_CD  = M1.OUT_TYPE_DIV
 WHERE M1.INVOICE_NO IN ('346724703834', '346724722535', '346724717915')
;

--조인활용1
--실전문제①
SELECT * 
  FROM (SELECT M1.INVOICE_NO, M1.OUTBOUND_NO, M1.OUTBOUND_BATCH, M2.ITEM_CD, M2.ITEM_NM, SUM(M2.ORDER_QTY) AS ORDER_QTY
          FROM LO_OUT_M M1 JOIN LO_OUT_D M2 ON  M2.INVOICE_NO = M1.INVOICE_NO
                                            AND ITEM_NM LIKE '%골뱅이%'
         WHERE M1.OUTBOUND_DATE BETWEEN '2019-09-03' AND '2019-09-10'
         GROUP BY M1.INVOICE_NO, M1.OUTBOUND_NO, M1.OUTBOUND_BATCH, M2.ITEM_CD, M2.ITEM_NM
         ORDER BY ORDER_QTY DESC
        )
 WHERE ROWNUM < 6
;

--실전문제②
SELECT M1.ITEM_CD, M3.ITEM_NM, SUM(M1.ORDER_QTY) AS ORDER_QTY
  FROM LO_OUT_D M1 JOIN LO_OUT_M M2 ON  M2.INVOICE_NO     = M1.INVOICE_NO
                                    AND M2.OUTBOUND_DATE BETWEEN '2019-09-03' AND '2019-09-10'
                                    AND OUT_BOX_DIV       = 'D5'
                   JOIN CM_ITEM  M3 ON  M3.ITEM_CD    = M1.ITEM_CD
 WHERE M2.OUT_BOX_DIV = 'D5'
 GROUP BY M1.ITEM_CD, M3.ITEM_NM
 ORDER BY ORDER_QTY DESC
;

--실전문제③
SELECT M1.INVOICE_NO, M1.OUTBOUND_DATE, M1.OUT_TYPE_DIV, M2.LINE_NO, M2.ITEM_CD, M3.ITEM_NM, M2.ORDER_QTY
     , CASE WHEN C1.CODE_NM IS NULL THEN 'Failed...' END AS TEMP_NM
     , C2.CODE_NM AS OUT_TYPE_NM
  FROM LO_OUT_M M1 JOIN      LO_OUT_D M2 ON  M2.INVOICE_NO  = M1.INVOICE_NO
                   JOIN      CM_ITEM  M3 ON  M3.ITEM_CD     = M2.ITEM_CD
                   LEFT JOIN CS_CODE C1  ON  C1.CODE_GRP    = 'LDIV011'
                                         AND C1.CODE_CD     = M1.TEMP_DIV
                   LEFT JOIN CS_CODE C2  ON  C2.CODE_GRP    = 'LDIV03'
                                         AND C2.CODE_CD     = M1.OUT_TYPE_DIV
 WHERE M1.INVOICE_NO IN ('346724703834','346724722535','346724717915')
;

--실전문제④
SELECT OUT_DATE, NVL(SUM(ORDER_QTY), 0) AS QTY
  FROM (SELECT TRUNC(TO_DATE(:OUTBOUND_DATE, 'YYYY-MM-DD'), 'MM') + LEVEL - 1 AS OUT_DATE
          FROM DUAL
         CONNECT BY LEVEL <= TO_DATE(:OUTBOUND_DATE, 'YYYY-MM-DD') - TO_DATE(SUBSTR(:OUTBOUND_DATE, 1, 8) || '01', 'YYYY-MM-DD') + 1
        ) M1 LEFT JOIN LO_OUT_M M2 ON M2.OUTBOUND_DATE = M1.OUT_DATE
             LEFT JOIN LO_OUT_D M3 ON M3.INVOICE_NO    = M2.INVOICE_NO
 GROUP BY OUT_DATE
 ORDER BY OUT_DATE
;


--LO_OUT_M: INVOICE_NO, OUTBOUND_DATE, OUTBOUND_NO, ORDER_PLACE, OUTBOUND_BATCH, TEMP_DIV, OUT_TYPE_DIV, OUT_BOX_DIV, OUT_BOX_NM, SET_TYPE_CD, SET_TYPE_NM, SET_QTY, SET_STATE, WORK_SEQ, REG_USER_ID, REG_DATETIME
--LO_OUT_D: INVOICE_NO, LINE_NO, ITEM_CD, ITEM_NM, ITEM_BAR_CD, BOX_BAR_CD, ITEM_WEIGHT, QTY_IN_BOX, BOX_WEIGHT, ITEM_WIDTH, ITEM_LENGTH, ITEM_HEIGHT, ITEM_CBM, SALE_PLACE, ORDER_QTY, REG_USER_ID, REG_DATETIME, OUT_TYPE_DIV_D
--CM_ITEM: ITEM_CD, ITEM_NM, QTY_IN_BOX, REG_USER_ID, REG_DATETIME
--SELECT * FROM CS_CODE;