--분석함수1
--실전문제①
SELECT INVOICE_NO, LINE_NO, ITEM_NM, ORDER_QTY
     , MIN(ORDER_QTY) OVER(PARTITION BY INVOICE_NO) AS MIN1
     , MIN(ORDER_QTY) OVER()                        AS MIN2
     , MAX(ORDER_QTY) OVER(PARTITION BY INVOICE_NO) AS MAX1
     , MAX(ORDER_QTY) OVER()                        AS MAX2
  FROM LO_OUT_D
 WHERE INVOICE_NO IN ('346724703845', '346724706214', '346724706225')
;

--분석함수2
--실전문제①
SELECT OUTBOUND_DATE, OUTBOUND_BATCH, ORDER_QTY
     , RANK()         OVER(PARTITION BY OUTBOUND_DATE ORDER BY ORDER_QTY DESC) AS RNK_PER_DAY
     , SUM(ORDER_QTY) OVER(PARTITION BY OUTBOUND_DATE ORDER BY ORDER_QTY DESC) AS ACC_SUM_PER_RNK
     , SUM(ORDER_QTY) OVER(PARTITION BY OUTBOUND_DATE)                         AS SUM_PER_DAY
     , COUNT(1)       OVER(PARTITION BY OUTBOUND_DATE)                         AS CNT_PER_DAY
     , COUNT(1)       OVER()                                                   AS CNT_TOT
  FROM (SELECT M1.OUTBOUND_DATE, M1.OUTBOUND_BATCH, SUM(M2.ORDER_QTY) AS ORDER_QTY
          FROM LO_OUT_M M1 JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
         WHERE M1.OUTBOUND_DATE BETWEEN '2019-09-03' AND '2019-09-10'
           AND M1.OUT_TYPE_DIV  = 'M11'
         GROUP BY M1.OUTBOUND_DATE, M1.OUTBOUND_BATCH
         ORDER BY OUTBOUND_DATE
        )
;

--실전문제②
SELECT OUTBOUND_DATE
     , RANK() OVER(PARTITION BY OUTBOUND_DATE ORDER BY ORDER_QTY DESC) AS RNK_PER_DAY
     , OUTBOUND_BATCH, ORDER_QTY
  FROM (SELECT M1.OUTBOUND_DATE, M1.OUTBOUND_BATCH
             , SUM(M2.ORDER_QTY) AS ORDER_QTY
          FROM LO_OUT_M M1 JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
         WHERE M1.OUTBOUND_DATE BETWEEN '2019-09-03' AND '2019-09-10'
           AND M1.OUT_TYPE_DIV  = 'M11'
         GROUP BY M1.OUTBOUND_DATE, M1.OUTBOUND_BATCH
        )
;

--실전문제③
SELECT CASE WHEN LAG(OUT_DATE) OVER(PARTITION BY OUT_DATE ORDER BY OUT_DATE) IS NULL THEN TO_CHAR(OUT_DATE, 'YY/MM/DD') END AS OUT_DATE
     , COUNT(1) OVER(PARTITION BY OUT_DATE ORDER BY ORDER_QTY DESC) AS CNT_PAR_DAY
     , OUTBOUND_BATCH
     , ORDER_QTY
  FROM (SELECT M1.OUTBOUND_DATE AS OUT_DATE, M1.OUTBOUND_BATCH, SUM(M2.ORDER_QTY) AS ORDER_QTY
          FROM LO_OUT_M M1 JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
         WHERE M1.OUTBOUND_DATE BETWEEN '2019-09-03' AND '2019-09-10'
           AND M1.OUT_TYPE_DIV  = 'M11'
         GROUP BY M1.OUTBOUND_DATE, M1.OUTBOUND_BATCH
         ORDER BY OUTBOUND_DATE
        )
;

--실전문제④
SELECT CASE WHEN RNK <= 5 THEN TO_CHAR(OUTBOUND_DATE, 'YYYY-MM-DD') ELSE '기타' END AS OUTBOUND_DATE
     , SUM(ORDER_QTY) AS ORDER_QTY
     , SUM(RATE)      AS RATE
     , MAX(RNK)       AS RNK
  FROM (SELECT M1.OUTBOUND_DATE, SUM(M2.ORDER_QTY) AS ORDER_QTY
              , ROUND(RATIO_TO_REPORT(SUM(M2.ORDER_QTY)) OVER() * 100, 3) AS RATE
              , RANK() OVER(ORDER BY SUM(M2.ORDER_QTY) DESC) AS RNK
          FROM LO_OUT_M M1 JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
         WHERE M1.OUTBOUND_DATE BETWEEN '2019-09-01' AND '2019-09-15'
         GROUP BY M1.OUTBOUND_DATE
         ORDER BY ORDER_QTY DESC
        )
 GROUP BY CASE WHEN RNK <= 5 THEN TO_CHAR(OUTBOUND_DATE, 'YYYY-MM-DD')  ELSE '기타' END
;

--분석함수3
--실전문제①
SELECT OUTBOUND_DATE, RNK, ITEM_NM, ORDER_QTY
  FROM (SELECT M1.OUTBOUND_DATE, M2.ITEM_NM, SUM(M2.ORDER_QTY) AS ORDER_QTY
             , RANK() OVER(PARTITION BY M1.OUTBOUND_DATE ORDER BY SUM(M2.ORDER_QTY) DESC) AS RNK
          FROM LO_OUT_M M1 JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
         WHERE M1.OUTBOUND_DATE BETWEEN '2019-09-03' AND '2019-09-05'
         GROUP BY M1.OUTBOUND_DATE, M2.ITEM_NM
         ORDER BY OUTBOUND_DATE, ORDER_QTY DESC
        )
 WHERE RNK <= 3
;

--실전문제②
SELECT LAG(NULL, 1, OUTBOUND_DATE) OVER(PARTITION BY OUTBOUND_DATE ORDER BY RNK) AS OUTBOUND_DATE
     , RNK, ITEM_NM, ORDER_QTY, RATIO
 FROM (SELECT M1.OUTBOUND_DATE, M2.ITEM_NM, SUM(M2.ORDER_QTY) AS ORDER_QTY
             , RANK() OVER(PARTITION BY M1.OUTBOUND_DATE ORDER BY SUM(M2.ORDER_QTY) DESC) AS RNK
             , ROUND(RATIO_TO_REPORT(SUM(M2.ORDER_QTY)) OVER(PARTITION BY OUTBOUND_DATE) * 100, 2) AS RATIO
          FROM LO_OUT_M M1 JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
         WHERE M1.OUTBOUND_DATE BETWEEN '2019-09-03' AND '2019-09-05'
         GROUP BY M1.OUTBOUND_DATE, M2.ITEM_NM
         ORDER BY OUTBOUND_DATE, ORDER_QTY DESC
        )
 WHERE RNK <= 3
;

--실전문제③
SELECT LAG(NULL, 1, OUTBOUND_DATE) OVER(PARTITION BY OUTBOUND_DATE ORDER BY RNK) AS OUTBOUND_DATE
     , RNK, ITEM_NM, ORDER_QTY, RATIO
     , SUM(RATIO) OVER(PARTITION BY OUTBOUND_DATE ORDER BY RNK) AS ACC_RNK
  FROM (SELECT M1.OUTBOUND_DATE, M2.ITEM_NM, SUM(M2.ORDER_QTY) AS ORDER_QTY
             , RANK() OVER(PARTITION BY M1.OUTBOUND_DATE ORDER BY SUM(M2.ORDER_QTY) DESC) AS RNK
             , ROUND(RATIO_TO_REPORT(SUM(M2.ORDER_QTY)) OVER(PARTITION BY M1.OUTBOUND_DATE) * 100, 2) AS RATIO
          FROM LO_OUT_M M1 JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
         WHERE M1.OUTBOUND_DATE BETWEEN '2019-09-03' AND '2019-09-05'
         GROUP BY M1.OUTBOUND_DATE, M2.ITEM_NM
        )
 WHERE RNK <= 3
;

--데이터압축하기1
--실전문제①
SELECT OUTBOUND_DATE
     , SUM(M2.ORDER_QTY) AS SUM_QTY
  FROM LO_OUT_M M1 JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
 WHERE OUTBOUND_DATE BETWEEN TO_DATE(:OUTBOUND_DATE, 'YYYY-MM')
                         AND LAST_DAY(TO_DATE(:OUTBOUND_DATE, 'YYYY-MM'))
 GROUP BY OUTBOUND_DATE
 ORDER BY SUM_QTY DESC
;

--실전문제②
SELECT SUM(CASE TO_CHAR(M1.OUTBOUND_DATE, 'D') WHEN '1' THEN M2.ORDER_QTY END) AS SUN
     , SUM(CASE TO_CHAR(M1.OUTBOUND_DATE, 'D') WHEN '2' THEN M2.ORDER_QTY END) AS MON
     , SUM(CASE TO_CHAR(M1.OUTBOUND_DATE, 'D') WHEN '3' THEN M2.ORDER_QTY END) AS TUE
     , SUM(CASE TO_CHAR(M1.OUTBOUND_DATE, 'D') WHEN '4' THEN M2.ORDER_QTY END) AS WED
     , SUM(CASE TO_CHAR(M1.OUTBOUND_DATE, 'D') WHEN '5' THEN M2.ORDER_QTY END) AS THU
     , SUM(CASE TO_CHAR(M1.OUTBOUND_DATE, 'D') WHEN '6' THEN M2.ORDER_QTY END) AS FRI
     , SUM(CASE TO_CHAR(M1.OUTBOUND_DATE, 'D') WHEN '7' THEN M2.ORDER_QTY END) AS SAT
  FROM LO_OUT_M M1 JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
 WHERE M1.OUTBOUND_DATE BETWEEN TO_DATE(:OUTBOUND_DATE, 'YYYY-MM')
                            AND LAST_DAY(TO_DATE(:OUTBOUND_DATE, 'YYYY-MM'))
;

SELECT TO_CHAR(M1.OUTBOUND_DATE, 'DAY') AS DAY
     , SUM(M2.ORDER_QTY) AS ORDER_QTY
  FROM LO_OUT_M M1 JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
 WHERE M1.OUTBOUND_DATE BETWEEN TO_DATE(:OUTBOUND_DATE, 'YYYY-MM')
                            AND LAST_DAY(TO_DATE(:OUTBOUND_DATE, 'YYYY-MM'))
 GROUP BY TO_CHAR(M1.OUTBOUND_DATE, 'DAY') 
        , TO_CHAR(M1.OUTBOUND_DATE, 'D') 
;

--실전문제③
SELECT SUM(CASE TO_CHAR(M1.OUTBOUND_DATE, 'MM') WHEN '01' THEN M2.ORDER_QTY END) AS M01
     , SUM(CASE TO_CHAR(M1.OUTBOUND_DATE, 'MM') WHEN '02' THEN M2.ORDER_QTY END) AS M02
     , SUM(CASE TO_CHAR(M1.OUTBOUND_DATE, 'MM') WHEN '03' THEN M2.ORDER_QTY END) AS M03
     , SUM(CASE TO_CHAR(M1.OUTBOUND_DATE, 'Q') WHEN '1' THEN M2.ORDER_QTY END)   AS Q1
     , SUM(CASE TO_CHAR(M1.OUTBOUND_DATE, 'MM') WHEN '04' THEN M2.ORDER_QTY END) AS M04
     , SUM(CASE TO_CHAR(M1.OUTBOUND_DATE, 'MM') WHEN '05' THEN M2.ORDER_QTY END) AS M05
     , SUM(CASE TO_CHAR(M1.OUTBOUND_DATE, 'MM') WHEN '06' THEN M2.ORDER_QTY END) AS M06
     , SUM(CASE TO_CHAR(M1.OUTBOUND_DATE, 'Q') WHEN '2' THEN M2.ORDER_QTY END)   AS Q2
     , SUM(CASE TO_CHAR(M1.OUTBOUND_DATE, 'MM') WHEN '07' THEN M2.ORDER_QTY END) AS M07
     , SUM(CASE TO_CHAR(M1.OUTBOUND_DATE, 'MM') WHEN '08' THEN M2.ORDER_QTY END) AS M08
     , SUM(CASE TO_CHAR(M1.OUTBOUND_DATE, 'MM') WHEN '09' THEN M2.ORDER_QTY END) AS M09
     , SUM(CASE TO_CHAR(M1.OUTBOUND_DATE, 'Q') WHEN '3' THEN M2.ORDER_QTY END)   AS Q3
     , SUM(CASE TO_CHAR(M1.OUTBOUND_DATE, 'MM') WHEN '10' THEN M2.ORDER_QTY END) AS M10
     , SUM(CASE TO_CHAR(M1.OUTBOUND_DATE, 'MM') WHEN '11' THEN M2.ORDER_QTY END) AS M11
     , SUM(CASE TO_CHAR(M1.OUTBOUND_DATE, 'MM') WHEN '12' THEN M2.ORDER_QTY END) AS M12
     , SUM(CASE TO_CHAR(M1.OUTBOUND_DATE, 'Q') WHEN '4' THEN M2.ORDER_QTY END)   AS Q4
  FROM LO_OUT_M M1 JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
 WHERE M1.OUTBOUND_DATE BETWEEN TO_DATE('2019' || '0101', 'YYYY-MM-DD')
                            AND TO_DATE('2019' || '1231', 'YYYY-MM-DD')
;

--실전문제④
SELECT CASE WHEN ROWNUM <= 5 THEN ROWNUM ELSE 0 END               AS RNUM
     , CASE WHEN ROWNUM <= 5 THEN ITEM_CD ELSE '99999' END          AS ITEM_CD
     , CASE WHEN ROWNUM <= 5 THEN ITEM_NM ELSE 'TOP5제외 합계' END AS ITEM_NM
     , SUM(ORDER_QTY) AS ORDER_QTY
  FROM (SELECT M2.ITEM_CD, M2.ITEM_NM, SUM(M2.ORDER_QTY) AS ORDER_QTY
          FROM LO_OUT_M M1 JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
         WHERE M1.OUTBOUND_DATE BETWEEN '2019-06-01' AND '2019-06-30'
           AND M2.ITEM_NM       LIKE     '%참치%'
         GROUP BY M2.ITEM_CD, M2.ITEM_NM
         ORDER BY SUM(M2.ORDER_QTY) DESC
        )
 GROUP BY CASE WHEN ROWNUM <= 5 THEN ROWNUM ELSE 0 END
        , CASE WHEN ROWNUM <= 5 THEN ITEM_CD ELSE '99999' END          
        , CASE WHEN ROWNUM <= 5 THEN ITEM_NM ELSE 'TOP5제외 합계' END 
 ORDER BY CASE WHEN RNUM = 0 THEN 99999 ELSE RNUM END
;

WITH BASE_01 AS (
SELECT M2.ITEM_CD, M2.ITEM_NM, SUM(M2.ORDER_QTY) AS ORDER_QTY
          FROM LO_OUT_M M1 JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
         WHERE M1.OUTBOUND_DATE BETWEEN '2019-06-01' AND '2019-06-30'
           AND M2.ITEM_NM       LIKE     '%참치%'
         GROUP BY M2.ITEM_CD, M2.ITEM_NM
         ORDER BY SUM(M2.ORDER_QTY) DESC
),
     BASE_02 AS (
SELECT ITEM_CD, ITEM_NM, ORDER_QTY
     , ROW_NUMBER() OVER(ORDER BY ORDER_QTY DESC) AS RNUM
  FROM BASE_01
 ORDER BY ORDER_QTY DESC
)

SELECT RNUM, ITEM_CD, ITEM_NM, ORDER_QTY
  FROM BASE_02
 WHERE RNUM <= 5

UNION ALL

SELECT 0               AS RNUM
     , '99999'         AS ITEM_CD
     , 'TOP5제외 합계'  AS ITEM_NM
     , SUM(ORDER_QTY)  AS ORDER_QTY
  FROM BASE_02
 WHERE RNUM >= 5
;
