--이전 복습: 실전문제②-스칼라 쿼리
SELECT INVOICE_NO
     , OUT_TYPE_DIV
     , OUT_BOX_DIV
     , TO_NUMBER(SUBSTR(MAX_VAL, 1, 5)) AS MAX_ORDER_QTY
     , TO_NUMBER(SUBSTR(MAX_VAL, 7, 9)) AS MAX_LINE_NO
  FROM (
        SELECT M1.INVOICE_NO
             , M1.OUT_TYPE_DIV
             , M1.OUT_BOX_DIV
             , (SELECT MAX(LPAD(M2.ORDER_QTY, 5, '0') || '-' || LPAD(M2.LINE_NO, 3, '0')) 
                  FROM LO_OUT_D M2
                 WHERE M2.INVOICE_NO = M1.INVOICE_NO) AS MAX_VAL
          FROM LO_OUT_M M1
         WHERE M1.OUTBOUND_DATE = '2019-06-03'
           AND OUTBOUND_NO      BETWEEN 'D190603-897353'
                                    AND 'D190603-897360'
        )
;

--내장함수일반
--실전문제①
SELECT INVOICE_NO
     , OUTBOUND_DATE
     , TO_CHAR(OUTBOUND_DATE, 'DAY') AS DAYY
     , OUTBOUND_NO
  FROM LO_OUT_M
 WHERE INVOICE_NO IN ('346724706214', '346724793596', '346724869970')
;

--실전문제②
SELECT NVL(TO_CHAR(SUM(ORDER_QTY)), 'Empty..') AS ORDER_QTY
  FROM LO_OUT_D
 WHERE INVOICE_NO = '346724706215'
;

--내장함수CASE
--실전문제①
SELECT OUTBOUND_DATE
     , COUNT(1) AS INVOICE_CNT
     , COUNT(CASE WHEN OUT_TYPE_DIV LIKE 'M1%' THEN 1 END) M1_CNT
     , COUNT(CASE WHEN OUT_TYPE_DIV LIKE 'M2%' THEN 1 END) M2_CNT
  FROM LO_OUT_M
 WHERE OUTBOUND_DATE BETWEEN TO_DATE(SUBSTR(:OUTBOUND_DATE, 1, 7) || '01', 'YYYY-MM-DD')
                         AND TO_DATE(:OUTBOUND_DATE, 'YYYY-MM-DD')
   AND OUT_BOX_DIV LIKE CASE :COND WHEN '1' THEN 'D'
                                   WHEN '2' THEN 'F'
                                   WHEN '0' THEN NULL
                                   END || '%'
 GROUP BY OUTBOUND_DATE
;

--실전문제②
SELECT ITEM_BAR_CD
     , COUNT(DISTINCT ITEM_CD) AS ITEM_CNT 
  FROM LO_OUT_D
 GROUP BY ITEM_BAR_CD
HAVING COUNT(DISTINCT ITEM_CD) >= 2
 ORDER BY CASE WHEN ITEM_BAR_CD IS NULL THEN 2 ELSE 1 END
        , ITEM_CNT DESC
;